# Leave-One-Site-Out Model Robustness

This notebook holds out each of the six lakes in turn. For each run, all pixels from the held-out lake are reserved for the final site test; whole scene IDs from the other five lakes are assigned to approximately 80% training and 20% test data. Both contain all five sites, both sensors, all seasons, and all classes. The only permitted train/test scene overlap is the configured Geneva 2021-09-06 scene, allocated as 120/30 rows whenever Geneva is not the held-out site. DT, RF, and XGBoost each receive exactly one Optuna search over one fixed stratified five-fold CV. There are no repeated CV-seed searches or candidate re-ranking passes.

In [1]:
from dataclasses import replace
import importlib
from pathlib import Path
import sys
import pandas as pd

ROOT = Path.cwd().resolve().parent if Path.cwd().name == "notebooks" else Path.cwd().resolve()
sys.path.insert(0, str(ROOT / "src"))

import lswt_cloud_masking.leave_one_site_out as loso
importlib.reload(loso)
from lswt_cloud_masking.leave_one_site_out import LeaveOneSiteOutConfig, run_leave_one_site_out_pipeline

/opt/homebrew/Caskroom/miniforge/base/envs/lswt-thin-cloud/lib/python3.14/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## 1. Configure the experiment

Keep `SMOKE_TEST = True` for a one-site, one-trial check. Set it to `False` for all six held-out sites with 120 trials per classifier. Completed full site runs are resumable.

In [2]:
config = LeaveOneSiteOutConfig.from_json(ROOT / "configs" / "leave_one_site_out.example.json")

SMOKE_TEST = False
if SMOKE_TEST:
    sites = config.held_out_sites or ["ageri"]
    config = replace(
        config,
        output_dir=f"{config.output_dir}_smoke",
        held_out_sites=sites[:1],
        cv_splits=2,
        n_trials_dt=1,
        n_trials_rf=1,
        n_trials_xgb=1,
        xgb_max_estimators=100,
        xgb_early_stopping_rounds=10,
        resume_completed_runs=False,
    )

print("Held-out sites:", config.held_out_sites)
print("CV folds:", config.cv_splits)
print("Trials (DT/RF/XGB):", config.n_trials_dt, config.n_trials_rf, config.n_trials_xgb)
print("Output root:", (ROOT / config.output_dir).resolve())
config

Held-out sites: ['ageri', 'bianco', 'geneva', 'greifensee', 'mendota', 'venice']
CV folds: 5
Trials (DT/RF/XGB): 200 200 200
Output root: /Users/airahaghi/Documents/Trishna/Scripts/LSWT-ML-thin-cloud-masking/outputs/leave_one_site_out

LeaveOneSiteOutConfig(input_csvs=['data/df_train_all.csv', 'data/df_test_all.csv'], output_dir='outputs/leave_one_site_out', held_out_sites=['ageri', 'bianco', 'geneva', 'greifensee', 'mendota', 'venice'], site_column='lakeN', scene_column='scene_id', label_column='lst_class', drop_columns=['lakeN', 'scene_id', 'lst_raw', 'lst_filt', 'raamap', 'vzamap', 'szamap'], test_fraction=0.2, split_random_state=42, scene_split_search_iterations=100000, scene_split_max_test_fraction_deviation=0.01, overlap_exception_scene_id='LC08_L1TP_196028_20210906_20210915_02_T1', overlap_exception_site='geneva', overlap_exception_class=3, overlap_exception_train_rows=120, overlap_exception_test_rows=30, cv_splits=5, cv_random_state=42, model_random_state=42, optuna_seed=42, scoring='balanced_accuracy', n_trials_dt=200, n_trials_rf=200, n_trials_xgb=200, optuna_n_jobs=1, rf_n_jobs=-1, xgb_n_jobs=-1, xgb_sample_weight='balanced', xgb_max_estimators=1500, xgb_early_stopping_rounds=250, resume_completed_runs=True)

## 2. Create splits, tune once, refit, and evaluate

The approximately 20% scene-disjoint test and held-out lake are never passed to Optuna or XGBoost early stopping. XGBoost early stopping uses only each training fold's internal validation fold.

In [3]:
loso_result = run_leave_one_site_out_pipeline(config, project_root=ROOT)
loso_result["paths"]

[1/6] Creating 80/20 split with 'ageri' completely held out.

[I 2026-08-25 14:38:13,264] A new study created in memory with name: DecisionTree_LOSO

[1/6] Running one 5-fold search per model.
  ageri: tuning Decision Tree (200 trials).

[I 2026-08-25 14:38:13,810] Trial 0 finished with value: 0.6595973227540484 and parameters: {'max_depth': 12, 'min_samples_split': 96, 'min_samples_leaf': 59, 'max_features': 0.6, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 1.3480180290890803e-07}. Best is trial 0 with value: 0.6595973227540484.
[I 2026-08-25 14:38:13,876] Trial 1 finished with value: 0.5398143487544739 and parameters: {'max_depth': 17, 'min_samples_split': 44, 'min_samples_leaf': 24, 'max_features': 0.8, 'criterion': 'log_loss', 'splitter': 'random', 'class_weight': None, 'ccp_alpha': 0.0043873144324354085}. Best is trial 0 with value: 0.6595973227540484.
[I 2026-08-25 14:38:13,904] Trial 2 finished with value: 0.5070742159351423 and parameters: {'max_depth': 30, 'min_samples_split': 82, 'min_samples_leaf': 25, 'max_features': 'sqrt', 'criterion': 'gini', 'splitter': 'random', 'class_weight': None, 'ccp_alpha': 0.006124806805925988}. Best is trial 0 with value: 0.6595973227540484.
[I 2026-08-25 14:38:14,081] Trial 3 finished with value: 0.6172748782099748 and parameters: {'max_depth': 24, 'min_samples_split': 95, 'min_samples_leaf': 72, 'max_features': 'sqrt', 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 0.00041245717727594227}. Best is trial 0 with value: 0.6595973227540484.
[I 2026-08-25 14:38:14,180] Trial 4 finished with value: 0.5495290789771665 and parameters: {'max_depth': 4, 'min_samples_split': 99, 'min_samples_leaf': 62, 'max_features': 'log2', 'criterion': 'entropy', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 1.5027137214154575e-07}. Best is trial 0 with value: 0.6595973227540484.
[I 2026-08-25 14:38:14,896] Trial 5 finished with value: 0.6561499544447607 and parameters: {'max_depth': 11, 'min_samples_split': 74, 'min_samples_leaf': 52, 'max_features': None, 'criterion': 'gini', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 2.8501838758433707e-05}. Best is trial 0 with value: 0.6595973227540484.
[I 2026-08-25 14:38:14,924] Trial 6 finished with value: 0.5441681100850451 and parameters: {'max_depth': 11, 'min_samples_split': 52, 'min_samples_leaf': 73, 'max_features': 'log2', 'criterion': 'entropy', 'splitter': 'random', 'class_weight': None, 'ccp_alpha': 0.0017697543538533224}. Best is trial 0 with value: 0.6595973227540484.
[I 2026-08-25 14:38:15,577] Trial 7 finished with value: 0.6588034352544637 and parameters: {'max_depth': 17, 'min_samples_split': 81, 'min_samples_leaf': 72, 'max_features': 0.8, 'criterion': 'entropy', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 1.8298712093870903e-07}. Best is trial 0 with value: 0.6595973227540484.
[I 2026-08-25 14:38:15,647] Trial 8 finished with value: 0.639281884735699 and parameters: {'max_depth': 17, 'min_samples_split': 71, 'min_samples_leaf': 30, 'max_features': None, 'criterion': 'entropy', 'splitter': 'random', 'class_weight': None, 'ccp_alpha': 1.0333896431462928e-08}. Best is trial 0 with value: 0.6595973227540484.
[I 2026-08-25 14:38:15,813] Trial 9 finished with value: 0.650136133985382 and parameters: {'max_depth': 16, 'min_samples_split': 99, 'min_samples_leaf': 20, 'max_features': 'sqrt', 'criterion': 'gini', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 1.3685182782317289e-05}. Best is trial 0 with value: 0.6595973227540484.
[I 2026-08-25 14:38:16,020] Trial 10 finished with value: 0.5491560966623805 and parameters: {'max_depth': 3, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 0.6, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 1.3312110800515346e-09}. Best is trial 0 with value: 0.6595973227540484.
[I 2026-08-25 14:38:16,335] Trial 11 finished with value: 0.6433304485433959 and parameters: {'max_depth': 11, 'min_samples_split': 56, 'min_samples_leaf': 50, 'max_features': 0.4, 'criterion': 'entropy', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 4.0184266648472174e-07}. Best is trial 0 with value: 0.6595973227540484.
[I 2026-08-25 14:38:16,990] Trial 12 finished with value: 0.6696765238299045 and parameters: {'max_depth': 22, 'min_samples_split': 82, 'min_samples_leaf': 55, 'max_features': 0.8, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 2.9769597875852853e-07}. Best is trial 12 with value: 0.6696765238299045.
[I 2026-08-25 14:38:17,503] Trial 13 finished with value: 0.6767364363678818 and parameters: {'max_depth': 24, 'min_samples_split': 65, 'min_samples_leaf': 45, 'max_features': 0.6, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 3.7405716246710883e-06}. Best is trial 13 with value: 0.6767364363678818.
[I 2026-08-25 14:38:18,039] Trial 14 finished with value: 0.6754312623726925 and parameters: {'max_depth': 25, 'min_samples_split': 34, 'min_samples_leaf': 40, 'max_features': 0.6, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 6.174767494322357e-06}. Best is trial 13 with value: 0.6767364363678818.
[I 2026-08-25 14:38:18,562] Trial 15 finished with value: 0.6863399380273051 and parameters: {'max_depth': 29, 'min_samples_split': 27, 'min_samples_leaf': 39, 'max_features': 0.6, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 6.605753887567251e-06}. Best is trial 15 with value: 0.6863399380273051.
[I 2026-08-25 14:38:19,083] Trial 16 finished with value: 0.6863399380273051 and parameters: {'max_depth': 29, 'min_samples_split': 18, 'min_samples_leaf': 39, 'max_features': 0.6, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 2.14902646134673e-06}. Best is trial 15 with value: 0.6863399380273051.
[I 2026-08-25 14:38:19,625] Trial 17 finished with value: 0.6815163119128387 and parameters: {'max_depth': 30, 'min_samples_split': 18, 'min_samples_leaf': 36, 'max_features': 0.6, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 4.8797375543227104e-05}. Best is trial 15 with value: 0.6863399380273051.
[I 2026-08-25 14:38:19,698] Trial 18 finished with value: 0.6535797724097153 and parameters: {'max_depth': 27, 'min_samples_split': 25, 'min_samples_leaf': 10, 'max_features': 0.4, 'criterion': 'log_loss', 'splitter': 'random', 'class_weight': 'balanced', 'ccp_alpha': 1.4641752838244698e-06}. Best is trial 15 with value: 0.6863399380273051.
[I 2026-08-25 14:38:20,252] Trial 19 finished with value: 0.6843237172274758 and parameters: {'max_depth': 28, 'min_samples_split': 8, 'min_samples_leaf': 35, 'max_features': 0.6, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 0.00014968727235882198}. Best is trial 15 with value: 0.6863399380273051.
[I 2026-08-25 14:38:20,739] Trial 20 finished with value: 0.673802391286566 and parameters: {'max_depth': 21, 'min_samples_split': 32, 'min_samples_leaf': 43, 'max_features': 0.6, 'criterion': 'gini', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 2.3612852478582268e-08}. Best is trial 15 with value: 0.6863399380273051.
[I 2026-08-25 14:38:21,272] Trial 21 finished with value: 0.681484172233215 and parameters: {'max_depth': 27, 'min_samples_split': 8, 'min_samples_leaf': 36, 'max_features': 0.6, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 0.00016034016651872627}. Best is trial 15 with value: 0.6863399380273051.
[I 2026-08-25 14:38:21,838] Trial 22 finished with value: 0.6962399878126376 and parameters: {'max_depth': 28, 'min_samples_split': 14, 'min_samples_leaf': 30, 'max_features': 0.6, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 0.00014696568329408322}. Best is trial 22 with value: 0.6962399878126376.
[I 2026-08-25 14:38:22,427] Trial 23 finished with value: 0.7297824118127202 and parameters: {'max_depth': 30, 'min_samples_split': 18, 'min_samples_leaf': 15, 'max_features': 0.6, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 1.2661739591796867e-06}. Best is trial 23 with value: 0.7297824118127202.
[I 2026-08-25 14:38:23,026] Trial 24 finished with value: 0.7219233514589573 and parameters: {'max_depth': 26, 'min_samples_split': 20, 'min_samples_leaf': 13, 'max_features': 0.6, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 0.000413735710547358}. Best is trial 23 with value: 0.7297824118127202.
[I 2026-08-25 14:38:23,624] Trial 25 finished with value: 0.7274441926775052 and parameters: {'max_depth': 20, 'min_samples_split': 18, 'min_samples_leaf': 15, 'max_features': 0.6, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 0.0005982543500126752}. Best is trial 23 with value: 0.7297824118127202.
[I 2026-08-25 14:38:23,661] Trial 26 finished with value: 0.5882047470656577 and parameters: {'max_depth': 20, 'min_samples_split': 41, 'min_samples_leaf': 14, 'max_features': 'log2', 'criterion': 'log_loss', 'splitter': 'random', 'class_weight': 'balanced', 'ccp_alpha': 0.0009590234985155447}. Best is trial 23 with value: 0.7297824118127202.
[I 2026-08-25 14:38:24,075] Trial 27 finished with value: 0.7108815308826565 and parameters: {'max_depth': 25, 'min_samples_split': 23, 'min_samples_leaf': 5, 'max_features': 0.4, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 0.0008096895493012256}. Best is trial 23 with value: 0.7297824118127202.
[I 2026-08-25 14:38:24,973] Trial 28 finished with value: 0.7216771739168819 and parameters: {'max_depth': 19, 'min_samples_split': 36, 'min_samples_leaf': 15, 'max_features': None, 'criterion': 'gini', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 4.8659774449257785e-05}. Best is trial 23 with value: 0.7297824118127202.
[I 2026-08-25 14:38:25,583] Trial 29 finished with value: 0.7341444606071786 and parameters: {'max_depth': 23, 'min_samples_split': 11, 'min_samples_leaf': 9, 'max_features': 0.6, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 1.5809001036767288e-08}. Best is trial 29 with value: 0.7341444606071786.
[I 2026-08-25 14:38:26,183] Trial 30 finished with value: 0.7274599578536965 and parameters: {'max_depth': 14, 'min_samples_split': 2, 'min_samples_leaf': 7, 'max_features': 0.6, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 2.945435662302505e-08}. Best is trial 29 with value: 0.7341444606071786.
[I 2026-08-25 14:38:26,784] Trial 31 finished with value: 0.7274599578536965 and parameters: {'max_depth': 14, 'min_samples_split': 2, 'min_samples_leaf': 7, 'max_features': 0.6, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 3.705435814399429e-08}. Best is trial 29 with value: 0.7341444606071786.
[I 2026-08-25 14:38:27,384] Trial 32 finished with value: 0.7274599578536965 and parameters: {'max_depth': 14, 'min_samples_split': 2, 'min_samples_leaf': 7, 'max_features': 0.6, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 3.232718555549257e-08}. Best is trial 29 with value: 0.7341444606071786.
[I 2026-08-25 14:38:27,856] Trial 33 finished with value: 0.6316514192524849 and parameters: {'max_depth': 8, 'min_samples_split': 11, 'min_samples_leaf': 1, 'max_features': 0.6, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 3.0318367769637515e-09}. Best is trial 29 with value: 0.7341444606071786.
[I 2026-08-25 14:38:27,903] Trial 34 finished with value: 0.5942762168801597 and parameters: {'max_depth': 8, 'min_samples_split': 7, 'min_samples_leaf': 21, 'max_features': 0.8, 'criterion': 'log_loss', 'splitter': 'random', 'class_weight': 'balanced', 'ccp_alpha': 5.6050115473285234e-08}. Best is trial 29 with value: 0.7341444606071786.
[I 2026-08-25 14:38:28,117] Trial 35 finished with value: 0.6881803441663833 and parameters: {'max_depth': 14, 'min_samples_split': 13, 'min_samples_leaf': 8, 'max_features': 'sqrt', 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 6.487300430102237e-09}. Best is trial 29 with value: 0.7341444606071786.
[I 2026-08-25 14:38:28,541] Trial 36 finished with value: 0.6147639382063871 and parameters: {'max_depth': 7, 'min_samples_split': 3, 'min_samples_leaf': 21, 'max_features': 0.6, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 9.129803355120518e-07}. Best is trial 29 with value: 0.7341444606071786.
[I 2026-08-25 14:38:28,604] Trial 37 finished with value: 0.6648848934945739 and parameters: {'max_depth': 14, 'min_samples_split': 13, 'min_samples_leaf': 4, 'max_features': 0.6, 'criterion': 'gini', 'splitter': 'random', 'class_weight': None, 'ccp_alpha': 7.470160379606147e-08}. Best is trial 29 with value: 0.7341444606071786.
[I 2026-08-25 14:38:28,819] Trial 38 finished with value: 0.6807292634546347 and parameters: {'max_depth': 13, 'min_samples_split': 7, 'min_samples_leaf': 11, 'max_features': 'log2', 'criterion': 'entropy', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 1.1420077477530208e-08}. Best is trial 29 with value: 0.7341444606071786.
[I 2026-08-25 14:38:29,754] Trial 39 finished with value: 0.7068763715681833 and parameters: {'max_depth': 23, 'min_samples_split': 29, 'min_samples_leaf': 25, 'max_features': None, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 6.046922340115093e-07}. Best is trial 29 with value: 0.7341444606071786.
[I 2026-08-25 14:38:29,797] Trial 40 finished with value: 0.5536176328835906 and parameters: {'max_depth': 18, 'min_samples_split': 22, 'min_samples_leaf': 80, 'max_features': 'sqrt', 'criterion': 'log_loss', 'splitter': 'random', 'class_weight': 'balanced', 'ccp_alpha': 1.0019962534605112e-09}. Best is trial 29 with value: 0.7341444606071786.
[I 2026-08-25 14:38:30,435] Trial 41 finished with value: 0.7356536801781723 and parameters: {'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 5, 'max_features': 0.6, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 3.177674659947401e-08}. Best is trial 41 with value: 0.7356536801781723.
[I 2026-08-25 14:38:31,014] Trial 42 finished with value: 0.7060561691037414 and parameters: {'max_depth': 16, 'min_samples_split': 6, 'min_samples_leaf': 18, 'max_features': 0.6, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 9.370003360239333e-08}. Best is trial 41 with value: 0.7356536801781723.
[I 2026-08-25 14:38:31,538] Trial 43 finished with value: 0.6735659606123103 and parameters: {'max_depth': 10, 'min_samples_split': 14, 'min_samples_leaf': 5, 'max_features': 0.6, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 1.9692079611918363e-08}. Best is trial 41 with value: 0.7356536801781723.
[I 2026-08-25 14:38:32,125] Trial 44 finished with value: 0.7237825210766655 and parameters: {'max_depth': 16, 'min_samples_split': 2, 'min_samples_leaf': 10, 'max_features': 0.6, 'criterion': 'entropy', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 3.219747870791338e-09}. Best is trial 41 with value: 0.7356536801781723.
[I 2026-08-25 14:38:32,850] Trial 45 finished with value: 0.6977252555212838 and parameters: {'max_depth': 12, 'min_samples_split': 10, 'min_samples_leaf': 17, 'max_features': 0.8, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 2.585133072497304e-07}. Best is trial 41 with value: 0.7356536801781723.
[I 2026-08-25 14:38:32,951] Trial 46 finished with value: 0.577452773377167 and parameters: {'max_depth': 5, 'min_samples_split': 14, 'min_samples_leaf': 3, 'max_features': 'log2', 'criterion': 'gini', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 4.7594074874570054e-08}. Best is trial 41 with value: 0.7356536801781723.
[I 2026-08-25 14:38:33,448] Trial 47 finished with value: 0.6644280501927009 and parameters: {'max_depth': 10, 'min_samples_split': 5, 'min_samples_leaf': 29, 'max_features': 0.6, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 6.032970678148229e-09}. Best is trial 41 with value: 0.7356536801781723.
[I 2026-08-25 14:38:33,835] Trial 48 finished with value: 0.5298437294788526 and parameters: {'max_depth': 15, 'min_samples_split': 18, 'min_samples_leaf': 7, 'max_features': 0.4, 'criterion': 'entropy', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 0.009591050402013749}. Best is trial 41 with value: 0.7356536801781723.
[I 2026-08-25 14:38:34,790] Trial 49 finished with value: 0.7096622693005521 and parameters: {'max_depth': 18, 'min_samples_split': 10, 'min_samples_leaf': 24, 'max_features': None, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 1.382766429535496e-07}. Best is trial 41 with value: 0.7356536801781723.
[I 2026-08-25 14:38:35,407] Trial 50 finished with value: 0.7244245035771385 and parameters: {'max_depth': 22, 'min_samples_split': 2, 'min_samples_leaf': 11, 'max_features': 0.6, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 1.2779551391826596e-08}. Best is trial 41 with value: 0.7356536801781723.
[I 2026-08-25 14:38:36,002] Trial 51 finished with value: 0.7067477740028767 and parameters: {'max_depth': 13, 'min_samples_split': 5, 'min_samples_leaf': 7, 'max_features': 0.6, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 3.715709794146925e-08}. Best is trial 41 with value: 0.7356536801781723.
[I 2026-08-25 14:38:36,637] Trial 52 finished with value: 0.7296659876727449 and parameters: {'max_depth': 15, 'min_samples_split': 15, 'min_samples_leaf': 1, 'max_features': 0.6, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 2.380182431168731e-08}. Best is trial 41 with value: 0.7356536801781723.
[I 2026-08-25 14:38:37,273] Trial 53 finished with value: 0.7395529205246716 and parameters: {'max_depth': 15, 'min_samples_split': 16, 'min_samples_leaf': 1, 'max_features': 0.6, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 3.2992113373066466e-09}. Best is trial 53 with value: 0.7395529205246716.
[I 2026-08-25 14:38:37,909] Trial 54 finished with value: 0.7366481533306422 and parameters: {'max_depth': 17, 'min_samples_split': 25, 'min_samples_leaf': 2, 'max_features': 0.6, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 2.397445325642645e-09}. Best is trial 53 with value: 0.7395529205246716.
[I 2026-08-25 14:38:38,135] Trial 55 finished with value: 0.6992969314956814 and parameters: {'max_depth': 18, 'min_samples_split': 30, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 2.1348748909497834e-09}. Best is trial 53 with value: 0.7395529205246716.
[I 2026-08-25 14:38:38,763] Trial 56 finished with value: 0.7304946092977038 and parameters: {'max_depth': 17, 'min_samples_split': 37, 'min_samples_leaf': 1, 'max_features': 0.6, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 6.051204337360446e-09}. Best is trial 53 with value: 0.7395529205246716.
[I 2026-08-25 14:38:38,820] Trial 57 finished with value: 0.6626615513916445 and parameters: {'max_depth': 17, 'min_samples_split': 50, 'min_samples_leaf': 12, 'max_features': 0.6, 'criterion': 'log_loss', 'splitter': 'random', 'class_weight': 'balanced', 'ccp_alpha': 5.005274959853364e-09}. Best is trial 53 with value: 0.7395529205246716.
[I 2026-08-25 14:38:39,460] Trial 58 finished with value: 0.7285523113747931 and parameters: {'max_depth': 20, 'min_samples_split': 38, 'min_samples_leaf': 18, 'max_features': 0.8, 'criterion': 'gini', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 1.6083330665519311e-09}. Best is trial 53 with value: 0.7395529205246716.

  ageri: tuning Random Forest (200 trials).

[I 2026-08-25 14:40:47,168] Trial 0 finished with value: 0.8008625255661748 and parameters: {'n_estimators': 300, 'max_depth': 32, 'min_samples_split': 3, 'min_samples_leaf': 15, 'max_features': 0.7, 'bootstrap': True, 'criterion': 'log_loss', 'class_weight': None}. Best is trial 0 with value: 0.8008625255661748.
[I 2026-08-25 14:40:56,231] Trial 1 finished with value: 0.776520861580472 and parameters: {'n_estimators': 600, 'max_depth': 16, 'min_samples_split': 20, 'min_samples_leaf': 13, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'gini', 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8008625255661748.
[I 2026-08-25 14:41:25,080] Trial 2 finished with value: 0.706123554717452 and parameters: {'n_estimators': 600, 'max_depth': 8, 'min_samples_split': 28, 'min_samples_leaf': 15, 'max_features': 0.7, 'bootstrap': True, 'criterion': 'entropy', 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8008625255661748.
[I 2026-08-25 14:41:47,623] Trial 3 finished with value: 0.7859597926749906 and parameters: {'n_estimators': 800, 'max_depth': 24, 'min_samples_split': 25, 'min_samples_leaf': 20, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'log_loss', 'class_weight': None}. Best is trial 0 with value: 0.8008625255661748.
[I 2026-08-25 14:42:05,374] Trial 4 finished with value: 0.7701828569928868 and parameters: {'n_estimators': 1000, 'max_depth': 16, 'min_samples_split': 31, 'min_samples_leaf': 15, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy', 'class_weight': None}. Best is trial 0 with value: 0.8008625255661748.
[I 2026-08-25 14:42:34,910] Trial 5 finished with value: 0.8372255374890593 and parameters: {'n_estimators': 800, 'max_depth': 48, 'min_samples_split': 18, 'min_samples_leaf': 3, 'max_features': 0.3, 'bootstrap': False, 'criterion': 'gini', 'class_weight': 'balanced'}. Best is trial 5 with value: 0.8372255374890593.
[I 2026-08-25 14:42:54,900] Trial 6 finished with value: 0.8173665593592784 and parameters: {'n_estimators': 400, 'max_depth': 48, 'min_samples_split': 34, 'min_samples_leaf': 1, 'max_features': 0.5, 'bootstrap': True, 'criterion': 'entropy', 'class_weight': 'balanced'}. Best is trial 5 with value: 0.8372255374890593.
[I 2026-08-25 14:43:37,698] Trial 7 finished with value: 0.8145546300530244 and parameters: {'n_estimators': 1000, 'max_depth': 32, 'min_samples_split': 19, 'min_samples_leaf': 15, 'max_features': 0.3, 'bootstrap': False, 'criterion': 'log_loss', 'class_weight': 'balanced'}. Best is trial 5 with value: 0.8372255374890593.
[I 2026-08-25 14:45:19,429] Trial 8 finished with value: 0.7179879171704919 and parameters: {'n_estimators': 900, 'max_depth': 24, 'min_samples_split': 40, 'min_samples_leaf': 19, 'max_features': 1.0, 'bootstrap': False, 'criterion': 'gini', 'class_weight': 'balanced_subsample'}. Best is trial 5 with value: 0.8372255374890593.
[I 2026-08-25 14:45:49,255] Trial 9 finished with value: 0.8540191789680038 and parameters: {'n_estimators': 600, 'max_depth': None, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 0.3, 'bootstrap': False, 'criterion': 'log_loss', 'class_weight': 'balanced_subsample'}. Best is trial 9 with value: 0.8540191789680038.
[I 2026-08-25 14:46:05,382] Trial 10 finished with value: 0.8298317676497936 and parameters: {'n_estimators': 500, 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 7, 'max_features': 'log2', 'bootstrap': False, 'criterion': 'log_loss', 'class_weight': 'balanced_subsample'}. Best is trial 9 with value: 0.8540191789680038.
[I 2026-08-25 14:46:32,460] Trial 11 finished with value: 0.8469019839034975 and parameters: {'n_estimators': 700, 'max_depth': 48, 'min_samples_split': 12, 'min_samples_leaf': 1, 'max_features': 0.3, 'bootstrap': False, 'criterion': 'gini', 'class_weight': 'balanced_subsample'}. Best is trial 9 with value: 0.8540191789680038.
[I 2026-08-25 14:46:55,189] Trial 12 finished with value: 0.7959268239805137 and parameters: {'n_estimators': 700, 'max_depth': 12, 'min_samples_split': 11, 'min_samples_leaf': 5, 'max_features': 0.3, 'bootstrap': False, 'criterion': 'gini', 'class_weight': 'balanced_subsample'}. Best is trial 9 with value: 0.8540191789680038.
[I 2026-08-25 14:47:25,032] Trial 13 finished with value: 0.8527884187783827 and parameters: {'n_estimators': 600, 'max_depth': None, 'min_samples_split': 11, 'min_samples_leaf': 1, 'max_features': 0.3, 'bootstrap': False, 'criterion': 'log_loss', 'class_weight': 'balanced_subsample'}. Best is trial 9 with value: 0.8540191789680038.
[I 2026-08-25 14:47:48,394] Trial 14 finished with value: 0.8352340769386812 and parameters: {'n_estimators': 500, 'max_depth': None, 'min_samples_split': 9, 'min_samples_leaf': 8, 'max_features': 0.3, 'bootstrap': False, 'criterion': 'log_loss', 'class_weight': 'balanced_subsample'}. Best is trial 9 with value: 0.8540191789680038.
[I 2026-08-25 14:48:30,975] Trial 15 finished with value: 0.8575227054378278 and parameters: {'n_estimators': 500, 'max_depth': None, 'min_samples_split': 7, 'min_samples_leaf': 4, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'log_loss', 'class_weight': 'balanced_subsample'}. Best is trial 15 with value: 0.8575227054378278.
[I 2026-08-25 14:48:55,153] Trial 16 finished with value: 0.8389063311491244 and parameters: {'n_estimators': 300, 'max_depth': None, 'min_samples_split': 6, 'min_samples_leaf': 9, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'log_loss', 'class_weight': 'balanced_subsample'}. Best is trial 15 with value: 0.8575227054378278.
[I 2026-08-25 14:49:28,859] Trial 17 finished with value: 0.8505858348663808 and parameters: {'n_estimators': 400, 'max_depth': None, 'min_samples_split': 16, 'min_samples_leaf': 4, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'log_loss', 'class_weight': 'balanced_subsample'}. Best is trial 15 with value: 0.8575227054378278.
[I 2026-08-25 14:49:40,006] Trial 18 finished with value: 0.6876499007455605 and parameters: {'n_estimators': 500, 'max_depth': 8, 'min_samples_split': 7, 'min_samples_leaf': 6, 'max_features': 'log2', 'bootstrap': False, 'criterion': 'log_loss', 'class_weight': 'balanced_subsample'}. Best is trial 15 with value: 0.8575227054378278.
[I 2026-08-25 14:50:36,924] Trial 19 finished with value: 0.7070587147805157 and parameters: {'n_estimators': 400, 'max_depth': 12, 'min_samples_split': 15, 'min_samples_leaf': 10, 'max_features': 1.0, 'bootstrap': False, 'criterion': 'log_loss', 'class_weight': 'balanced_subsample'}. Best is trial 15 with value: 0.8575227054378278.
[I 2026-08-25 14:51:35,431] Trial 20 finished with value: 0.8613798685340484 and parameters: {'n_estimators': 700, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 3, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8613798685340484.
[I 2026-08-25 14:52:34,461] Trial 21 finished with value: 0.8613798685340484 and parameters: {'n_estimators': 700, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 3, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8613798685340484.
[I 2026-08-25 14:53:33,278] Trial 22 finished with value: 0.8613798685340484 and parameters: {'n_estimators': 700, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 3, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8613798685340484.
[I 2026-08-25 14:54:40,804] Trial 23 finished with value: 0.8609053404704078 and parameters: {'n_estimators': 800, 'max_depth': None, 'min_samples_split': 3, 'min_samples_leaf': 3, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8613798685340484.
[I 2026-08-25 14:55:39,855] Trial 24 finished with value: 0.8613798685340484 and parameters: {'n_estimators': 700, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 3, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8613798685340484.
[I 2026-08-25 14:56:52,987] Trial 25 finished with value: 0.8473898108722915 and parameters: {'n_estimators': 900, 'max_depth': None, 'min_samples_split': 14, 'min_samples_leaf': 6, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8613798685340484.
[I 2026-08-25 15:12:35,848] Trial 26 finished with value: 0.8374739102422133 and parameters: {'n_estimators': 700, 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 5, 'max_features': 0.5, 'bootstrap': True, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8613798685340484.
[I 2026-08-25 15:45:49,352] Trial 27 finished with value: 0.7995519651389749 and parameters: {'n_estimators': 800, 'max_depth': 12, 'min_samples_split': 7, 'min_samples_leaf': 11, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8613798685340484.
[I 2026-08-25 15:50:40,704] Trial 28 finished with value: 0.8531047486328787 and parameters: {'n_estimators': 900, 'max_depth': 16, 'min_samples_split': 5, 'min_samples_leaf': 3, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8613798685340484.
[I 2026-08-25 15:51:24,893] Trial 29 finished with value: 0.8312591760052678 and parameters: {'n_estimators': 700, 'max_depth': 32, 'min_samples_split': 4, 'min_samples_leaf': 7, 'max_features': 0.7, 'bootstrap': True, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8613798685340484.
[I 2026-08-25 15:52:09,132] Trial 30 finished with value: 0.6976307166201658 and parameters: {'n_estimators': 800, 'max_depth': 8, 'min_samples_split': 9, 'min_samples_leaf': 2, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8613798685340484.
[I 2026-08-25 15:53:05,807] Trial 31 finished with value: 0.8592598259705678 and parameters: {'n_estimators': 700, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 4, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8613798685340484.
[I 2026-08-25 15:53:55,131] Trial 32 finished with value: 0.8609809666761776 and parameters: {'n_estimators': 600, 'max_depth': None, 'min_samples_split': 8, 'min_samples_leaf': 3, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8613798685340484.
[I 2026-08-25 15:55:10,649] Trial 33 finished with value: 0.8528655303243691 and parameters: {'n_estimators': 700, 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 5, 'max_features': 0.7, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8613798685340484.
[I 2026-08-25 15:55:41,175] Trial 34 finished with value: 0.8409579466283592 and parameters: {'n_estimators': 600, 'max_depth': 32, 'min_samples_split': 13, 'min_samples_leaf': 2, 'max_features': 0.5, 'bootstrap': True, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8613798685340484.
[I 2026-08-25 15:56:06,769] Trial 35 finished with value: 0.8302462224082617 and parameters: {'n_estimators': 800, 'max_depth': 24, 'min_samples_split': 22, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8613798685340484.
[I 2026-08-25 15:56:20,283] Trial 36 finished with value: 0.8050436196437927 and parameters: {'n_estimators': 700, 'max_depth': 16, 'min_samples_split': 5, 'min_samples_leaf': 6, 'max_features': 'log2', 'bootstrap': True, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8613798685340484.
[I 2026-08-25 15:57:54,837] Trial 37 finished with value: 0.7686352171252835 and parameters: {'n_estimators': 600, 'max_depth': None, 'min_samples_split': 4, 'min_samples_leaf': 4, 'max_features': 1.0, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8613798685340484.
[I 2026-08-25 15:58:12,452] Trial 38 finished with value: 0.6893258950646601 and parameters: {'n_estimators': 800, 'max_depth': 8, 'min_samples_split': 8, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'entropy', 'class_weight': 'balanced'}. Best is trial 20 with value: 0.8613798685340484.
[I 2026-08-25 15:58:55,691] Trial 39 finished with value: 0.8278184863021233 and parameters: {'n_estimators': 900, 'max_depth': 24, 'min_samples_split': 6, 'min_samples_leaf': 7, 'max_features': 0.5, 'bootstrap': True, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8613798685340484.
[I 2026-08-25 16:00:01,997] Trial 40 finished with value: 0.8566582890608136 and parameters: {'n_estimators': 600, 'max_depth': 48, 'min_samples_split': 10, 'min_samples_leaf': 3, 'max_features': 0.7, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8613798685340484.
[I 2026-08-25 16:25:12,753] Trial 41 finished with value: 0.8609809666761776 and parameters: {'n_estimators': 600, 'max_depth': None, 'min_samples_split': 8, 'min_samples_leaf': 3, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8613798685340484.
[I 2026-08-25 16:26:10,112] Trial 42 finished with value: 0.8592598259705678 and parameters: {'n_estimators': 700, 'max_depth': None, 'min_samples_split': 4, 'min_samples_leaf': 4, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8613798685340484.
[I 2026-08-25 16:27:00,209] Trial 43 finished with value: 0.8096633006006823 and parameters: {'n_estimators': 700, 'max_depth': None, 'min_samples_split': 9, 'min_samples_leaf': 18, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8613798685340484.
[I 2026-08-25 16:27:40,775] Trial 44 finished with value: 0.8525432164275341 and parameters: {'n_estimators': 600, 'max_depth': None, 'min_samples_split': 12, 'min_samples_leaf': 1, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'gini', 'class_weight': 'balanced'}. Best is trial 20 with value: 0.8613798685340484.
[I 2026-08-25 16:28:28,805] Trial 45 finished with value: 0.8458726403097143 and parameters: {'n_estimators': 600, 'max_depth': None, 'min_samples_split': 17, 'min_samples_leaf': 5, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8613798685340484.
[I 2026-08-25 16:29:30,370] Trial 46 finished with value: 0.8204466318353884 and parameters: {'n_estimators': 800, 'max_depth': 16, 'min_samples_split': 40, 'min_samples_leaf': 2, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8613798685340484.
[I 2026-08-25 16:31:01,095] Trial 47 finished with value: 0.731180855670025 and parameters: {'n_estimators': 700, 'max_depth': None, 'min_samples_split': 37, 'min_samples_leaf': 1, 'max_features': 1.0, 'bootstrap': False, 'criterion': 'gini', 'class_weight': 'balanced'}. Best is trial 20 with value: 0.8613798685340484.
[I 2026-08-25 16:31:16,857] Trial 48 finished with value: 0.821985751585158 and parameters: {'n_estimators': 500, 'max_depth': 48, 'min_samples_split': 28, 'min_samples_leaf': 3, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8613798685340484.
[I 2026-08-25 16:31:36,189] Trial 49 finished with value: 0.8366734915344836 and parameters: {'n_estimators': 600, 'max_depth': 32, 'min_samples_split': 2, 'min_samples_leaf': 5, 'max_features': 'log2', 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8613798685340484.
[I 2026-08-25 16:32:01,712] Trial 50 finished with value: 0.8163423921884216 and parameters: {'n_estimators': 700, 'max_depth': None, 'min_samples_split': 11, 'min_samples_leaf': 8, 'max_features': 0.5, 'bootstrap': True, 'criterion': 'gini', 'class_weight': None}. Best is trial 20 with value: 0.8613798685340484.
[I 2026-08-25 16:32:51,791] Trial 51 finished with value: 0.8609809666761776 and parameters: {'n_estimators': 600, 'max_depth': None, 'min_samples_split': 8, 'min_samples_leaf': 3, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8613798685340484.
[I 2026-08-25 16:33:33,369] Trial 52 finished with value: 0.8610021702049113 and parameters: {'n_estimators': 500, 'max_depth': None, 'min_samples_split': 6, 'min_samples_leaf': 3, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8613798685340484.
[I 2026-08-25 16:34:14,451] Trial 53 finished with value: 0.8581964350289887 and parameters: {'n_estimators': 500, 'max_depth': None, 'min_samples_split': 6, 'min_samples_leaf': 4, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8613798685340484.
[I 2026-08-25 16:34:56,765] Trial 54 finished with value: 0.8649054196602123 and parameters: {'n_estimators': 500, 'max_depth': None, 'min_samples_split': 4, 'min_samples_leaf': 2, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 54 with value: 0.8649054196602123.
[I 2026-08-25 16:35:19,067] Trial 55 finished with value: 0.8187798608615766 and parameters: {'n_estimators': 300, 'max_depth': 12, 'min_samples_split': 3, 'min_samples_leaf': 2, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 54 with value: 0.8649054196602123.
[I 2026-08-25 16:35:54,171] Trial 56 finished with value: 0.8645771923902406 and parameters: {'n_estimators': 400, 'max_depth': None, 'min_samples_split': 6, 'min_samples_leaf': 1, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': 'balanced'}. Best is trial 54 with value: 0.8649054196602123.
[I 2026-08-25 16:36:29,715] Trial 57 finished with value: 0.8655121988584534 and parameters: {'n_estimators': 400, 'max_depth': None, 'min_samples_split': 4, 'min_samples_leaf': 1, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': 'balanced'}. Best is trial 57 with value: 0.8655121988584534.
[I 2026-08-25 16:36:49,861] Trial 58 finished with value: 0.8578566914964597 and parameters: {'n_estimators': 400, 'max_depth': 24, 'min_samples_split': 3, 'min_samples_leaf': 1, 'max_features': 0.3, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': 'balanced'}. Best is trial 57 with value: 0.8655121988584534.
[I 2026-08-25 16:37:17,687] Trial 59 finished with value: 0.8581365149517761 and parameters: {'n_estimators': 400, 'max_depth': None, 'min_samples_split': 4, 'min_samples_leaf': 1, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'gini', 'class_weight': 'balanced'}. Best is trial 57 with value: 0.8655121988584534.
[I 2026-08-25 16:38:25,818] Trial 60 finished with value: 0.7700072572562336 and parameters: {'n_estimators': 400, 'max_depth': None, 'min_samples_split': 7, 'min_samples_leaf': 1, 'max_features': 1.0, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': 'balanced'}. Best is trial 57 with value: 0.8655121988584534.
[I 2026-08-25 16:38:51,968] Trial 61 finished with value: 0.8617423512863276 and parameters: {'n_estimators': 300, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 2, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': 'balanced'}. Best is trial 57 with value: 0.8655121988584534.

  ageri: tuning XGBoost (200 trials).

[I 2026-08-26 07:34:37,354] Trial 0 finished with value: 0.8334865619533934 and parameters: {'max_depth': 9, 'learning_rate': 0.019677977348166304, 'subsample': 0.8978561926718072, 'colsample_bytree': 0.7442003345025142, 'min_child_weight': 2.1771032186203514, 'gamma': 1.8277151418544553, 'reg_alpha': 8.665537597324885e-06, 'reg_lambda': 1.0311514495138399}. Best is trial 0 with value: 0.8334865619533934.
[I 2026-08-26 07:34:52,138] Trial 1 finished with value: 0.8485356547395684 and parameters: {'max_depth': 7, 'learning_rate': 0.09439831569936806, 'subsample': 0.9842104900822669, 'colsample_bytree': 0.7826484435755748, 'min_child_weight': 2.880043790954131, 'gamma': 0.3403911033599112, 'reg_alpha': 1.5100408408589772e-07, 'reg_lambda': 23.538263110950048}. Best is trial 1 with value: 0.8485356547395684.
[I 2026-08-26 07:35:08,870] Trial 2 finished with value: 0.8645070684964271 and parameters: {'max_depth': 10, 'learning_rate': 0.14726161255504092, 'subsample': 0.8585642249613574, 'colsample_bytree': 0.6855299248522434, 'min_child_weight': 6.781935357780796, 'gamma': 0.41743875595471047, 'reg_alpha': 3.864031899313156e-05, 'reg_lambda': 14.610499699549097}. Best is trial 2 with value: 0.8645070684964271.
[I 2026-08-26 07:35:24,372] Trial 3 finished with value: 0.8469280286110583 and parameters: {'max_depth': 5, 'learning_rate': 0.08394754752250128, 'subsample': 0.9450697344147837, 'colsample_bytree': 0.6595392252176876, 'min_child_weight': 5.011643571251018, 'gamma': 0.4774657914394431, 'reg_alpha': 5.357340695323986e-08, 'reg_lambda': 0.18099954688158187}. Best is trial 2 with value: 0.8645070684964271.
[I 2026-08-26 07:35:38,773] Trial 4 finished with value: 0.8005710927393792 and parameters: {'max_depth': 4, 'learning_rate': 0.048769840070943336, 'subsample': 0.9178299664912868, 'colsample_bytree': 0.9963290723923126, 'min_child_weight': 13.502442798764482, 'gamma': 1.1322462171492673, 'reg_alpha': 0.00014367270092871558, 'reg_lambda': 0.1399264351773497}. Best is trial 2 with value: 0.8645070684964271.
[I 2026-08-26 07:35:55,847] Trial 5 finished with value: 0.7908267822443935 and parameters: {'max_depth': 8, 'learning_rate': 0.018099146987238985, 'subsample': 0.953044632771952, 'colsample_bytree': 0.8904231274266234, 'min_child_weight': 15.164258427643505, 'gamma': 2.130692051488852, 'reg_alpha': 0.009425386803829051, 'reg_lambda': 20.136195700340338}. Best is trial 2 with value: 0.8645070684964271.
[I 2026-08-26 07:36:26,268] Trial 6 finished with value: 0.8370642030096057 and parameters: {'max_depth': 10, 'learning_rate': 0.01918354750824495, 'subsample': 0.782598566894961, 'colsample_bytree': 0.7970893967426577, 'min_child_weight': 0.7811624819629674, 'gamma': 0.46120338258524907, 'reg_alpha': 6.963704487425356, 'reg_lambda': 0.47063847559435423}. Best is trial 2 with value: 0.8645070684964271.
[I 2026-08-26 07:36:48,452] Trial 7 finished with value: 0.8505509156083368 and parameters: {'max_depth': 10, 'learning_rate': 0.022953302153308094, 'subsample': 0.6529433178954122, 'colsample_bytree': 0.7269413610677277, 'min_child_weight': 1.7604099383967902, 'gamma': 1.266165560263202, 'reg_alpha': 2.041568273325791e-06, 'reg_lambda': 2.5538276254965817}. Best is trial 2 with value: 0.8645070684964271.
[I 2026-08-26 07:37:06,834] Trial 8 finished with value: 0.8244904502841812 and parameters: {'max_depth': 3, 'learning_rate': 0.11851328676362981, 'subsample': 0.7074625481911713, 'colsample_bytree': 0.9645659651689448, 'min_child_weight': 20.063522776432464, 'gamma': 0.047573401053791486, 'reg_alpha': 0.34420918881100815, 'reg_lambda': 4.715832950352583}. Best is trial 2 with value: 0.8645070684964271.
[I 2026-08-26 07:37:20,641] Trial 9 finished with value: 0.7268129801587169 and parameters: {'max_depth': 3, 'learning_rate': 0.033391708755025735, 'subsample': 0.8256997968048689, 'colsample_bytree': 0.837631051781117, 'min_child_weight': 8.12005959578132, 'gamma': 1.8972954750065205, 'reg_alpha': 2.437950567013768, 'reg_lambda': 6.697837558293906}. Best is trial 2 with value: 0.8645070684964271.
[I 2026-08-26 07:37:30,165] Trial 10 finished with value: 0.7861789683356235 and parameters: {'max_depth': 6, 'learning_rate': 0.17115128841996644, 'subsample': 0.8154186866999962, 'colsample_bytree': 0.6025554256995838, 'min_child_weight': 0.8625345056254972, 'gamma': 2.9869578392012968, 'reg_alpha': 1.239446148413562e-09, 'reg_lambda': 0.9684799729031198}. Best is trial 2 with value: 0.8645070684964271.
[I 2026-08-26 07:37:49,347] Trial 11 finished with value: 0.8541359101324157 and parameters: {'max_depth': 10, 'learning_rate': 0.04809950013571818, 'subsample': 0.6132599083973347, 'colsample_bytree': 0.7068708218135153, 'min_child_weight': 2.000151976177787, 'gamma': 1.1015819037394388, 'reg_alpha': 4.514632609962317e-05, 'reg_lambda': 5.019540607508096}. Best is trial 2 with value: 0.8645070684964271.
[I 2026-08-26 07:38:08,222] Trial 12 finished with value: 0.8518635074314872 and parameters: {'max_depth': 9, 'learning_rate': 0.05449774578204275, 'subsample': 0.6446773085991204, 'colsample_bytree': 0.6782743329282878, 'min_child_weight': 5.024974615071706, 'gamma': 1.0252076108694772, 'reg_alpha': 0.0009910433108845519, 'reg_lambda': 8.210034909208419}. Best is trial 2 with value: 0.8645070684964271.
[I 2026-08-26 07:38:23,415] Trial 13 finished with value: 0.8587266467520767 and parameters: {'max_depth': 10, 'learning_rate': 0.19639010434181664, 'subsample': 0.6021768360536973, 'colsample_bytree': 0.6725320077667093, 'min_child_weight': 1.334503164197373, 'gamma': 0.7848649789462945, 'reg_alpha': 6.501336646332095e-05, 'reg_lambda': 11.389015447500912}. Best is trial 2 with value: 0.8645070684964271.
[I 2026-08-26 07:38:37,515] Trial 14 finished with value: 0.8538064631493876 and parameters: {'max_depth': 8, 'learning_rate': 0.1748224970113755, 'subsample': 0.7251257998024343, 'colsample_bytree': 0.6067985020666221, 'min_child_weight': 0.5629506277333849, 'gamma': 0.7357192839349284, 'reg_alpha': 0.007366281502087388, 'reg_lambda': 15.167077457961938}. Best is trial 2 with value: 0.8645070684964271.
[I 2026-08-26 07:39:03,788] Trial 15 finished with value: 0.8606361638232689 and parameters: {'max_depth': 9, 'learning_rate': 0.19817774165410926, 'subsample': 0.8690856269930812, 'colsample_bytree': 0.6536074054839038, 'min_child_weight': 27.489547649192218, 'gamma': 0.014190871821646578, 'reg_alpha': 7.749040818304145e-07, 'reg_lambda': 11.633131249215683}. Best is trial 2 with value: 0.8645070684964271.
[I 2026-08-26 07:39:37,671] Trial 16 finished with value: 0.8566139131923103 and parameters: {'max_depth': 8, 'learning_rate': 0.13177796734730307, 'subsample': 0.8586927017191538, 'colsample_bytree': 0.6390519450381702, 'min_child_weight': 29.266819628702436, 'gamma': 0.020524823242183767, 'reg_alpha': 2.2588770720502548e-07, 'reg_lambda': 3.0830473334047306}. Best is trial 2 with value: 0.8645070684964271.
[I 2026-08-26 07:39:55,115] Trial 17 finished with value: 0.8718621334256502 and parameters: {'max_depth': 9, 'learning_rate': 0.11559880571167458, 'subsample': 0.8864095686072445, 'colsample_bytree': 0.7462766269481121, 'min_child_weight': 8.540761076488415, 'gamma': 0.262938132752185, 'reg_alpha': 2.172213690433863e-09, 'reg_lambda': 2.083558458304227}. Best is trial 17 with value: 0.8718621334256502.
[I 2026-08-26 07:40:07,913] Trial 18 finished with value: 0.8309799295711991 and parameters: {'max_depth': 6, 'learning_rate': 0.0782463128351522, 'subsample': 0.7667214138864583, 'colsample_bytree': 0.7685876627442525, 'min_child_weight': 7.513754202666461, 'gamma': 1.4557408989094207, 'reg_alpha': 3.0898501493733272e-09, 'reg_lambda': 1.1357101578547972}. Best is trial 17 with value: 0.8718621334256502.
[I 2026-08-26 07:40:16,537] Trial 19 finished with value: 0.8305523056994069 and parameters: {'max_depth': 7, 'learning_rate': 0.13279314941400044, 'subsample': 0.9967124142755496, 'colsample_bytree': 0.8425310595120723, 'min_child_weight': 4.053989981004542, 'gamma': 0.7312884368852899, 'reg_alpha': 1.3760240810671025e-08, 'reg_lambda': 0.35425072033627353}. Best is trial 17 with value: 0.8718621334256502.
[I 2026-08-26 07:40:38,371] Trial 20 finished with value: 0.8720574749753688 and parameters: {'max_depth': 9, 'learning_rate': 0.06418949709826452, 'subsample': 0.8681238025780942, 'colsample_bytree': 0.705568621452069, 'min_child_weight': 9.115994902439157, 'gamma': 0.31089772099195145, 'reg_alpha': 0.09095647740042732, 'reg_lambda': 2.2641434467107167}. Best is trial 20 with value: 0.8720574749753688.
[I 2026-08-26 07:40:57,225] Trial 21 finished with value: 0.8684951265010504 and parameters: {'max_depth': 9, 'learning_rate': 0.06857798114488887, 'subsample': 0.8782041330301507, 'colsample_bytree': 0.7156866437123837, 'min_child_weight': 8.748670161501403, 'gamma': 0.34181595694196115, 'reg_alpha': 0.48317265512657953, 'reg_lambda': 1.9422836377699944}. Best is trial 20 with value: 0.8720574749753688.
[I 2026-08-26 07:41:17,075] Trial 22 finished with value: 0.8656443026167835 and parameters: {'max_depth': 9, 'learning_rate': 0.06651217468208913, 'subsample': 0.900149073766403, 'colsample_bytree': 0.739912759336613, 'min_child_weight': 11.554094959194167, 'gamma': 0.34106308655449113, 'reg_alpha': 0.15851927368239083, 'reg_lambda': 1.9222542302610328}. Best is trial 20 with value: 0.8720574749753688.
[I 2026-08-26 07:41:38,804] Trial 23 finished with value: 0.8711008901547161 and parameters: {'max_depth': 8, 'learning_rate': 0.10357567616016997, 'subsample': 0.8224550556193101, 'colsample_bytree': 0.8161400869086647, 'min_child_weight': 9.825653021639553, 'gamma': 0.2298959367723586, 'reg_alpha': 0.03367336652018941, 'reg_lambda': 1.616281742805327}. Best is trial 20 with value: 0.8720574749753688.
[I 2026-08-26 07:41:54,087] Trial 24 finished with value: 0.8596308365787795 and parameters: {'max_depth': 7, 'learning_rate': 0.10408414139034529, 'subsample': 0.8172555698933346, 'colsample_bytree': 0.8500368212761793, 'min_child_weight': 11.4194089410537, 'gamma': 0.6478612884614297, 'reg_alpha': 0.011601566918598627, 'reg_lambda': 0.6463820045841848}. Best is trial 20 with value: 0.8720574749753688.
[I 2026-08-26 07:42:34,233] Trial 25 finished with value: 0.8648891705762743 and parameters: {'max_depth': 8, 'learning_rate': 0.03376207213703955, 'subsample': 0.7615666242320015, 'colsample_bytree': 0.8156322899320291, 'min_child_weight': 16.79796399788668, 'gamma': 0.19348598583840332, 'reg_alpha': 0.0544165872863283, 'reg_lambda': 1.386114759754914}. Best is trial 20 with value: 0.8720574749753688.
[I 2026-08-26 07:42:46,671] Trial 26 finished with value: 0.8526283813466702 and parameters: {'max_depth': 8, 'learning_rate': 0.10264804653521425, 'subsample': 0.8380099865899632, 'colsample_bytree': 0.8981480418851177, 'min_child_weight': 3.707821157244363, 'gamma': 0.949955346389509, 'reg_alpha': 0.0003824362507556758, 'reg_lambda': 3.271475386017675}. Best is trial 20 with value: 0.8720574749753688.
[I 2026-08-26 07:43:09,235] Trial 27 finished with value: 0.8630981693644848 and parameters: {'max_depth': 7, 'learning_rate': 0.039562476336283556, 'subsample': 0.7895756603797992, 'colsample_bytree': 0.7600053655625387, 'min_child_weight': 5.984494598696171, 'gamma': 0.5912999703320375, 'reg_alpha': 0.0011105988818385128, 'reg_lambda': 0.6872518464735312}. Best is trial 20 with value: 0.8720574749753688.
[I 2026-08-26 07:43:35,056] Trial 28 finished with value: 0.8752815988758714 and parameters: {'max_depth': 9, 'learning_rate': 0.06440850471552748, 'subsample': 0.92788520711102, 'colsample_bytree': 0.9035571214411334, 'min_child_weight': 9.356929348314193, 'gamma': 0.16307760375610608, 'reg_alpha': 0.03078720565945149, 'reg_lambda': 1.7914082629340526}. Best is trial 28 with value: 0.8752815988758714.
[I 2026-08-26 07:43:44,815] Trial 29 finished with value: 0.8035560249510383 and parameters: {'max_depth': 9, 'learning_rate': 0.061023688279080314, 'subsample': 0.9254644610649688, 'colsample_bytree': 0.9128853280361336, 'min_child_weight': 3.344776627281478, 'gamma': 2.7071649520000003, 'reg_alpha': 1.7380401483784091, 'reg_lambda': 3.8958771346876926}. Best is trial 28 with value: 0.8752815988758714.
[I 2026-08-26 07:44:00,079] Trial 30 finished with value: 0.8141532982673443 and parameters: {'max_depth': 9, 'learning_rate': 0.026479783815403904, 'subsample': 0.9605580282721359, 'colsample_bytree': 0.9285017176829372, 'min_child_weight': 23.276679695381006, 'gamma': 1.5543130931395168, 'reg_alpha': 2.9945472770271383e-06, 'reg_lambda': 0.31148575461658956}. Best is trial 28 with value: 0.8752815988758714.
[I 2026-08-26 07:44:22,621] Trial 31 finished with value: 0.8735375888202597 and parameters: {'max_depth': 8, 'learning_rate': 0.08161788421318071, 'subsample': 0.8951891309570741, 'colsample_bytree': 0.8607362441611519, 'min_child_weight': 9.267319598032001, 'gamma': 0.20573188370086826, 'reg_alpha': 0.041557470786751566, 'reg_lambda': 1.698257267435732}. Best is trial 28 with value: 0.8752815988758714.
[I 2026-08-26 07:44:45,605] Trial 32 finished with value: 0.8733887898882923 and parameters: {'max_depth': 9, 'learning_rate': 0.08107841730643402, 'subsample': 0.8935902985405406, 'colsample_bytree': 0.8649858360907002, 'min_child_weight': 10.543839412364575, 'gamma': 0.21161042326574936, 'reg_alpha': 0.07203443331220827, 'reg_lambda': 2.2345114517539475}. Best is trial 28 with value: 0.8752815988758714.
[I 2026-08-26 07:45:08,634] Trial 33 finished with value: 0.8757768085858206 and parameters: {'max_depth': 7, 'learning_rate': 0.08262476443748482, 'subsample': 0.9153641141231644, 'colsample_bytree': 0.8678096322275495, 'min_child_weight': 5.555130846885489, 'gamma': 0.1354139053279499, 'reg_alpha': 0.06677327738295193, 'reg_lambda': 0.9613314051013694}. Best is trial 33 with value: 0.8757768085858206.
[I 2026-08-26 07:45:33,496] Trial 34 finished with value: 0.8733642745647927 and parameters: {'max_depth': 6, 'learning_rate': 0.0795406185222286, 'subsample': 0.915308671149777, 'colsample_bytree': 0.8726832495118195, 'min_child_weight': 5.95658299669982, 'gamma': 0.13460554274263098, 'reg_alpha': 0.0024182464690984846, 'reg_lambda': 0.9230393508593662}. Best is trial 33 with value: 0.8757768085858206.
[I 2026-08-26 07:45:45,923] Trial 35 finished with value: 0.8504124032670528 and parameters: {'max_depth': 7, 'learning_rate': 0.09176938854353371, 'subsample': 0.9701838936753047, 'colsample_bytree': 0.9472088759651119, 'min_child_weight': 2.7001501188576817, 'gamma': 0.5020264551833661, 'reg_alpha': 0.5153238348096396, 'reg_lambda': 1.3223699607901696}. Best is trial 33 with value: 0.8757768085858206.
[I 2026-08-26 07:46:00,535] Trial 36 finished with value: 0.8573824237820347 and parameters: {'max_depth': 7, 'learning_rate': 0.07465416624409016, 'subsample': 0.9230228404748064, 'colsample_bytree': 0.8772721096054387, 'min_child_weight': 5.0450944168037735, 'gamma': 0.5341714359838272, 'reg_alpha': 0.025175687544935852, 'reg_lambda': 0.7524404036279078}. Best is trial 33 with value: 0.8757768085858206.
[I 2026-08-26 07:46:13,060] Trial 37 finished with value: 0.8212183005545167 and parameters: {'max_depth': 5, 'learning_rate': 0.08803830494827714, 'subsample': 0.9426007230425298, 'colsample_bytree': 0.8629832221495394, 'min_child_weight': 17.46855746709023, 'gamma': 0.860101181247109, 'reg_alpha': 0.00578537773496677, 'reg_lambda': 0.4999617471476896}. Best is trial 33 with value: 0.8757768085858206.
[I 2026-08-26 07:46:34,956] Trial 38 finished with value: 0.8508632384968683 and parameters: {'max_depth': 8, 'learning_rate': 0.05448478893725932, 'subsample': 0.8994396817685834, 'colsample_bytree': 0.9833270262238019, 'min_child_weight': 11.900396184295703, 'gamma': 0.15475945404983635, 'reg_alpha': 7.175533503904134, 'reg_lambda': 2.8368832264251727}. Best is trial 33 with value: 0.8757768085858206.
[I 2026-08-26 07:46:55,341] Trial 39 finished with value: 0.8507070453468166 and parameters: {'max_depth': 6, 'learning_rate': 0.04263262452513591, 'subsample': 0.9413015819672643, 'colsample_bytree': 0.925944692531739, 'min_child_weight': 13.756160942199806, 'gamma': 0.44282033026243417, 'reg_alpha': 0.1822026922842364, 'reg_lambda': 0.21731344762088392}. Best is trial 33 with value: 0.8757768085858206.
[I 2026-08-26 07:47:32,886] Trial 40 finished with value: 0.8815867605293084 and parameters: {'max_depth': 10, 'learning_rate': 0.07378589173242686, 'subsample': 0.8458010103538273, 'colsample_bytree': 0.8961330371326033, 'min_child_weight': 6.4639115653861765, 'gamma': 0.0032221940011098182, 'reg_alpha': 1.4157976467202182, 'reg_lambda': 1.4834010278888219}. Best is trial 40 with value: 0.8815867605293084.
[I 2026-08-26 07:48:01,472] Trial 41 finished with value: 0.8790547556727348 and parameters: {'max_depth': 10, 'learning_rate': 0.057083243204470314, 'subsample': 0.844806969617997, 'colsample_bytree': 0.8945421416737447, 'min_child_weight': 6.703290207457388, 'gamma': 0.14147492031222844, 'reg_alpha': 0.7769982680682604, 'reg_lambda': 1.533456252504461}. Best is trial 40 with value: 0.8815867605293084.
[I 2026-08-26 07:48:46,801] Trial 42 finished with value: 0.878805897059012 and parameters: {'max_depth': 10, 'learning_rate': 0.05904491904649769, 'subsample': 0.847941023635729, 'colsample_bytree': 0.895242766628248, 'min_child_weight': 6.657786327432544, 'gamma': 0.014642111988752537, 'reg_alpha': 2.0262932994703147, 'reg_lambda': 1.5667825432967126}. Best is trial 40 with value: 0.8815867605293084.
[I 2026-08-26 07:49:33,525] Trial 43 finished with value: 0.8801629987883015 and parameters: {'max_depth': 10, 'learning_rate': 0.05434031817555566, 'subsample': 0.8471586272101693, 'colsample_bytree': 0.8954858131560908, 'min_child_weight': 6.710366524061663, 'gamma': 0.0025880291104427022, 'reg_alpha': 1.380775701977322, 'reg_lambda': 0.9266289198437023}. Best is trial 40 with value: 0.8815867605293084.
[I 2026-08-26 07:50:13,477] Trial 44 finished with value: 0.8800013610821132 and parameters: {'max_depth': 10, 'learning_rate': 0.05274613636703598, 'subsample': 0.8418093179455708, 'colsample_bytree': 0.9497769502340743, 'min_child_weight': 6.5095177945759035, 'gamma': 0.04482755733949522, 'reg_alpha': 1.575569749805781, 'reg_lambda': 0.9080384590455394}. Best is trial 40 with value: 0.8815867605293084.
[I 2026-08-26 07:51:03,111] Trial 45 finished with value: 0.8812740140330166 and parameters: {'max_depth': 10, 'learning_rate': 0.05033678413781417, 'subsample': 0.8458163190533885, 'colsample_bytree': 0.9441120109189772, 'min_child_weight': 4.233233536147139, 'gamma': 0.0074592591523478516, 'reg_alpha': 1.9610126761595412, 'reg_lambda': 0.5425727476426472}. Best is trial 40 with value: 0.8815867605293084.
[I 2026-08-26 07:51:23,606] Trial 46 finished with value: 0.8714092990254556 and parameters: {'max_depth': 10, 'learning_rate': 0.047087145922240975, 'subsample': 0.7934033454860998, 'colsample_bytree': 0.954509656919842, 'min_child_weight': 2.5413649839019357, 'gamma': 0.4317737966906523, 'reg_alpha': 1.1406045065227637, 'reg_lambda': 0.48528787834264403}. Best is trial 40 with value: 0.8815867605293084.
[I 2026-08-26 07:51:48,489] Trial 47 finished with value: 0.8593892070421907 and parameters: {'max_depth': 10, 'learning_rate': 0.03791030065784251, 'subsample': 0.8041657085262596, 'colsample_bytree': 0.9770831193715886, 'min_child_weight': 4.205780193306147, 'gamma': 0.3462277821699764, 'reg_alpha': 4.189703401705504, 'reg_lambda': 0.10527598360394627}. Best is trial 40 with value: 0.8815867605293084.
[I 2026-08-26 07:52:29,561] Trial 48 finished with value: 0.8811290230617717 and parameters: {'max_depth': 10, 'learning_rate': 0.05224114181872859, 'subsample': 0.8402990050777452, 'colsample_bytree': 0.9996321792689185, 'min_child_weight': 7.041358613137505, 'gamma': 0.02502363323887207, 'reg_alpha': 0.9496980094440347, 'reg_lambda': 0.2681473251943912}. Best is trial 40 with value: 0.8815867605293084.

[2/6] Creating 80/20 split with 'bianco' completely held out.

[I 2026-08-26 09:09:02,777] A new study created in memory with name: DecisionTree_LOSO

[2/6] Running one 5-fold search per model.
  bianco: tuning Decision Tree (200 trials).

[I 2026-08-26 09:09:03,400] Trial 0 finished with value: 0.6484595690895779 and parameters: {'max_depth': 12, 'min_samples_split': 96, 'min_samples_leaf': 59, 'max_features': 0.6, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 1.3480180290890803e-07}. Best is trial 0 with value: 0.6484595690895779.
[I 2026-08-26 09:09:03,463] Trial 1 finished with value: 0.5728767981661977 and parameters: {'max_depth': 17, 'min_samples_split': 44, 'min_samples_leaf': 24, 'max_features': 0.8, 'criterion': 'log_loss', 'splitter': 'random', 'class_weight': None, 'ccp_alpha': 0.0043873144324354085}. Best is trial 0 with value: 0.6484595690895779.
[I 2026-08-26 09:09:03,491] Trial 2 finished with value: 0.5232912191780829 and parameters: {'max_depth': 30, 'min_samples_split': 82, 'min_samples_leaf': 25, 'max_features': 'sqrt', 'criterion': 'gini', 'splitter': 'random', 'class_weight': None, 'ccp_alpha': 0.006124806805925988}. Best is trial 0 with value: 0.6484595690895779.
[I 2026-08-26 09:09:03,687] Trial 3 finished with value: 0.6288410642476873 and parameters: {'max_depth': 24, 'min_samples_split': 95, 'min_samples_leaf': 72, 'max_features': 'sqrt', 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 0.00041245717727594227}. Best is trial 0 with value: 0.6484595690895779.
[I 2026-08-26 09:09:03,791] Trial 4 finished with value: 0.5777600478659004 and parameters: {'max_depth': 4, 'min_samples_split': 99, 'min_samples_leaf': 62, 'max_features': 'log2', 'criterion': 'entropy', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 1.5027137214154575e-07}. Best is trial 0 with value: 0.6484595690895779.
[I 2026-08-26 09:09:04,660] Trial 5 finished with value: 0.6524853033741743 and parameters: {'max_depth': 11, 'min_samples_split': 74, 'min_samples_leaf': 52, 'max_features': None, 'criterion': 'gini', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 2.8501838758433707e-05}. Best is trial 5 with value: 0.6524853033741743.
[I 2026-08-26 09:09:04,682] Trial 6 finished with value: 0.5657838284194101 and parameters: {'max_depth': 11, 'min_samples_split': 52, 'min_samples_leaf': 73, 'max_features': 'log2', 'criterion': 'entropy', 'splitter': 'random', 'class_weight': None, 'ccp_alpha': 0.0017697543538533224}. Best is trial 5 with value: 0.6524853033741743.
[I 2026-08-26 09:09:05,468] Trial 7 finished with value: 0.6659777344526601 and parameters: {'max_depth': 17, 'min_samples_split': 81, 'min_samples_leaf': 72, 'max_features': 0.8, 'criterion': 'entropy', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 1.8298712093870903e-07}. Best is trial 7 with value: 0.6659777344526601.
[I 2026-08-26 09:09:05,539] Trial 8 finished with value: 0.6465261521897578 and parameters: {'max_depth': 17, 'min_samples_split': 71, 'min_samples_leaf': 30, 'max_features': None, 'criterion': 'entropy', 'splitter': 'random', 'class_weight': None, 'ccp_alpha': 1.0333896431462928e-08}. Best is trial 7 with value: 0.6659777344526601.
[I 2026-08-26 09:09:05,734] Trial 9 finished with value: 0.65805039128255 and parameters: {'max_depth': 16, 'min_samples_split': 99, 'min_samples_leaf': 20, 'max_features': 'sqrt', 'criterion': 'gini', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 1.3685182782317289e-05}. Best is trial 7 with value: 0.6659777344526601.
[I 2026-08-26 09:09:05,892] Trial 10 finished with value: 0.5803803580636768 and parameters: {'max_depth': 3, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 0.4, 'criterion': 'entropy', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 1.3381271619726983e-09}. Best is trial 7 with value: 0.6659777344526601.
[I 2026-08-26 09:09:06,672] Trial 11 finished with value: 0.6832095339431299 and parameters: {'max_depth': 20, 'min_samples_split': 56, 'min_samples_leaf': 42, 'max_features': 0.8, 'criterion': 'gini', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 6.204616091188485e-06}. Best is trial 11 with value: 0.6832095339431299.
[I 2026-08-26 09:09:07,449] Trial 12 finished with value: 0.6843764293593971 and parameters: {'max_depth': 23, 'min_samples_split': 52, 'min_samples_leaf': 43, 'max_features': 0.8, 'criterion': 'gini', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 1.6480900083100138e-06}. Best is trial 12 with value: 0.6843764293593971.
[I 2026-08-26 09:09:08,229] Trial 13 finished with value: 0.6832095339431299 and parameters: {'max_depth': 24, 'min_samples_split': 42, 'min_samples_leaf': 42, 'max_features': 0.8, 'criterion': 'gini', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 5.28883883276434e-06}. Best is trial 12 with value: 0.6843764293593971.
[I 2026-08-26 09:09:09,026] Trial 14 finished with value: 0.6866201747549459 and parameters: {'max_depth': 23, 'min_samples_split': 25, 'min_samples_leaf': 40, 'max_features': 0.8, 'criterion': 'gini', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 1.0100260719750913e-06}. Best is trial 14 with value: 0.6866201747549459.
[I 2026-08-26 09:09:09,824] Trial 15 finished with value: 0.6885147137357623 and parameters: {'max_depth': 30, 'min_samples_split': 18, 'min_samples_leaf': 39, 'max_features': 0.8, 'criterion': 'gini', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 9.990316153594146e-07}. Best is trial 15 with value: 0.6885147137357623.
[I 2026-08-26 09:09:10,252] Trial 16 finished with value: 0.7220862298428548 and parameters: {'max_depth': 29, 'min_samples_split': 17, 'min_samples_leaf': 13, 'max_features': 0.4, 'criterion': 'gini', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 0.00012723130809787154}. Best is trial 16 with value: 0.7220862298428548.
[I 2026-08-26 09:09:10,709] Trial 17 finished with value: 0.7287723459201588 and parameters: {'max_depth': 30, 'min_samples_split': 12, 'min_samples_leaf': 9, 'max_features': 0.4, 'criterion': 'gini', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 0.00012844828975803788}. Best is trial 17 with value: 0.7287723459201588.
[I 2026-08-26 09:09:10,780] Trial 18 finished with value: 0.6739219257900311 and parameters: {'max_depth': 27, 'min_samples_split': 4, 'min_samples_leaf': 6, 'max_features': 0.4, 'criterion': 'gini', 'splitter': 'random', 'class_weight': 'balanced', 'ccp_alpha': 0.00014804374425740586}. Best is trial 17 with value: 0.7287723459201588.
[I 2026-08-26 09:09:11,200] Trial 19 finished with value: 0.7071381469777873 and parameters: {'max_depth': 27, 'min_samples_split': 20, 'min_samples_leaf': 15, 'max_features': 0.4, 'criterion': 'gini', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 0.00031715366845905274}. Best is trial 17 with value: 0.7287723459201588.
[I 2026-08-26 09:09:11,685] Trial 20 finished with value: 0.7262935786566282 and parameters: {'max_depth': 27, 'min_samples_split': 29, 'min_samples_leaf': 11, 'max_features': 0.4, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 9.087915314514519e-05}. Best is trial 17 with value: 0.7287723459201588.
[I 2026-08-26 09:09:12,161] Trial 21 finished with value: 0.7219386623364511 and parameters: {'max_depth': 27, 'min_samples_split': 30, 'min_samples_leaf': 15, 'max_features': 0.4, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 9.218063385038199e-05}. Best is trial 17 with value: 0.7287723459201588.
[I 2026-08-26 09:09:12,669] Trial 22 finished with value: 0.6906831853716306 and parameters: {'max_depth': 30, 'min_samples_split': 13, 'min_samples_leaf': 10, 'max_features': 0.4, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 0.00107633044458318}. Best is trial 17 with value: 0.7287723459201588.
[I 2026-08-26 09:09:13,182] Trial 23 finished with value: 0.7291484059453053 and parameters: {'max_depth': 27, 'min_samples_split': 28, 'min_samples_leaf': 2, 'max_features': 0.4, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 5.385927285780402e-05}. Best is trial 23 with value: 0.7291484059453053.
[I 2026-08-26 09:09:13,693] Trial 24 finished with value: 0.7200336232209688 and parameters: {'max_depth': 26, 'min_samples_split': 33, 'min_samples_leaf': 2, 'max_features': 0.4, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 4.748835604962492e-05}. Best is trial 23 with value: 0.7291484059453053.
[I 2026-08-26 09:09:14,519] Trial 25 finished with value: 0.7367664571277104 and parameters: {'max_depth': 21, 'min_samples_split': 11, 'min_samples_leaf': 8, 'max_features': 0.6, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 0.0007542583338761624}. Best is trial 25 with value: 0.7367664571277104.
[I 2026-08-26 09:09:14,612] Trial 26 finished with value: 0.6330371847203347 and parameters: {'max_depth': 20, 'min_samples_split': 9, 'min_samples_leaf': 6, 'max_features': 0.6, 'criterion': 'log_loss', 'splitter': 'random', 'class_weight': 'balanced', 'ccp_alpha': 0.0008225783883693396}. Best is trial 25 with value: 0.7367664571277104.
[I 2026-08-26 09:09:15,369] Trial 27 finished with value: 0.6230652865519022 and parameters: {'max_depth': 21, 'min_samples_split': 39, 'min_samples_leaf': 20, 'max_features': 0.6, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 0.0023692647849267055}. Best is trial 25 with value: 0.7367664571277104.
[I 2026-08-26 09:09:16,076] Trial 28 finished with value: 0.6915833625535918 and parameters: {'max_depth': 25, 'min_samples_split': 10, 'min_samples_leaf': 32, 'max_features': 0.6, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 0.0003479155745647618}. Best is trial 25 with value: 0.7367664571277104.
[I 2026-08-26 09:09:16,632] Trial 29 finished with value: 0.630821550130197 and parameters: {'max_depth': 8, 'min_samples_split': 23, 'min_samples_leaf': 6, 'max_features': 0.6, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 1.41195396903175e-05}. Best is trial 25 with value: 0.7367664571277104.
[I 2026-08-26 09:09:17,348] Trial 30 finished with value: 0.7135111815768239 and parameters: {'max_depth': 14, 'min_samples_split': 13, 'min_samples_leaf': 19, 'max_features': 0.6, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 2.9878418291649217e-05}. Best is trial 25 with value: 0.7367664571277104.
[I 2026-08-26 09:09:17,837] Trial 31 finished with value: 0.7189755215943019 and parameters: {'max_depth': 28, 'min_samples_split': 31, 'min_samples_leaf': 10, 'max_features': 0.4, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 9.885501106434482e-05}. Best is trial 25 with value: 0.7367664571277104.
[I 2026-08-26 09:09:18,365] Trial 32 finished with value: 0.5759258066488429 and parameters: {'max_depth': 22, 'min_samples_split': 26, 'min_samples_leaf': 1, 'max_features': 0.4, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 0.007540049426671667}. Best is trial 25 with value: 0.7367664571277104.
[I 2026-08-26 09:09:18,855] Trial 33 finished with value: 0.7139501676274116 and parameters: {'max_depth': 19, 'min_samples_split': 35, 'min_samples_leaf': 10, 'max_features': 0.4, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 0.0005254240907517697}. Best is trial 25 with value: 0.7367664571277104.
[I 2026-08-26 09:09:18,888] Trial 34 finished with value: 0.6013380931445002 and parameters: {'max_depth': 25, 'min_samples_split': 9, 'min_samples_leaf': 27, 'max_features': 'log2', 'criterion': 'log_loss', 'splitter': 'random', 'class_weight': 'balanced', 'ccp_alpha': 0.00025747092300624304}. Best is trial 25 with value: 0.7367664571277104.
[I 2026-08-26 09:09:20,138] Trial 35 finished with value: 0.617483673902032 and parameters: {'max_depth': 28, 'min_samples_split': 26, 'min_samples_leaf': 17, 'max_features': None, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 0.0029672044598356424}. Best is trial 25 with value: 0.7367664571277104.
[I 2026-08-26 09:09:20,381] Trial 36 finished with value: 0.6826774729892319 and parameters: {'max_depth': 29, 'min_samples_split': 46, 'min_samples_leaf': 23, 'max_features': 'sqrt', 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 5.182714180824652e-05}. Best is trial 25 with value: 0.7367664571277104.
[I 2026-08-26 09:09:20,436] Trial 37 finished with value: 0.6821262242187143 and parameters: {'max_depth': 25, 'min_samples_split': 16, 'min_samples_leaf': 6, 'max_features': 0.4, 'criterion': 'log_loss', 'splitter': 'random', 'class_weight': None, 'ccp_alpha': 1.154913535075394e-05}. Best is trial 25 with value: 0.7367664571277104.
[I 2026-08-26 09:09:21,211] Trial 38 finished with value: 0.6994129892129957 and parameters: {'max_depth': 22, 'min_samples_split': 38, 'min_samples_leaf': 12, 'max_features': 0.6, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 0.001169378673261696}. Best is trial 25 with value: 0.7367664571277104.
[I 2026-08-26 09:09:21,444] Trial 39 finished with value: 0.5707809236889514 and parameters: {'max_depth': 26, 'min_samples_split': 6, 'min_samples_leaf': 24, 'max_features': 'log2', 'criterion': 'entropy', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 0.009844132860034955}. Best is trial 25 with value: 0.7367664571277104.
[I 2026-08-26 09:09:21,508] Trial 40 finished with value: 0.6111299968174568 and parameters: {'max_depth': 30, 'min_samples_split': 23, 'min_samples_leaf': 80, 'max_features': None, 'criterion': 'log_loss', 'splitter': 'random', 'class_weight': 'balanced', 'ccp_alpha': 4.445964914284398e-06}. Best is trial 25 with value: 0.7367664571277104.
[I 2026-08-26 09:09:21,937] Trial 41 finished with value: 0.7212590057640293 and parameters: {'max_depth': 28, 'min_samples_split': 18, 'min_samples_leaf': 13, 'max_features': 0.4, 'criterion': 'gini', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 0.00020611290762821496}. Best is trial 25 with value: 0.7367664571277104.
[I 2026-08-26 09:09:22,403] Trial 42 finished with value: 0.7412461756664985 and parameters: {'max_depth': 29, 'min_samples_split': 15, 'min_samples_leaf': 4, 'max_features': 0.4, 'criterion': 'gini', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 6.295588415362433e-05}. Best is trial 42 with value: 0.7412461756664985.
[I 2026-08-26 09:09:22,872] Trial 43 finished with value: 0.7425230072566213 and parameters: {'max_depth': 29, 'min_samples_split': 12, 'min_samples_leaf': 4, 'max_features': 0.4, 'criterion': 'gini', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 5.0394627238854605e-05}. Best is trial 43 with value: 0.7425230072566213.
[I 2026-08-26 09:09:23,314] Trial 44 finished with value: 0.7446598633568116 and parameters: {'max_depth': 30, 'min_samples_split': 2, 'min_samples_leaf': 4, 'max_features': 0.4, 'criterion': 'gini', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 4.524984763101731e-05}. Best is trial 44 with value: 0.7446598633568116.
[I 2026-08-26 09:09:23,554] Trial 45 finished with value: 0.7199983500744389 and parameters: {'max_depth': 29, 'min_samples_split': 6, 'min_samples_leaf': 4, 'max_features': 'sqrt', 'criterion': 'gini', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 2.426989682799004e-05}. Best is trial 44 with value: 0.7446598633568116.
[I 2026-08-26 09:09:23,991] Trial 46 finished with value: 0.7413818228554929 and parameters: {'max_depth': 24, 'min_samples_split': 7, 'min_samples_leaf': 4, 'max_features': 0.4, 'criterion': 'gini', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 2.29882109973704e-06}. Best is trial 44 with value: 0.7446598633568116.
[I 2026-08-26 09:09:24,420] Trial 47 finished with value: 0.7418259123270377 and parameters: {'max_depth': 24, 'min_samples_split': 2, 'min_samples_leaf': 7, 'max_features': 0.4, 'criterion': 'gini', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 2.5522100411861677e-07}. Best is trial 44 with value: 0.7446598633568116.
[I 2026-08-26 09:09:24,855] Trial 48 finished with value: 0.7420959249992117 and parameters: {'max_depth': 23, 'min_samples_split': 2, 'min_samples_leaf': 4, 'max_features': 0.4, 'criterion': 'gini', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 2.660507604823095e-07}. Best is trial 44 with value: 0.7446598633568116.
[I 2026-08-26 09:09:25,325] Trial 49 finished with value: 0.7458953869650844 and parameters: {'max_depth': 24, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 0.4, 'criterion': 'gini', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 6.868656085413827e-08}. Best is trial 49 with value: 0.7458953869650844.
[I 2026-08-26 09:09:25,785] Trial 50 finished with value: 0.7547855616133679 and parameters: {'max_depth': 19, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 0.4, 'criterion': 'gini', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 4.431892538357521e-08}. Best is trial 50 with value: 0.7547855616133679.
[I 2026-08-26 09:09:26,225] Trial 51 finished with value: 0.7408845414443384 and parameters: {'max_depth': 17, 'min_samples_split': 3, 'min_samples_leaf': 1, 'max_features': 0.4, 'criterion': 'gini', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 4.93535925698114e-08}. Best is trial 50 with value: 0.7547855616133679.
[I 2026-08-26 09:09:26,646] Trial 52 finished with value: 0.734794767624149 and parameters: {'max_depth': 19, 'min_samples_split': 5, 'min_samples_leaf': 8, 'max_features': 0.4, 'criterion': 'gini', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 6.201850804344417e-08}. Best is trial 50 with value: 0.7547855616133679.
[I 2026-08-26 09:09:27,058] Trial 53 finished with value: 0.7120804300638246 and parameters: {'max_depth': 23, 'min_samples_split': 2, 'min_samples_leaf': 16, 'max_features': 0.4, 'criterion': 'gini', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 2.8848819195324475e-07}. Best is trial 50 with value: 0.7547855616133679.
[I 2026-08-26 09:09:27,402] Trial 54 finished with value: 0.662076210555321 and parameters: {'max_depth': 19, 'min_samples_split': 2, 'min_samples_leaf': 53, 'max_features': 0.4, 'criterion': 'gini', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 1.1023247721029778e-08}. Best is trial 50 with value: 0.7547855616133679.
[I 2026-08-26 09:09:27,791] Trial 55 finished with value: 0.6991544832066936 and parameters: {'max_depth': 13, 'min_samples_split': 8, 'min_samples_leaf': 5, 'max_features': 0.4, 'criterion': 'gini', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 2.8472962605611265e-07}. Best is trial 50 with value: 0.7547855616133679.
[I 2026-08-26 09:09:28,037] Trial 56 finished with value: 0.7296389956132747 and parameters: {'max_depth': 22, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'log2', 'criterion': 'gini', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 1.0484095779858604e-08}. Best is trial 50 with value: 0.7547855616133679.
[I 2026-08-26 09:09:28,085] Trial 57 finished with value: 0.6619113729867906 and parameters: {'max_depth': 15, 'min_samples_split': 20, 'min_samples_leaf': 7, 'max_features': 0.4, 'criterion': 'gini', 'splitter': 'random', 'class_weight': None, 'ccp_alpha': 3.817208139781272e-08}. Best is trial 50 with value: 0.7547855616133679.
[I 2026-08-26 09:09:28,482] Trial 58 finished with value: 0.7135939445255922 and parameters: {'max_depth': 18, 'min_samples_split': 13, 'min_samples_leaf': 13, 'max_features': 0.4, 'criterion': 'gini', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 2.637673276735415e-09}. Best is trial 50 with value: 0.7547855616133679.

  bianco: tuning Random Forest (200 trials).

[I 2026-08-26 09:12:39,366] Trial 0 finished with value: 0.8122578467668632 and parameters: {'n_estimators': 300, 'max_depth': 32, 'min_samples_split': 3, 'min_samples_leaf': 15, 'max_features': 0.7, 'bootstrap': True, 'criterion': 'log_loss', 'class_weight': None}. Best is trial 0 with value: 0.8122578467668632.
[I 2026-08-26 09:12:50,430] Trial 1 finished with value: 0.7775075059782822 and parameters: {'n_estimators': 600, 'max_depth': 16, 'min_samples_split': 20, 'min_samples_leaf': 13, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'gini', 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8122578467668632.
[I 2026-08-26 09:13:26,089] Trial 2 finished with value: 0.6717864117914523 and parameters: {'n_estimators': 600, 'max_depth': 8, 'min_samples_split': 28, 'min_samples_leaf': 15, 'max_features': 0.7, 'bootstrap': True, 'criterion': 'entropy', 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8122578467668632.
[I 2026-08-26 09:13:54,204] Trial 3 finished with value: 0.791795267091252 and parameters: {'n_estimators': 800, 'max_depth': 24, 'min_samples_split': 25, 'min_samples_leaf': 20, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'log_loss', 'class_weight': None}. Best is trial 0 with value: 0.8122578467668632.
[I 2026-08-26 09:14:16,093] Trial 4 finished with value: 0.7725215347964743 and parameters: {'n_estimators': 1000, 'max_depth': 16, 'min_samples_split': 31, 'min_samples_leaf': 15, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy', 'class_weight': None}. Best is trial 0 with value: 0.8122578467668632.
[I 2026-08-26 09:14:52,536] Trial 5 finished with value: 0.8480947728377547 and parameters: {'n_estimators': 800, 'max_depth': 48, 'min_samples_split': 18, 'min_samples_leaf': 3, 'max_features': 0.3, 'bootstrap': False, 'criterion': 'gini', 'class_weight': 'balanced'}. Best is trial 5 with value: 0.8480947728377547.
[I 2026-08-26 09:15:17,874] Trial 6 finished with value: 0.8240808482954375 and parameters: {'n_estimators': 400, 'max_depth': 48, 'min_samples_split': 34, 'min_samples_leaf': 1, 'max_features': 0.5, 'bootstrap': True, 'criterion': 'entropy', 'class_weight': 'balanced'}. Best is trial 5 with value: 0.8480947728377547.
[I 2026-08-26 09:16:11,544] Trial 7 finished with value: 0.8227163036491728 and parameters: {'n_estimators': 1000, 'max_depth': 32, 'min_samples_split': 19, 'min_samples_leaf': 15, 'max_features': 0.3, 'bootstrap': False, 'criterion': 'log_loss', 'class_weight': 'balanced'}. Best is trial 5 with value: 0.8480947728377547.
[I 2026-08-26 09:18:22,012] Trial 8 finished with value: 0.7311173292190988 and parameters: {'n_estimators': 900, 'max_depth': 24, 'min_samples_split': 40, 'min_samples_leaf': 19, 'max_features': 1.0, 'bootstrap': False, 'criterion': 'gini', 'class_weight': 'balanced_subsample'}. Best is trial 5 with value: 0.8480947728377547.
[I 2026-08-26 09:18:58,971] Trial 9 finished with value: 0.8649834335849527 and parameters: {'n_estimators': 600, 'max_depth': None, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 0.3, 'bootstrap': False, 'criterion': 'log_loss', 'class_weight': 'balanced_subsample'}. Best is trial 9 with value: 0.8649834335849527.
[I 2026-08-26 09:19:18,821] Trial 10 finished with value: 0.8395937006166084 and parameters: {'n_estimators': 500, 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 7, 'max_features': 'log2', 'bootstrap': False, 'criterion': 'log_loss', 'class_weight': 'balanced_subsample'}. Best is trial 9 with value: 0.8649834335849527.
[I 2026-08-26 09:19:52,181] Trial 11 finished with value: 0.8600708492943534 and parameters: {'n_estimators': 700, 'max_depth': 48, 'min_samples_split': 12, 'min_samples_leaf': 1, 'max_features': 0.3, 'bootstrap': False, 'criterion': 'gini', 'class_weight': 'balanced_subsample'}. Best is trial 9 with value: 0.8649834335849527.
[I 2026-08-26 09:20:19,615] Trial 12 finished with value: 0.7986344811453245 and parameters: {'n_estimators': 700, 'max_depth': 12, 'min_samples_split': 11, 'min_samples_leaf': 5, 'max_features': 0.3, 'bootstrap': False, 'criterion': 'gini', 'class_weight': 'balanced_subsample'}. Best is trial 9 with value: 0.8649834335849527.
[I 2026-08-26 09:20:56,463] Trial 13 finished with value: 0.8639935030498649 and parameters: {'n_estimators': 600, 'max_depth': None, 'min_samples_split': 11, 'min_samples_leaf': 1, 'max_features': 0.3, 'bootstrap': False, 'criterion': 'log_loss', 'class_weight': 'balanced_subsample'}. Best is trial 9 with value: 0.8649834335849527.
[I 2026-08-26 09:21:25,105] Trial 14 finished with value: 0.8468236167829293 and parameters: {'n_estimators': 500, 'max_depth': None, 'min_samples_split': 9, 'min_samples_leaf': 8, 'max_features': 0.3, 'bootstrap': False, 'criterion': 'log_loss', 'class_weight': 'balanced_subsample'}. Best is trial 9 with value: 0.8649834335849527.
[I 2026-08-26 09:22:18,480] Trial 15 finished with value: 0.8699190711661517 and parameters: {'n_estimators': 500, 'max_depth': None, 'min_samples_split': 7, 'min_samples_leaf': 4, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'log_loss', 'class_weight': 'balanced_subsample'}. Best is trial 15 with value: 0.8699190711661517.
[I 2026-08-26 09:22:49,097] Trial 16 finished with value: 0.8518913438745495 and parameters: {'n_estimators': 300, 'max_depth': None, 'min_samples_split': 6, 'min_samples_leaf': 9, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'log_loss', 'class_weight': 'balanced_subsample'}. Best is trial 15 with value: 0.8699190711661517.
[I 2026-08-26 09:23:31,401] Trial 17 finished with value: 0.8611389643454478 and parameters: {'n_estimators': 400, 'max_depth': None, 'min_samples_split': 16, 'min_samples_leaf': 4, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'log_loss', 'class_weight': 'balanced_subsample'}. Best is trial 15 with value: 0.8699190711661517.
[I 2026-08-26 09:23:44,735] Trial 18 finished with value: 0.6642409730681125 and parameters: {'n_estimators': 500, 'max_depth': 8, 'min_samples_split': 7, 'min_samples_leaf': 6, 'max_features': 'log2', 'bootstrap': False, 'criterion': 'log_loss', 'class_weight': 'balanced_subsample'}. Best is trial 15 with value: 0.8699190711661517.
[I 2026-08-26 09:24:55,150] Trial 19 finished with value: 0.7061373742686053 and parameters: {'n_estimators': 400, 'max_depth': 12, 'min_samples_split': 15, 'min_samples_leaf': 10, 'max_features': 1.0, 'bootstrap': False, 'criterion': 'log_loss', 'class_weight': 'balanced_subsample'}. Best is trial 15 with value: 0.8699190711661517.
[I 2026-08-26 09:26:08,732] Trial 20 finished with value: 0.8715033686908065 and parameters: {'n_estimators': 700, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 3, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8715033686908065.
[I 2026-08-26 09:27:22,455] Trial 21 finished with value: 0.8715033686908065 and parameters: {'n_estimators': 700, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 3, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8715033686908065.
[I 2026-08-26 09:28:36,605] Trial 22 finished with value: 0.8715033686908065 and parameters: {'n_estimators': 700, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 3, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8715033686908065.
[I 2026-08-26 09:30:00,507] Trial 23 finished with value: 0.8713093564625712 and parameters: {'n_estimators': 800, 'max_depth': None, 'min_samples_split': 3, 'min_samples_leaf': 3, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8715033686908065.
[I 2026-08-26 09:31:14,244] Trial 24 finished with value: 0.8715033686908065 and parameters: {'n_estimators': 700, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 3, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8715033686908065.
[I 2026-08-26 09:32:45,275] Trial 25 finished with value: 0.8605293430731041 and parameters: {'n_estimators': 900, 'max_depth': None, 'min_samples_split': 14, 'min_samples_leaf': 6, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8715033686908065.
[I 2026-08-26 09:33:29,259] Trial 26 finished with value: 0.8493558651505658 and parameters: {'n_estimators': 700, 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 5, 'max_features': 0.5, 'bootstrap': True, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8715033686908065.
[I 2026-08-26 09:34:39,191] Trial 27 finished with value: 0.8043118909816158 and parameters: {'n_estimators': 800, 'max_depth': 12, 'min_samples_split': 7, 'min_samples_leaf': 11, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8715033686908065.
[I 2026-08-26 09:36:09,957] Trial 28 finished with value: 0.8620682710490689 and parameters: {'n_estimators': 900, 'max_depth': 16, 'min_samples_split': 5, 'min_samples_leaf': 3, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8715033686908065.
[I 2026-08-26 09:37:07,338] Trial 29 finished with value: 0.8449044116291583 and parameters: {'n_estimators': 700, 'max_depth': 32, 'min_samples_split': 4, 'min_samples_leaf': 7, 'max_features': 0.7, 'bootstrap': True, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8715033686908065.
[I 2026-08-26 09:38:02,871] Trial 30 finished with value: 0.6844398845436943 and parameters: {'n_estimators': 800, 'max_depth': 8, 'min_samples_split': 9, 'min_samples_leaf': 2, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8715033686908065.
[I 2026-08-26 09:39:15,639] Trial 31 finished with value: 0.8698895920182649 and parameters: {'n_estimators': 700, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 4, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8715033686908065.
[I 2026-08-26 09:40:18,683] Trial 32 finished with value: 0.8708942573725891 and parameters: {'n_estimators': 600, 'max_depth': None, 'min_samples_split': 8, 'min_samples_leaf': 3, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8715033686908065.
[I 2026-08-26 09:41:55,600] Trial 33 finished with value: 0.8646809515631102 and parameters: {'n_estimators': 700, 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 5, 'max_features': 0.7, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8715033686908065.
[I 2026-08-26 09:42:34,640] Trial 34 finished with value: 0.8519120682874576 and parameters: {'n_estimators': 600, 'max_depth': 32, 'min_samples_split': 13, 'min_samples_leaf': 2, 'max_features': 0.5, 'bootstrap': True, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8715033686908065.
[I 2026-08-26 09:43:06,644] Trial 35 finished with value: 0.8390229726681498 and parameters: {'n_estimators': 800, 'max_depth': 24, 'min_samples_split': 22, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8715033686908065.
[I 2026-08-26 09:43:23,311] Trial 36 finished with value: 0.813538671387611 and parameters: {'n_estimators': 700, 'max_depth': 16, 'min_samples_split': 5, 'min_samples_leaf': 6, 'max_features': 'log2', 'bootstrap': True, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8715033686908065.
[I 2026-08-26 09:45:27,337] Trial 37 finished with value: 0.783911631929177 and parameters: {'n_estimators': 600, 'max_depth': None, 'min_samples_split': 4, 'min_samples_leaf': 4, 'max_features': 1.0, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8715033686908065.
[I 2026-08-26 09:45:48,700] Trial 38 finished with value: 0.6641096706088134 and parameters: {'n_estimators': 800, 'max_depth': 8, 'min_samples_split': 8, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'entropy', 'class_weight': 'balanced'}. Best is trial 20 with value: 0.8715033686908065.
[I 2026-08-26 09:46:43,499] Trial 39 finished with value: 0.8407088009129892 and parameters: {'n_estimators': 900, 'max_depth': 24, 'min_samples_split': 6, 'min_samples_leaf': 7, 'max_features': 0.5, 'bootstrap': True, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8715033686908065.
[I 2026-08-26 09:48:08,756] Trial 40 finished with value: 0.867441064303962 and parameters: {'n_estimators': 600, 'max_depth': 48, 'min_samples_split': 10, 'min_samples_leaf': 3, 'max_features': 0.7, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8715033686908065.
[I 2026-08-26 09:49:32,736] Trial 41 finished with value: 0.8713093564625712 and parameters: {'n_estimators': 800, 'max_depth': None, 'min_samples_split': 3, 'min_samples_leaf': 3, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8715033686908065.
[I 2026-08-26 09:50:55,732] Trial 42 finished with value: 0.8701717326540936 and parameters: {'n_estimators': 800, 'max_depth': None, 'min_samples_split': 4, 'min_samples_leaf': 4, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8715033686908065.
[I 2026-08-26 09:52:00,418] Trial 43 finished with value: 0.8235798303234658 and parameters: {'n_estimators': 700, 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 18, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8715033686908065.
[I 2026-08-26 09:53:01,121] Trial 44 finished with value: 0.8711127530840723 and parameters: {'n_estimators': 700, 'max_depth': None, 'min_samples_split': 4, 'min_samples_leaf': 1, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'gini', 'class_weight': 'balanced'}. Best is trial 20 with value: 0.8715033686908065.
[I 2026-08-26 09:54:23,209] Trial 45 finished with value: 0.8654154392930483 and parameters: {'n_estimators': 800, 'max_depth': None, 'min_samples_split': 9, 'min_samples_leaf': 5, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8715033686908065.
[I 2026-08-26 09:55:50,814] Trial 46 finished with value: 0.8321894067272048 and parameters: {'n_estimators': 900, 'max_depth': 16, 'min_samples_split': 40, 'min_samples_leaf': 2, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8715033686908065.
[I 2026-08-26 09:57:42,742] Trial 47 finished with value: 0.7453660543896123 and parameters: {'n_estimators': 700, 'max_depth': None, 'min_samples_split': 37, 'min_samples_leaf': 3, 'max_features': 1.0, 'bootstrap': False, 'criterion': 'gini', 'class_weight': 'balanced'}. Best is trial 20 with value: 0.8715033686908065.
[I 2026-08-26 09:58:06,519] Trial 48 finished with value: 0.8327201763513923 and parameters: {'n_estimators': 600, 'max_depth': 48, 'min_samples_split': 28, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8715033686908065.
[I 2026-08-26 09:58:46,202] Trial 49 finished with value: 0.8476741197926444 and parameters: {'n_estimators': 1000, 'max_depth': 32, 'min_samples_split': 6, 'min_samples_leaf': 5, 'max_features': 'log2', 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8715033686908065.
[I 2026-08-26 09:59:23,218] Trial 50 finished with value: 0.8300562454215787 and parameters: {'n_estimators': 800, 'max_depth': None, 'min_samples_split': 11, 'min_samples_leaf': 8, 'max_features': 0.5, 'bootstrap': True, 'criterion': 'gini', 'class_weight': None}. Best is trial 20 with value: 0.8715033686908065.
[I 2026-08-26 10:00:47,345] Trial 51 finished with value: 0.8713093564625712 and parameters: {'n_estimators': 800, 'max_depth': None, 'min_samples_split': 3, 'min_samples_leaf': 3, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8715033686908065.
[I 2026-08-26 10:02:00,933] Trial 52 finished with value: 0.8715033686908065 and parameters: {'n_estimators': 700, 'max_depth': None, 'min_samples_split': 3, 'min_samples_leaf': 3, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8715033686908065.
[I 2026-08-26 10:03:13,705] Trial 53 finished with value: 0.8698895920182649 and parameters: {'n_estimators': 700, 'max_depth': None, 'min_samples_split': 7, 'min_samples_leaf': 4, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8715033686908065.
[I 2026-08-26 10:04:17,664] Trial 54 finished with value: 0.8742628269800322 and parameters: {'n_estimators': 600, 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 2, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 54 with value: 0.8742628269800322.
[I 2026-08-26 10:05:12,337] Trial 55 finished with value: 0.8215026792971732 and parameters: {'n_estimators': 600, 'max_depth': 12, 'min_samples_split': 5, 'min_samples_leaf': 2, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 54 with value: 0.8742628269800322.
[I 2026-08-26 10:06:07,745] Trial 56 finished with value: 0.8754130572023169 and parameters: {'n_estimators': 500, 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': 'balanced'}. Best is trial 56 with value: 0.8754130572023169.
[I 2026-08-26 10:07:02,622] Trial 57 finished with value: 0.8734835100151548 and parameters: {'n_estimators': 500, 'max_depth': None, 'min_samples_split': 8, 'min_samples_leaf': 1, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': 'balanced'}. Best is trial 56 with value: 0.8754130572023169.
[I 2026-08-26 10:07:33,204] Trial 58 finished with value: 0.8627915922482678 and parameters: {'n_estimators': 500, 'max_depth': 24, 'min_samples_split': 12, 'min_samples_leaf': 1, 'max_features': 0.3, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': 'balanced'}. Best is trial 56 with value: 0.8754130572023169.
[I 2026-08-26 10:08:16,861] Trial 59 finished with value: 0.869780454372229 and parameters: {'n_estimators': 500, 'max_depth': None, 'min_samples_split': 8, 'min_samples_leaf': 1, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'gini', 'class_weight': 'balanced'}. Best is trial 56 with value: 0.8754130572023169.
[I 2026-08-26 10:10:03,395] Trial 60 finished with value: 0.7778762089090433 and parameters: {'n_estimators': 500, 'max_depth': None, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 1.0, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': 'balanced'}. Best is trial 56 with value: 0.8754130572023169.
[I 2026-08-26 10:10:47,134] Trial 61 finished with value: 0.8723145087660908 and parameters: {'n_estimators': 400, 'max_depth': None, 'min_samples_split': 6, 'min_samples_leaf': 2, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': 'balanced'}. Best is trial 56 with value: 0.8754130572023169.

  bianco: tuning XGBoost (200 trials).

[I 2026-08-26 12:19:14,362] Trial 0 finished with value: 0.8358851293866095 and parameters: {'max_depth': 9, 'learning_rate': 0.019677977348166304, 'subsample': 0.8978561926718072, 'colsample_bytree': 0.7442003345025142, 'min_child_weight': 2.1771032186203514, 'gamma': 1.8277151418544553, 'reg_alpha': 8.665537597324885e-06, 'reg_lambda': 1.0311514495138399}. Best is trial 0 with value: 0.8358851293866095.
[I 2026-08-26 12:19:30,104] Trial 1 finished with value: 0.8525307266509768 and parameters: {'max_depth': 7, 'learning_rate': 0.09439831569936806, 'subsample': 0.9842104900822669, 'colsample_bytree': 0.7826484435755748, 'min_child_weight': 2.880043790954131, 'gamma': 0.3403911033599112, 'reg_alpha': 1.5100408408589772e-07, 'reg_lambda': 23.538263110950048}. Best is trial 1 with value: 0.8525307266509768.
[I 2026-08-26 12:19:46,833] Trial 2 finished with value: 0.8707084398731398 and parameters: {'max_depth': 10, 'learning_rate': 0.14726161255504092, 'subsample': 0.8585642249613574, 'colsample_bytree': 0.6855299248522434, 'min_child_weight': 6.781935357780796, 'gamma': 0.41743875595471047, 'reg_alpha': 3.864031899313156e-05, 'reg_lambda': 14.610499699549097}. Best is trial 2 with value: 0.8707084398731398.
[I 2026-08-26 12:20:02,602] Trial 3 finished with value: 0.8496985345614421 and parameters: {'max_depth': 5, 'learning_rate': 0.08394754752250128, 'subsample': 0.9450697344147837, 'colsample_bytree': 0.6595392252176876, 'min_child_weight': 5.011643571251018, 'gamma': 0.4774657914394431, 'reg_alpha': 5.357340695323986e-08, 'reg_lambda': 0.18099954688158187}. Best is trial 2 with value: 0.8707084398731398.
[I 2026-08-26 12:20:18,341] Trial 4 finished with value: 0.7997623600624479 and parameters: {'max_depth': 4, 'learning_rate': 0.048769840070943336, 'subsample': 0.9178299664912868, 'colsample_bytree': 0.9963290723923126, 'min_child_weight': 13.502442798764482, 'gamma': 1.1322462171492673, 'reg_alpha': 0.00014367270092871558, 'reg_lambda': 0.1399264351773497}. Best is trial 2 with value: 0.8707084398731398.
[I 2026-08-26 12:20:36,465] Trial 5 finished with value: 0.7834719379868638 and parameters: {'max_depth': 8, 'learning_rate': 0.018099146987238985, 'subsample': 0.953044632771952, 'colsample_bytree': 0.8904231274266234, 'min_child_weight': 15.164258427643505, 'gamma': 2.130692051488852, 'reg_alpha': 0.009425386803829051, 'reg_lambda': 20.136195700340338}. Best is trial 2 with value: 0.8707084398731398.
[I 2026-08-26 12:21:09,905] Trial 6 finished with value: 0.8409497701954727 and parameters: {'max_depth': 10, 'learning_rate': 0.01918354750824495, 'subsample': 0.782598566894961, 'colsample_bytree': 0.7970893967426577, 'min_child_weight': 0.7811624819629674, 'gamma': 0.46120338258524907, 'reg_alpha': 6.963704487425356, 'reg_lambda': 0.47063847559435423}. Best is trial 2 with value: 0.8707084398731398.
[I 2026-08-26 12:21:33,951] Trial 7 finished with value: 0.8551460550110856 and parameters: {'max_depth': 10, 'learning_rate': 0.022953302153308094, 'subsample': 0.6529433178954122, 'colsample_bytree': 0.7269413610677277, 'min_child_weight': 1.7604099383967902, 'gamma': 1.266165560263202, 'reg_alpha': 2.041568273325791e-06, 'reg_lambda': 2.5538276254965817}. Best is trial 2 with value: 0.8707084398731398.
[I 2026-08-26 12:21:52,994] Trial 8 finished with value: 0.8243323463505096 and parameters: {'max_depth': 3, 'learning_rate': 0.11851328676362981, 'subsample': 0.7074625481911713, 'colsample_bytree': 0.9645659651689448, 'min_child_weight': 20.063522776432464, 'gamma': 0.047573401053791486, 'reg_alpha': 0.34420918881100815, 'reg_lambda': 4.715832950352583}. Best is trial 2 with value: 0.8707084398731398.
[I 2026-08-26 12:22:07,607] Trial 9 finished with value: 0.7238322489926128 and parameters: {'max_depth': 3, 'learning_rate': 0.033391708755025735, 'subsample': 0.8256997968048689, 'colsample_bytree': 0.837631051781117, 'min_child_weight': 8.12005959578132, 'gamma': 1.8972954750065205, 'reg_alpha': 2.437950567013768, 'reg_lambda': 6.697837558293906}. Best is trial 2 with value: 0.8707084398731398.
[I 2026-08-26 12:22:17,644] Trial 10 finished with value: 0.78261957156579 and parameters: {'max_depth': 6, 'learning_rate': 0.17115128841996644, 'subsample': 0.8154186866999962, 'colsample_bytree': 0.6025554256995838, 'min_child_weight': 0.8625345056254972, 'gamma': 2.9869578392012968, 'reg_alpha': 1.239446148413562e-09, 'reg_lambda': 0.9684799729031198}. Best is trial 2 with value: 0.8707084398731398.
[I 2026-08-26 12:22:37,985] Trial 11 finished with value: 0.8570340523160944 and parameters: {'max_depth': 10, 'learning_rate': 0.04809950013571818, 'subsample': 0.6132599083973347, 'colsample_bytree': 0.7068708218135153, 'min_child_weight': 2.000151976177787, 'gamma': 1.1015819037394388, 'reg_alpha': 4.514632609962317e-05, 'reg_lambda': 5.019540607508096}. Best is trial 2 with value: 0.8707084398731398.
[I 2026-08-26 12:22:58,362] Trial 12 finished with value: 0.8547945996323734 and parameters: {'max_depth': 9, 'learning_rate': 0.05449774578204275, 'subsample': 0.6446773085991204, 'colsample_bytree': 0.6782743329282878, 'min_child_weight': 5.024974615071706, 'gamma': 1.0252076108694772, 'reg_alpha': 0.0009910433108845519, 'reg_lambda': 8.210034909208419}. Best is trial 2 with value: 0.8707084398731398.
[I 2026-08-26 12:23:14,809] Trial 13 finished with value: 0.85976741796909 and parameters: {'max_depth': 10, 'learning_rate': 0.19639010434181664, 'subsample': 0.6021768360536973, 'colsample_bytree': 0.6725320077667093, 'min_child_weight': 1.334503164197373, 'gamma': 0.7848649789462945, 'reg_alpha': 6.501336646332095e-05, 'reg_lambda': 11.389015447500912}. Best is trial 2 with value: 0.8707084398731398.
[I 2026-08-26 12:23:30,005] Trial 14 finished with value: 0.858551660131876 and parameters: {'max_depth': 8, 'learning_rate': 0.1748224970113755, 'subsample': 0.7251257998024343, 'colsample_bytree': 0.6067985020666221, 'min_child_weight': 0.5629506277333849, 'gamma': 0.7357192839349284, 'reg_alpha': 0.007366281502087388, 'reg_lambda': 15.167077457961938}. Best is trial 2 with value: 0.8707084398731398.
[I 2026-08-26 12:24:00,347] Trial 15 finished with value: 0.8648432435241358 and parameters: {'max_depth': 9, 'learning_rate': 0.19817774165410926, 'subsample': 0.8690856269930812, 'colsample_bytree': 0.6536074054839038, 'min_child_weight': 27.489547649192218, 'gamma': 0.014190871821646578, 'reg_alpha': 7.749040818304145e-07, 'reg_lambda': 11.633131249215683}. Best is trial 2 with value: 0.8707084398731398.
[I 2026-08-26 12:24:39,335] Trial 16 finished with value: 0.8633413100460657 and parameters: {'max_depth': 8, 'learning_rate': 0.13177796734730307, 'subsample': 0.8586927017191538, 'colsample_bytree': 0.6390519450381702, 'min_child_weight': 29.266819628702436, 'gamma': 0.020524823242183767, 'reg_alpha': 2.2588770720502548e-07, 'reg_lambda': 3.0830473334047306}. Best is trial 2 with value: 0.8707084398731398.
[I 2026-08-26 12:24:58,223] Trial 17 finished with value: 0.8780553715921655 and parameters: {'max_depth': 9, 'learning_rate': 0.11559880571167458, 'subsample': 0.8864095686072445, 'colsample_bytree': 0.7462766269481121, 'min_child_weight': 8.540761076488415, 'gamma': 0.262938132752185, 'reg_alpha': 2.172213690433863e-09, 'reg_lambda': 2.083558458304227}. Best is trial 17 with value: 0.8780553715921655.
[I 2026-08-26 12:25:11,982] Trial 18 finished with value: 0.8355722541857261 and parameters: {'max_depth': 6, 'learning_rate': 0.0782463128351522, 'subsample': 0.7667214138864583, 'colsample_bytree': 0.7685876627442525, 'min_child_weight': 7.513754202666461, 'gamma': 1.4557408989094207, 'reg_alpha': 3.0898501493733272e-09, 'reg_lambda': 1.1357101578547972}. Best is trial 17 with value: 0.8780553715921655.
[I 2026-08-26 12:25:22,527] Trial 19 finished with value: 0.8371484552667887 and parameters: {'max_depth': 7, 'learning_rate': 0.13279314941400044, 'subsample': 0.9967124142755496, 'colsample_bytree': 0.8425310595120723, 'min_child_weight': 4.053989981004542, 'gamma': 0.7312884368852899, 'reg_alpha': 1.3760240810671025e-08, 'reg_lambda': 0.35425072033627353}. Best is trial 17 with value: 0.8780553715921655.
[I 2026-08-26 12:25:46,449] Trial 20 finished with value: 0.87475293241197 and parameters: {'max_depth': 9, 'learning_rate': 0.06418949709826452, 'subsample': 0.8681238025780942, 'colsample_bytree': 0.705568621452069, 'min_child_weight': 9.115994902439157, 'gamma': 0.31089772099195145, 'reg_alpha': 0.09095647740042732, 'reg_lambda': 2.2641434467107167}. Best is trial 17 with value: 0.8780553715921655.
[I 2026-08-26 12:26:07,062] Trial 21 finished with value: 0.8731170287189804 and parameters: {'max_depth': 9, 'learning_rate': 0.06857798114488887, 'subsample': 0.8782041330301507, 'colsample_bytree': 0.7156866437123837, 'min_child_weight': 8.748670161501403, 'gamma': 0.34181595694196115, 'reg_alpha': 0.48317265512657953, 'reg_lambda': 1.9422836377699944}. Best is trial 17 with value: 0.8780553715921655.
[I 2026-08-26 12:26:28,767] Trial 22 finished with value: 0.8701848815704075 and parameters: {'max_depth': 9, 'learning_rate': 0.06651217468208913, 'subsample': 0.900149073766403, 'colsample_bytree': 0.739912759336613, 'min_child_weight': 11.554094959194167, 'gamma': 0.34106308655449113, 'reg_alpha': 0.15851927368239083, 'reg_lambda': 1.9222542302610328}. Best is trial 17 with value: 0.8780553715921655.
[I 2026-08-26 12:26:53,021] Trial 23 finished with value: 0.8768712463582847 and parameters: {'max_depth': 8, 'learning_rate': 0.10357567616016997, 'subsample': 0.8224550556193101, 'colsample_bytree': 0.8161400869086647, 'min_child_weight': 9.825653021639553, 'gamma': 0.2298959367723586, 'reg_alpha': 0.03367336652018941, 'reg_lambda': 1.616281742805327}. Best is trial 17 with value: 0.8780553715921655.
[I 2026-08-26 12:27:09,560] Trial 24 finished with value: 0.8641812594647591 and parameters: {'max_depth': 7, 'learning_rate': 0.10408414139034529, 'subsample': 0.8172555698933346, 'colsample_bytree': 0.8500368212761793, 'min_child_weight': 11.4194089410537, 'gamma': 0.6478612884614297, 'reg_alpha': 0.011601566918598627, 'reg_lambda': 0.6463820045841848}. Best is trial 17 with value: 0.8780553715921655.
[I 2026-08-26 12:27:51,125] Trial 25 finished with value: 0.8653259936855772 and parameters: {'max_depth': 8, 'learning_rate': 0.03376207213703955, 'subsample': 0.7615666242320015, 'colsample_bytree': 0.8156322899320291, 'min_child_weight': 16.79796399788668, 'gamma': 0.19348598583840332, 'reg_alpha': 0.0544165872863283, 'reg_lambda': 1.386114759754914}. Best is trial 17 with value: 0.8780553715921655.
[I 2026-08-26 12:28:04,417] Trial 26 finished with value: 0.8601239438915359 and parameters: {'max_depth': 8, 'learning_rate': 0.10264804653521425, 'subsample': 0.8380099865899632, 'colsample_bytree': 0.8981480418851177, 'min_child_weight': 3.707821157244363, 'gamma': 0.949955346389509, 'reg_alpha': 0.0003824362507556758, 'reg_lambda': 3.271475386017675}. Best is trial 17 with value: 0.8780553715921655.
[I 2026-08-26 12:28:29,066] Trial 27 finished with value: 0.8684626484022271 and parameters: {'max_depth': 7, 'learning_rate': 0.039562476336283556, 'subsample': 0.7895756603797992, 'colsample_bytree': 0.7600053655625387, 'min_child_weight': 5.984494598696171, 'gamma': 0.5912999703320375, 'reg_alpha': 0.0011105988818385128, 'reg_lambda': 0.6872518464735312}. Best is trial 17 with value: 0.8780553715921655.
[I 2026-08-26 12:28:57,300] Trial 28 finished with value: 0.8798321251366319 and parameters: {'max_depth': 9, 'learning_rate': 0.06440850471552748, 'subsample': 0.92788520711102, 'colsample_bytree': 0.9035571214411334, 'min_child_weight': 9.356929348314193, 'gamma': 0.16307760375610608, 'reg_alpha': 0.03078720565945149, 'reg_lambda': 1.7914082629340526}. Best is trial 28 with value: 0.8798321251366319.
[I 2026-08-26 12:29:17,802] Trial 29 finished with value: 0.8760036914499623 and parameters: {'max_depth': 9, 'learning_rate': 0.08240518340999604, 'subsample': 0.9241458984244015, 'colsample_bytree': 0.9177835330770112, 'min_child_weight': 10.099523253467344, 'gamma': 0.174106856033297, 'reg_alpha': 1.5900935063071773, 'reg_lambda': 1.4202338879009222}. Best is trial 28 with value: 0.8798321251366319.
[I 2026-08-26 12:29:29,637] Trial 30 finished with value: 0.824031104559768 and parameters: {'max_depth': 6, 'learning_rate': 0.12088884539740243, 'subsample': 0.9683188589261923, 'colsample_bytree': 0.939508325727845, 'min_child_weight': 18.11504872628474, 'gamma': 0.8704176806234408, 'reg_alpha': 2.9945472770271383e-06, 'reg_lambda': 0.31148575461658956}. Best is trial 28 with value: 0.8798321251366319.
[I 2026-08-26 12:29:49,222] Trial 31 finished with value: 0.8730464628400924 and parameters: {'max_depth': 9, 'learning_rate': 0.08146000052092844, 'subsample': 0.9362053170330361, 'colsample_bytree': 0.8900715317553145, 'min_child_weight': 11.870956011452801, 'gamma': 0.17942344583682485, 'reg_alpha': 2.0854406303849107, 'reg_lambda': 1.5208346220440563}. Best is trial 28 with value: 0.8798321251366319.
[I 2026-08-26 12:30:15,823] Trial 32 finished with value: 0.8673618425994457 and parameters: {'max_depth': 8, 'learning_rate': 0.09885878528944196, 'subsample': 0.909675369976811, 'colsample_bytree': 0.919748875588488, 'min_child_weight': 22.165997395137644, 'gamma': 0.21161042326574936, 'reg_alpha': 0.031315264630833645, 'reg_lambda': 0.9314326575690436}. Best is trial 28 with value: 0.8798321251366319.
[I 2026-08-26 12:30:28,993] Trial 33 finished with value: 0.8254864320751268 and parameters: {'max_depth': 9, 'learning_rate': 0.08829160413873587, 'subsample': 0.9269577594536152, 'colsample_bytree': 0.9461092517946128, 'min_child_weight': 9.89521112813443, 'gamma': 0.45624620808148064, 'reg_alpha': 9.408302944249108, 'reg_lambda': 4.02067526434441}. Best is trial 28 with value: 0.8798321251366319.
[I 2026-08-26 12:30:41,832] Trial 34 finished with value: 0.8694473746301792 and parameters: {'max_depth': 10, 'learning_rate': 0.1518842040197946, 'subsample': 0.8932166349718167, 'colsample_bytree': 0.86212959718046, 'min_child_weight': 6.099993119114918, 'gamma': 0.5654177682075594, 'reg_alpha': 0.002554702091970482, 'reg_lambda': 1.561814380642602}. Best is trial 28 with value: 0.8798321251366319.
[I 2026-08-26 12:31:01,687] Trial 35 finished with value: 0.8755105857704597 and parameters: {'max_depth': 8, 'learning_rate': 0.057010858584817074, 'subsample': 0.9701838936753047, 'colsample_bytree': 0.8100029298045003, 'min_child_weight': 3.971121098849584, 'gamma': 0.17607982394743638, 'reg_alpha': 1.0026208197559328, 'reg_lambda': 0.683470361192524}. Best is trial 28 with value: 0.8798321251366319.
[I 2026-08-26 12:31:12,726] Trial 36 finished with value: 0.816697393961498 and parameters: {'max_depth': 9, 'learning_rate': 0.07446615169345247, 'subsample': 0.8902886358325917, 'colsample_bytree': 0.9905462897315671, 'min_child_weight': 2.990249280584988, 'gamma': 2.7487401913156297, 'reg_alpha': 0.21553249625497864, 'reg_lambda': 1.2355485254037823}. Best is trial 28 with value: 0.8798321251366319.
[I 2026-08-26 12:31:27,268] Trial 37 finished with value: 0.8590529315094818 and parameters: {'max_depth': 7, 'learning_rate': 0.09085903956289838, 'subsample': 0.9523040240550134, 'colsample_bytree': 0.8763432271184883, 'min_child_weight': 5.2572706663202045, 'gamma': 0.49783530413082216, 'reg_alpha': 0.02562594847196976, 'reg_lambda': 2.8622239421249454}. Best is trial 28 with value: 0.8798321251366319.
[I 2026-08-26 12:31:43,796] Trial 38 finished with value: 0.8783749077444041 and parameters: {'max_depth': 10, 'learning_rate': 0.11269210100597075, 'subsample': 0.9210246173601286, 'colsample_bytree': 0.7823465728292601, 'min_child_weight': 6.815700128823182, 'gamma': 0.2736613551856823, 'reg_alpha': 9.289752003627775e-06, 'reg_lambda': 0.8973725721058692}. Best is trial 28 with value: 0.8798321251366319.
[I 2026-08-26 12:32:02,922] Trial 39 finished with value: 0.8710477259025341 and parameters: {'max_depth': 10, 'learning_rate': 0.11441806103579943, 'subsample': 0.8511461396467839, 'colsample_bytree': 0.7874682268629749, 'min_child_weight': 14.401850755915802, 'gamma': 0.3780428799800073, 'reg_alpha': 4.864594119581704e-08, 'reg_lambda': 0.23665918139440748}. Best is trial 28 with value: 0.8798321251366319.
[I 2026-08-26 12:32:12,558] Trial 40 finished with value: 0.8407356905699255 and parameters: {'max_depth': 10, 'learning_rate': 0.14742947603882298, 'subsample': 0.9691385867743643, 'colsample_bytree': 0.7623638871931769, 'min_child_weight': 6.818164328183039, 'gamma': 1.347971371267619, 'reg_alpha': 1.776242175507318e-05, 'reg_lambda': 0.8460465685637126}. Best is trial 28 with value: 0.8798321251366319.
[I 2026-08-26 12:32:33,755] Trial 41 finished with value: 0.8811778758068151 and parameters: {'max_depth': 9, 'learning_rate': 0.10583738916086247, 'subsample': 0.9199604370213873, 'colsample_bytree': 0.8230513798268493, 'min_child_weight': 7.439838656943802, 'gamma': 0.151445675225869, 'reg_alpha': 6.516119789414097e-06, 'reg_lambda': 0.5207717991609646}. Best is trial 41 with value: 0.8811778758068151.
[I 2026-08-26 12:33:00,669] Trial 42 finished with value: 0.8840147699089111 and parameters: {'max_depth': 10, 'learning_rate': 0.11275323430879314, 'subsample': 0.9106104519441277, 'colsample_bytree': 0.8228414012688231, 'min_child_weight': 7.310656745265945, 'gamma': 0.014642111988752537, 'reg_alpha': 0.00017000040858317422, 'reg_lambda': 0.1274497172043531}. Best is trial 42 with value: 0.8840147699089111.
[I 2026-08-26 12:33:25,312] Trial 43 finished with value: 0.8834102346199192 and parameters: {'max_depth': 10, 'learning_rate': 0.12963862529136935, 'subsample': 0.912876909972581, 'colsample_bytree': 0.7986871572166412, 'min_child_weight': 6.671783247432165, 'gamma': 0.0027489230804911002, 'reg_alpha': 6.432045221502888e-06, 'reg_lambda': 0.16873361155679586}. Best is trial 42 with value: 0.8840147699089111.
[I 2026-08-26 12:33:45,964] Trial 44 finished with value: 0.8854466504530849 and parameters: {'max_depth': 10, 'learning_rate': 0.13438171891113485, 'subsample': 0.9438464562071578, 'colsample_bytree': 0.8291545919409499, 'min_child_weight': 6.759346456870686, 'gamma': 0.04484018730534913, 'reg_alpha': 6.234155584767853e-06, 'reg_lambda': 0.11579663844546687}. Best is trial 44 with value: 0.8854466504530849.
[I 2026-08-26 12:34:08,895] Trial 45 finished with value: 0.887132055693379 and parameters: {'max_depth': 10, 'learning_rate': 0.13425298654718823, 'subsample': 0.9444137230908928, 'colsample_bytree': 0.8366027486709143, 'min_child_weight': 4.393884468634246, 'gamma': 0.0074592591523478516, 'reg_alpha': 2.866300487200738e-06, 'reg_lambda': 0.12470614007973976}. Best is trial 45 with value: 0.887132055693379.
[I 2026-08-26 12:34:22,061] Trial 46 finished with value: 0.8877474627480811 and parameters: {'max_depth': 10, 'learning_rate': 0.15716659617597792, 'subsample': 0.9919841850693425, 'colsample_bytree': 0.8300844307506628, 'min_child_weight': 2.638176514631532, 'gamma': 0.033949120465310595, 'reg_alpha': 2.5527729277360785e-06, 'reg_lambda': 0.10719977296294511}. Best is trial 46 with value: 0.8877474627480811.
[I 2026-08-26 12:34:36,802] Trial 47 finished with value: 0.8863596510295579 and parameters: {'max_depth': 10, 'learning_rate': 0.157926156162152, 'subsample': 0.9945199245851312, 'colsample_bytree': 0.799244337406663, 'min_child_weight': 2.6258870771557934, 'gamma': 0.039965823056099754, 'reg_alpha': 5.40605826184488e-07, 'reg_lambda': 0.10527598360394627}. Best is trial 46 with value: 0.8877474627480811.

[3/6] Creating 80/20 split with 'geneva' completely held out.

[I 2026-08-26 14:04:25,233] A new study created in memory with name: DecisionTree_LOSO

[3/6] Running one 5-fold search per model.
  geneva: tuning Decision Tree (200 trials).

[I 2026-08-26 14:04:25,462] Trial 0 finished with value: 0.6937602640477005 and parameters: {'max_depth': 12, 'min_samples_split': 96, 'min_samples_leaf': 59, 'max_features': 0.6, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 1.3480180290890803e-07}. Best is trial 0 with value: 0.6937602640477005.
[I 2026-08-26 14:04:25,493] Trial 1 finished with value: 0.5913222953500029 and parameters: {'max_depth': 17, 'min_samples_split': 44, 'min_samples_leaf': 24, 'max_features': 0.8, 'criterion': 'log_loss', 'splitter': 'random', 'class_weight': None, 'ccp_alpha': 0.0043873144324354085}. Best is trial 0 with value: 0.6937602640477005.
[I 2026-08-26 14:04:25,508] Trial 2 finished with value: 0.5272607201460252 and parameters: {'max_depth': 30, 'min_samples_split': 82, 'min_samples_leaf': 25, 'max_features': 'sqrt', 'criterion': 'gini', 'splitter': 'random', 'class_weight': None, 'ccp_alpha': 0.006124806805925988}. Best is trial 0 with value: 0.6937602640477005.
[I 2026-08-26 14:04:25,586] Trial 3 finished with value: 0.644339821451144 and parameters: {'max_depth': 24, 'min_samples_split': 95, 'min_samples_leaf': 72, 'max_features': 'sqrt', 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 0.00041245717727594227}. Best is trial 0 with value: 0.6937602640477005.
[I 2026-08-26 14:04:25,634] Trial 4 finished with value: 0.6012811153083593 and parameters: {'max_depth': 4, 'min_samples_split': 99, 'min_samples_leaf': 62, 'max_features': 'log2', 'criterion': 'entropy', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 1.5027137214154575e-07}. Best is trial 0 with value: 0.6937602640477005.
[I 2026-08-26 14:04:25,965] Trial 5 finished with value: 0.6895254765056305 and parameters: {'max_depth': 11, 'min_samples_split': 74, 'min_samples_leaf': 52, 'max_features': None, 'criterion': 'gini', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 2.8501838758433707e-05}. Best is trial 0 with value: 0.6937602640477005.
[I 2026-08-26 14:04:25,978] Trial 6 finished with value: 0.5815209854432379 and parameters: {'max_depth': 11, 'min_samples_split': 52, 'min_samples_leaf': 73, 'max_features': 'log2', 'criterion': 'entropy', 'splitter': 'random', 'class_weight': None, 'ccp_alpha': 0.0017697543538533224}. Best is trial 0 with value: 0.6937602640477005.
[I 2026-08-26 14:04:26,278] Trial 7 finished with value: 0.6876837188266516 and parameters: {'max_depth': 17, 'min_samples_split': 81, 'min_samples_leaf': 72, 'max_features': 0.8, 'criterion': 'entropy', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 1.8298712093870903e-07}. Best is trial 0 with value: 0.6937602640477005.
[I 2026-08-26 14:04:26,310] Trial 8 finished with value: 0.6521802633023437 and parameters: {'max_depth': 17, 'min_samples_split': 71, 'min_samples_leaf': 30, 'max_features': None, 'criterion': 'entropy', 'splitter': 'random', 'class_weight': None, 'ccp_alpha': 1.0333896431462928e-08}. Best is trial 0 with value: 0.6937602640477005.
[I 2026-08-26 14:04:26,388] Trial 9 finished with value: 0.6797916911263687 and parameters: {'max_depth': 16, 'min_samples_split': 99, 'min_samples_leaf': 20, 'max_features': 'sqrt', 'criterion': 'gini', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 1.3685182782317289e-05}. Best is trial 0 with value: 0.6937602640477005.
[I 2026-08-26 14:04:26,497] Trial 10 finished with value: 0.5906330677733533 and parameters: {'max_depth': 3, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 0.6, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 1.3312110800515346e-09}. Best is trial 0 with value: 0.6937602640477005.
[I 2026-08-26 14:04:26,629] Trial 11 finished with value: 0.6722903739955449 and parameters: {'max_depth': 10, 'min_samples_split': 59, 'min_samples_leaf': 50, 'max_features': 0.4, 'criterion': 'gini', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 1.993338966151073e-05}. Best is trial 0 with value: 0.6937602640477005.
[I 2026-08-26 14:04:26,878] Trial 12 finished with value: 0.7018212865721295 and parameters: {'max_depth': 12, 'min_samples_split': 35, 'min_samples_leaf': 48, 'max_features': 0.6, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 4.8231736633537e-06}. Best is trial 12 with value: 0.7018212865721295.
[I 2026-08-26 14:04:27,116] Trial 13 finished with value: 0.6860303275248534 and parameters: {'max_depth': 9, 'min_samples_split': 23, 'min_samples_leaf': 43, 'max_features': 0.6, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 6.878618899006824e-07}. Best is trial 12 with value: 0.7018212865721295.
[I 2026-08-26 14:04:27,322] Trial 14 finished with value: 0.6473909760702135 and parameters: {'max_depth': 7, 'min_samples_split': 31, 'min_samples_leaf': 40, 'max_features': 0.6, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 1.579941230102522e-06}. Best is trial 12 with value: 0.7018212865721295.
[I 2026-08-26 14:04:27,554] Trial 15 finished with value: 0.693143776312425 and parameters: {'max_depth': 14, 'min_samples_split': 5, 'min_samples_leaf': 58, 'max_features': 0.6, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 1.5390005185388046e-08}. Best is trial 12 with value: 0.7018212865721295.
[I 2026-08-26 14:04:27,784] Trial 16 finished with value: 0.6897163498012705 and parameters: {'max_depth': 22, 'min_samples_split': 18, 'min_samples_leaf': 64, 'max_features': 0.6, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 2.5049378265574325e-06}. Best is trial 12 with value: 0.7018212865721295.
[I 2026-08-26 14:04:27,947] Trial 17 finished with value: 0.7128207366431222 and parameters: {'max_depth': 24, 'min_samples_split': 39, 'min_samples_leaf': 39, 'max_features': 0.4, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 0.00012124487282954174}. Best is trial 17 with value: 0.7128207366431222.
[I 2026-08-26 14:04:27,970] Trial 18 finished with value: 0.641017014984764 and parameters: {'max_depth': 23, 'min_samples_split': 38, 'min_samples_leaf': 36, 'max_features': 0.4, 'criterion': 'log_loss', 'splitter': 'random', 'class_weight': 'balanced', 'ccp_alpha': 0.00022582887117893365}. Best is trial 17 with value: 0.7128207366431222.
[I 2026-08-26 14:04:28,066] Trial 19 finished with value: 0.7163798953213586 and parameters: {'max_depth': 30, 'min_samples_split': 60, 'min_samples_leaf': 15, 'max_features': 'log2', 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 0.00011720400246717735}. Best is trial 19 with value: 0.7163798953213586.
[I 2026-08-26 14:04:28,163] Trial 20 finished with value: 0.7174201824872711 and parameters: {'max_depth': 30, 'min_samples_split': 61, 'min_samples_leaf': 8, 'max_features': 'log2', 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 0.00012625695634811774}. Best is trial 20 with value: 0.7174201824872711.
[I 2026-08-26 14:04:28,261] Trial 21 finished with value: 0.7132931179610572 and parameters: {'max_depth': 30, 'min_samples_split': 59, 'min_samples_leaf': 11, 'max_features': 'log2', 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 0.0001456576587254279}. Best is trial 20 with value: 0.7174201824872711.
[I 2026-08-26 14:04:28,361] Trial 22 finished with value: 0.7119191364441064 and parameters: {'max_depth': 30, 'min_samples_split': 60, 'min_samples_leaf': 10, 'max_features': 'log2', 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 0.0006670043202620436}. Best is trial 20 with value: 0.7174201824872711.
[I 2026-08-26 14:04:28,459] Trial 23 finished with value: 0.7181528663677101 and parameters: {'max_depth': 27, 'min_samples_split': 63, 'min_samples_leaf': 12, 'max_features': 'log2', 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 8.832709162977383e-05}. Best is trial 23 with value: 0.7181528663677101.
[I 2026-08-26 14:04:28,555] Trial 24 finished with value: 0.7024222179092167 and parameters: {'max_depth': 26, 'min_samples_split': 70, 'min_samples_leaf': 14, 'max_features': 'log2', 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 6.359877471168925e-05}. Best is trial 23 with value: 0.7181528663677101.
[I 2026-08-26 14:04:28,658] Trial 25 finished with value: 0.7275489254351984 and parameters: {'max_depth': 28, 'min_samples_split': 50, 'min_samples_leaf': 4, 'max_features': 'log2', 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 0.000929121784244444}. Best is trial 25 with value: 0.7275489254351984.
[I 2026-08-26 14:04:28,680] Trial 26 finished with value: 0.6637715979865761 and parameters: {'max_depth': 27, 'min_samples_split': 54, 'min_samples_leaf': 2, 'max_features': 'log2', 'criterion': 'log_loss', 'splitter': 'random', 'class_weight': 'balanced', 'ccp_alpha': 0.0011289972782743858}. Best is trial 25 with value: 0.7275489254351984.
[I 2026-08-26 14:04:28,780] Trial 27 finished with value: 0.6984646207275748 and parameters: {'max_depth': 20, 'min_samples_split': 47, 'min_samples_leaf': 6, 'max_features': 'log2', 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 0.0023506076504133115}. Best is trial 25 with value: 0.7275489254351984.
[I 2026-08-26 14:04:28,874] Trial 28 finished with value: 0.7014861397788359 and parameters: {'max_depth': 27, 'min_samples_split': 68, 'min_samples_leaf': 17, 'max_features': 'log2', 'criterion': 'entropy', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 0.0004991731157925871}. Best is trial 25 with value: 0.7275489254351984.
[I 2026-08-26 14:04:28,961] Trial 29 finished with value: 0.6990885586405406 and parameters: {'max_depth': 27, 'min_samples_split': 86, 'min_samples_leaf': 7, 'max_features': 'log2', 'criterion': 'gini', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 4.396971508374943e-05}. Best is trial 25 with value: 0.7275489254351984.
[I 2026-08-26 14:04:29,054] Trial 30 finished with value: 0.6974430072402062 and parameters: {'max_depth': 20, 'min_samples_split': 49, 'min_samples_leaf': 30, 'max_features': 'log2', 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 9.815473246667535e-06}. Best is trial 25 with value: 0.7275489254351984.
[I 2026-08-26 14:04:29,148] Trial 31 finished with value: 0.7074307241903239 and parameters: {'max_depth': 28, 'min_samples_split': 64, 'min_samples_leaf': 14, 'max_features': 'log2', 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 7.689603115223e-05}. Best is trial 25 with value: 0.7275489254351984.
[I 2026-08-26 14:04:29,514] Trial 32 finished with value: 0.6332752910108372 and parameters: {'max_depth': 25, 'min_samples_split': 56, 'min_samples_leaf': 20, 'max_features': 0.8, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 0.008145814427780637}. Best is trial 25 with value: 0.7275489254351984.
[I 2026-08-26 14:04:29,617] Trial 33 finished with value: 0.7325026203156291 and parameters: {'max_depth': 29, 'min_samples_split': 44, 'min_samples_leaf': 6, 'max_features': 'log2', 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 0.00033887950518049666}. Best is trial 33 with value: 0.7325026203156291.
[I 2026-08-26 14:04:29,639] Trial 34 finished with value: 0.6754371987355676 and parameters: {'max_depth': 28, 'min_samples_split': 42, 'min_samples_leaf': 7, 'max_features': 'log2', 'criterion': 'log_loss', 'splitter': 'random', 'class_weight': 'balanced', 'ccp_alpha': 0.0002850976164068334}. Best is trial 33 with value: 0.7325026203156291.
[I 2026-08-26 14:04:30,078] Trial 35 finished with value: 0.7179075811839337 and parameters: {'max_depth': 29, 'min_samples_split': 28, 'min_samples_leaf': 25, 'max_features': None, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 0.00403137232595888}. Best is trial 33 with value: 0.7325026203156291.
[I 2026-08-26 14:04:30,521] Trial 36 finished with value: 0.7251081622400296 and parameters: {'max_depth': 21, 'min_samples_split': 28, 'min_samples_leaf': 24, 'max_features': None, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 0.0036221526885801838}. Best is trial 33 with value: 0.7325026203156291.
[I 2026-08-26 14:04:30,558] Trial 37 finished with value: 0.6448748072771755 and parameters: {'max_depth': 21, 'min_samples_split': 19, 'min_samples_leaf': 22, 'max_features': None, 'criterion': 'gini', 'splitter': 'random', 'class_weight': None, 'ccp_alpha': 0.0009918830683616614}. Best is trial 33 with value: 0.7325026203156291.
[I 2026-08-26 14:04:30,994] Trial 38 finished with value: 0.7237387317348697 and parameters: {'max_depth': 25, 'min_samples_split': 43, 'min_samples_leaf': 29, 'max_features': None, 'criterion': 'entropy', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 0.003228851046590318}. Best is trial 33 with value: 0.7325026203156291.
[I 2026-08-26 14:04:31,417] Trial 39 finished with value: 0.5756029403242646 and parameters: {'max_depth': 25, 'min_samples_split': 45, 'min_samples_leaf': 28, 'max_features': None, 'criterion': 'entropy', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 0.009946448151624675}. Best is trial 33 with value: 0.7325026203156291.
[I 2026-08-26 14:04:31,446] Trial 40 finished with value: 0.6200588143265015 and parameters: {'max_depth': 19, 'min_samples_split': 30, 'min_samples_leaf': 80, 'max_features': None, 'criterion': 'entropy', 'splitter': 'random', 'class_weight': 'balanced', 'ccp_alpha': 0.0023298086174905093}. Best is trial 33 with value: 0.7325026203156291.
[I 2026-08-26 14:04:31,873] Trial 41 finished with value: 0.7110346434915303 and parameters: {'max_depth': 24, 'min_samples_split': 49, 'min_samples_leaf': 33, 'max_features': None, 'criterion': 'entropy', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 0.003748709272237722}. Best is trial 33 with value: 0.7325026203156291.
[I 2026-08-26 14:04:31,972] Trial 42 finished with value: 0.7183472400141767 and parameters: {'max_depth': 22, 'min_samples_split': 42, 'min_samples_leaf': 18, 'max_features': 'sqrt', 'criterion': 'entropy', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 0.0004844348603498636}. Best is trial 33 with value: 0.7325026203156291.
[I 2026-08-26 14:04:32,072] Trial 43 finished with value: 0.7215563532856636 and parameters: {'max_depth': 19, 'min_samples_split': 43, 'min_samples_leaf': 18, 'max_features': 'sqrt', 'criterion': 'entropy', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 0.0004485476097564535}. Best is trial 33 with value: 0.7325026203156291.
[I 2026-08-26 14:04:32,177] Trial 44 finished with value: 0.7314235987617683 and parameters: {'max_depth': 18, 'min_samples_split': 35, 'min_samples_leaf': 3, 'max_features': 'sqrt', 'criterion': 'entropy', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 0.0015301683999290757}. Best is trial 33 with value: 0.7325026203156291.
[I 2026-08-26 14:04:32,283] Trial 45 finished with value: 0.6439130331837264 and parameters: {'max_depth': 15, 'min_samples_split': 36, 'min_samples_leaf': 3, 'max_features': 'sqrt', 'criterion': 'entropy', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 0.0034630221943211825}. Best is trial 33 with value: 0.7325026203156291.
[I 2026-08-26 14:04:32,770] Trial 46 finished with value: 0.7852679170121849 and parameters: {'max_depth': 25, 'min_samples_split': 25, 'min_samples_leaf': 4, 'max_features': None, 'criterion': 'entropy', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 0.0016544763040507997}. Best is trial 46 with value: 0.7852679170121849.
[I 2026-08-26 14:04:33,181] Trial 47 finished with value: 0.8019591164866124 and parameters: {'max_depth': 23, 'min_samples_split': 10, 'min_samples_leaf': 4, 'max_features': 0.8, 'criterion': 'entropy', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 0.0012586759075589157}. Best is trial 47 with value: 0.8019591164866124.
[I 2026-08-26 14:04:33,589] Trial 48 finished with value: 0.7955912224736958 and parameters: {'max_depth': 23, 'min_samples_split': 12, 'min_samples_leaf': 4, 'max_features': 0.8, 'criterion': 'entropy', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 0.0013073405797630762}. Best is trial 47 with value: 0.8019591164866124.
[I 2026-08-26 14:04:34,009] Trial 49 finished with value: 0.7966373813786604 and parameters: {'max_depth': 18, 'min_samples_split': 11, 'min_samples_leaf': 1, 'max_features': 0.8, 'criterion': 'entropy', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 0.0013158045586943378}. Best is trial 47 with value: 0.8019591164866124.
[I 2026-08-26 14:04:34,423] Trial 50 finished with value: 0.8132701631500806 and parameters: {'max_depth': 23, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 0.8, 'criterion': 'entropy', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 0.0002856408713718199}. Best is trial 50 with value: 0.8132701631500806.
[I 2026-08-26 14:04:34,837] Trial 51 finished with value: 0.8133978770708981 and parameters: {'max_depth': 23, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 0.8, 'criterion': 'entropy', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 0.00023859430773192898}. Best is trial 51 with value: 0.8133978770708981.
[I 2026-08-26 14:04:35,251] Trial 52 finished with value: 0.8135243379530968 and parameters: {'max_depth': 24, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 0.8, 'criterion': 'entropy', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 0.00020883664120967678}. Best is trial 52 with value: 0.8135243379530968.
[I 2026-08-26 14:04:35,674] Trial 53 finished with value: 0.8078616893720978 and parameters: {'max_depth': 23, 'min_samples_split': 11, 'min_samples_leaf': 1, 'max_features': 0.8, 'criterion': 'entropy', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 3.906008703184941e-05}. Best is trial 52 with value: 0.8135243379530968.
[I 2026-08-26 14:04:36,094] Trial 54 finished with value: 0.8099884264657632 and parameters: {'max_depth': 23, 'min_samples_split': 9, 'min_samples_leaf': 1, 'max_features': 0.8, 'criterion': 'entropy', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 3.533440156262541e-05}. Best is trial 52 with value: 0.8135243379530968.
[I 2026-08-26 14:04:36,520] Trial 55 finished with value: 0.8116198004774196 and parameters: {'max_depth': 23, 'min_samples_split': 8, 'min_samples_leaf': 1, 'max_features': 0.8, 'criterion': 'entropy', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 9.064468712937647e-06}. Best is trial 52 with value: 0.8135243379530968.
[I 2026-08-26 14:04:36,910] Trial 56 finished with value: 0.7828857287775803 and parameters: {'max_depth': 22, 'min_samples_split': 6, 'min_samples_leaf': 10, 'max_features': 0.8, 'criterion': 'entropy', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 2.6208098333609346e-05}. Best is trial 52 with value: 0.8135243379530968.
[I 2026-08-26 14:04:36,955] Trial 57 finished with value: 0.7454107278794483 and parameters: {'max_depth': 23, 'min_samples_split': 17, 'min_samples_leaf': 1, 'max_features': 0.8, 'criterion': 'entropy', 'splitter': 'random', 'class_weight': None, 'ccp_alpha': 1.2788537019841253e-05}. Best is trial 52 with value: 0.8135243379530968.
[I 2026-08-26 14:04:37,350] Trial 58 finished with value: 0.7903343054691847 and parameters: {'max_depth': 21, 'min_samples_split': 4, 'min_samples_leaf': 9, 'max_features': 0.8, 'criterion': 'entropy', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 6.104173321168967e-06}. Best is trial 52 with value: 0.8135243379530968.

  geneva: tuning Random Forest (200 trials).

[I 2026-08-26 14:05:40,722] Trial 0 finished with value: 0.8357399479313574 and parameters: {'n_estimators': 300, 'max_depth': 32, 'min_samples_split': 3, 'min_samples_leaf': 15, 'max_features': 0.7, 'bootstrap': True, 'criterion': 'log_loss', 'class_weight': None}. Best is trial 0 with value: 0.8357399479313574.
[I 2026-08-26 14:05:45,385] Trial 1 finished with value: 0.8185042100691302 and parameters: {'n_estimators': 600, 'max_depth': 16, 'min_samples_split': 20, 'min_samples_leaf': 13, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'gini', 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8357399479313574.
[I 2026-08-26 14:06:00,097] Trial 2 finished with value: 0.7616070189226948 and parameters: {'n_estimators': 600, 'max_depth': 8, 'min_samples_split': 28, 'min_samples_leaf': 15, 'max_features': 0.7, 'bootstrap': True, 'criterion': 'entropy', 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8357399479313574.
[I 2026-08-26 14:06:11,341] Trial 3 finished with value: 0.8211589898301673 and parameters: {'n_estimators': 800, 'max_depth': 24, 'min_samples_split': 25, 'min_samples_leaf': 20, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'log_loss', 'class_weight': None}. Best is trial 0 with value: 0.8357399479313574.
[I 2026-08-26 14:06:20,458] Trial 4 finished with value: 0.8042999348777651 and parameters: {'n_estimators': 1000, 'max_depth': 16, 'min_samples_split': 31, 'min_samples_leaf': 15, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy', 'class_weight': None}. Best is trial 0 with value: 0.8357399479313574.
[I 2026-08-26 14:06:34,703] Trial 5 finished with value: 0.8800443502340224 and parameters: {'n_estimators': 800, 'max_depth': 48, 'min_samples_split': 18, 'min_samples_leaf': 3, 'max_features': 0.3, 'bootstrap': False, 'criterion': 'gini', 'class_weight': 'balanced'}. Best is trial 5 with value: 0.8800443502340224.
[I 2026-08-26 14:06:44,512] Trial 6 finished with value: 0.856957075286575 and parameters: {'n_estimators': 400, 'max_depth': 48, 'min_samples_split': 34, 'min_samples_leaf': 1, 'max_features': 0.5, 'bootstrap': True, 'criterion': 'entropy', 'class_weight': 'balanced'}. Best is trial 5 with value: 0.8800443502340224.
[I 2026-08-26 14:07:05,605] Trial 7 finished with value: 0.8549673549939657 and parameters: {'n_estimators': 1000, 'max_depth': 32, 'min_samples_split': 19, 'min_samples_leaf': 15, 'max_features': 0.3, 'bootstrap': False, 'criterion': 'log_loss', 'class_weight': 'balanced'}. Best is trial 5 with value: 0.8800443502340224.
[I 2026-08-26 14:07:51,549] Trial 8 finished with value: 0.7702325867740885 and parameters: {'n_estimators': 900, 'max_depth': 24, 'min_samples_split': 40, 'min_samples_leaf': 19, 'max_features': 1.0, 'bootstrap': False, 'criterion': 'gini', 'class_weight': 'balanced_subsample'}. Best is trial 5 with value: 0.8800443502340224.
[I 2026-08-26 14:08:05,965] Trial 9 finished with value: 0.8956610039917106 and parameters: {'n_estimators': 600, 'max_depth': None, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 0.3, 'bootstrap': False, 'criterion': 'log_loss', 'class_weight': 'balanced_subsample'}. Best is trial 9 with value: 0.8956610039917106.
[I 2026-08-26 14:08:13,760] Trial 10 finished with value: 0.873632696321095 and parameters: {'n_estimators': 500, 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 7, 'max_features': 'log2', 'bootstrap': False, 'criterion': 'log_loss', 'class_weight': 'balanced_subsample'}. Best is trial 9 with value: 0.8956610039917106.
[I 2026-08-26 14:08:26,913] Trial 11 finished with value: 0.8900688913605356 and parameters: {'n_estimators': 700, 'max_depth': 48, 'min_samples_split': 12, 'min_samples_leaf': 1, 'max_features': 0.3, 'bootstrap': False, 'criterion': 'gini', 'class_weight': 'balanced_subsample'}. Best is trial 9 with value: 0.8956610039917106.
[I 2026-08-26 14:08:38,377] Trial 12 finished with value: 0.861304660215426 and parameters: {'n_estimators': 700, 'max_depth': 12, 'min_samples_split': 11, 'min_samples_leaf': 5, 'max_features': 0.3, 'bootstrap': False, 'criterion': 'gini', 'class_weight': 'balanced_subsample'}. Best is trial 9 with value: 0.8956610039917106.
[I 2026-08-26 14:08:52,719] Trial 13 finished with value: 0.8945006691068176 and parameters: {'n_estimators': 600, 'max_depth': None, 'min_samples_split': 11, 'min_samples_leaf': 1, 'max_features': 0.3, 'bootstrap': False, 'criterion': 'log_loss', 'class_weight': 'balanced_subsample'}. Best is trial 9 with value: 0.8956610039917106.
[I 2026-08-26 14:09:03,754] Trial 14 finished with value: 0.8775171632323225 and parameters: {'n_estimators': 500, 'max_depth': None, 'min_samples_split': 9, 'min_samples_leaf': 8, 'max_features': 0.3, 'bootstrap': False, 'criterion': 'log_loss', 'class_weight': 'balanced_subsample'}. Best is trial 9 with value: 0.8956610039917106.
[I 2026-08-26 14:09:23,954] Trial 15 finished with value: 0.8971446978109519 and parameters: {'n_estimators': 500, 'max_depth': None, 'min_samples_split': 7, 'min_samples_leaf': 4, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'log_loss', 'class_weight': 'balanced_subsample'}. Best is trial 15 with value: 0.8971446978109519.
[I 2026-08-26 14:09:35,641] Trial 16 finished with value: 0.8782034068750718 and parameters: {'n_estimators': 300, 'max_depth': None, 'min_samples_split': 6, 'min_samples_leaf': 9, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'log_loss', 'class_weight': 'balanced_subsample'}. Best is trial 15 with value: 0.8971446978109519.
[I 2026-08-26 14:09:51,792] Trial 17 finished with value: 0.8899079381272346 and parameters: {'n_estimators': 400, 'max_depth': None, 'min_samples_split': 16, 'min_samples_leaf': 4, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'log_loss', 'class_weight': 'balanced_subsample'}. Best is trial 15 with value: 0.8971446978109519.
[I 2026-08-26 14:09:57,723] Trial 18 finished with value: 0.761898176578695 and parameters: {'n_estimators': 500, 'max_depth': 8, 'min_samples_split': 7, 'min_samples_leaf': 6, 'max_features': 'log2', 'bootstrap': False, 'criterion': 'log_loss', 'class_weight': 'balanced_subsample'}. Best is trial 15 with value: 0.8971446978109519.
[I 2026-08-26 14:10:25,937] Trial 19 finished with value: 0.7778413210048133 and parameters: {'n_estimators': 400, 'max_depth': 12, 'min_samples_split': 15, 'min_samples_leaf': 10, 'max_features': 1.0, 'bootstrap': False, 'criterion': 'log_loss', 'class_weight': 'balanced_subsample'}. Best is trial 15 with value: 0.8971446978109519.
[I 2026-08-26 14:10:54,103] Trial 20 finished with value: 0.8971134299747853 and parameters: {'n_estimators': 700, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 3, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 15 with value: 0.8971446978109519.
[I 2026-08-26 14:11:22,315] Trial 21 finished with value: 0.8971134299747853 and parameters: {'n_estimators': 700, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 3, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 15 with value: 0.8971446978109519.
[I 2026-08-26 14:11:50,466] Trial 22 finished with value: 0.8971134299747853 and parameters: {'n_estimators': 700, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 3, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 15 with value: 0.8971446978109519.
[I 2026-08-26 14:12:22,219] Trial 23 finished with value: 0.894673007160188 and parameters: {'n_estimators': 800, 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 4, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 15 with value: 0.8971446978109519.
[I 2026-08-26 14:12:57,124] Trial 24 finished with value: 0.8885519996696223 and parameters: {'n_estimators': 900, 'max_depth': None, 'min_samples_split': 7, 'min_samples_leaf': 6, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 15 with value: 0.8971446978109519.
[I 2026-08-26 14:13:25,008] Trial 25 finished with value: 0.8908660226458581 and parameters: {'n_estimators': 700, 'max_depth': None, 'min_samples_split': 14, 'min_samples_leaf': 3, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 15 with value: 0.8971446978109519.
[I 2026-08-26 14:13:45,551] Trial 26 finished with value: 0.8530518933225739 and parameters: {'n_estimators': 900, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 10, 'max_features': 0.5, 'bootstrap': True, 'criterion': 'entropy', 'class_weight': None}. Best is trial 15 with value: 0.8971446978109519.
[I 2026-08-26 14:14:04,017] Trial 27 finished with value: 0.8725111299318847 and parameters: {'n_estimators': 500, 'max_depth': 12, 'min_samples_split': 7, 'min_samples_leaf': 5, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 15 with value: 0.8971446978109519.
[I 2026-08-26 14:14:35,051] Trial 28 finished with value: 0.880921392295144 and parameters: {'n_estimators': 800, 'max_depth': 16, 'min_samples_split': 22, 'min_samples_leaf': 3, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 15 with value: 0.8971446978109519.
[I 2026-08-26 14:14:44,631] Trial 29 finished with value: 0.8679824068398586 and parameters: {'n_estimators': 300, 'max_depth': 32, 'min_samples_split': 4, 'min_samples_leaf': 7, 'max_features': 0.7, 'bootstrap': True, 'criterion': 'entropy', 'class_weight': None}. Best is trial 15 with value: 0.8971446978109519.
[I 2026-08-26 14:15:04,999] Trial 30 finished with value: 0.7552079099686403 and parameters: {'n_estimators': 700, 'max_depth': 8, 'min_samples_split': 9, 'min_samples_leaf': 12, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 15 with value: 0.8971446978109519.
[I 2026-08-26 14:15:33,130] Trial 31 finished with value: 0.8971134299747853 and parameters: {'n_estimators': 700, 'max_depth': None, 'min_samples_split': 4, 'min_samples_leaf': 3, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 15 with value: 0.8971446978109519.
[I 2026-08-26 14:15:57,585] Trial 32 finished with value: 0.901184662791333 and parameters: {'n_estimators': 600, 'max_depth': None, 'min_samples_split': 4, 'min_samples_leaf': 2, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 32 with value: 0.901184662791333.
[I 2026-08-26 14:16:30,274] Trial 33 finished with value: 0.8957375676125819 and parameters: {'n_estimators': 600, 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 2, 'max_features': 0.7, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 32 with value: 0.901184662791333.
[I 2026-08-26 14:16:44,787] Trial 34 finished with value: 0.8709954731380822 and parameters: {'n_estimators': 600, 'max_depth': 32, 'min_samples_split': 13, 'min_samples_leaf': 5, 'max_features': 0.5, 'bootstrap': True, 'criterion': 'entropy', 'class_weight': None}. Best is trial 32 with value: 0.901184662791333.
[I 2026-08-26 14:16:54,619] Trial 35 finished with value: 0.887834964143998 and parameters: {'n_estimators': 600, 'max_depth': 24, 'min_samples_split': 8, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 32 with value: 0.901184662791333.
[I 2026-08-26 14:16:59,907] Trial 36 finished with value: 0.8656449307687304 and parameters: {'n_estimators': 500, 'max_depth': 16, 'min_samples_split': 4, 'min_samples_leaf': 4, 'max_features': 'log2', 'bootstrap': True, 'criterion': 'entropy', 'class_weight': 'balanced'}. Best is trial 32 with value: 0.901184662791333.
[I 2026-08-26 14:17:49,014] Trial 37 finished with value: 0.8126006046471937 and parameters: {'n_estimators': 800, 'max_depth': None, 'min_samples_split': 9, 'min_samples_leaf': 2, 'max_features': 1.0, 'bootstrap': False, 'criterion': 'gini', 'class_weight': None}. Best is trial 32 with value: 0.901184662791333.
[I 2026-08-26 14:17:56,105] Trial 38 finished with value: 0.7610951683880268 and parameters: {'n_estimators': 600, 'max_depth': 8, 'min_samples_split': 17, 'min_samples_leaf': 5, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'entropy', 'class_weight': 'balanced'}. Best is trial 32 with value: 0.901184662791333.
[I 2026-08-26 14:18:05,710] Trial 39 finished with value: 0.8690440000638343 and parameters: {'n_estimators': 400, 'max_depth': 24, 'min_samples_split': 6, 'min_samples_leaf': 6, 'max_features': 0.5, 'bootstrap': True, 'criterion': 'entropy', 'class_weight': None}. Best is trial 32 with value: 0.901184662791333.
[I 2026-08-26 14:18:34,589] Trial 40 finished with value: 0.8745046159936525 and parameters: {'n_estimators': 700, 'max_depth': 48, 'min_samples_split': 22, 'min_samples_leaf': 2, 'max_features': 0.7, 'bootstrap': False, 'criterion': 'gini', 'class_weight': None}. Best is trial 32 with value: 0.901184662791333.
[I 2026-08-26 14:19:02,331] Trial 41 finished with value: 0.8942616052961083 and parameters: {'n_estimators': 700, 'max_depth': None, 'min_samples_split': 3, 'min_samples_leaf': 4, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 32 with value: 0.901184662791333.
[I 2026-08-26 14:19:34,301] Trial 42 finished with value: 0.898095845118951 and parameters: {'n_estimators': 800, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 3, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 32 with value: 0.901184662791333.
[I 2026-08-26 14:20:02,471] Trial 43 finished with value: 0.8467215510157482 and parameters: {'n_estimators': 800, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 18, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 32 with value: 0.901184662791333.
[I 2026-08-26 14:20:39,637] Trial 44 finished with value: 0.8989801628848918 and parameters: {'n_estimators': 900, 'max_depth': None, 'min_samples_split': 11, 'min_samples_leaf': 1, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': 'balanced'}. Best is trial 32 with value: 0.901184662791333.
[I 2026-08-26 14:21:16,614] Trial 45 finished with value: 0.8978857519026923 and parameters: {'n_estimators': 900, 'max_depth': None, 'min_samples_split': 12, 'min_samples_leaf': 1, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': 'balanced'}. Best is trial 32 with value: 0.901184662791333.
[I 2026-08-26 14:21:57,053] Trial 46 finished with value: 0.8943132753948635 and parameters: {'n_estimators': 1000, 'max_depth': 16, 'min_samples_split': 13, 'min_samples_leaf': 1, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'log_loss', 'class_weight': 'balanced'}. Best is trial 32 with value: 0.901184662791333.
[I 2026-08-26 14:23:07,342] Trial 47 finished with value: 0.8237747565972802 and parameters: {'n_estimators': 900, 'max_depth': None, 'min_samples_split': 11, 'min_samples_leaf': 1, 'max_features': 1.0, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': 'balanced'}. Best is trial 32 with value: 0.901184662791333.
[I 2026-08-26 14:23:22,255] Trial 48 finished with value: 0.887870728958303 and parameters: {'n_estimators': 900, 'max_depth': 48, 'min_samples_split': 10, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'log_loss', 'class_weight': 'balanced'}. Best is trial 32 with value: 0.901184662791333.
[I 2026-08-26 14:23:34,599] Trial 49 finished with value: 0.8577614062438308 and parameters: {'n_estimators': 1000, 'max_depth': 32, 'min_samples_split': 36, 'min_samples_leaf': 1, 'max_features': 'log2', 'bootstrap': False, 'criterion': 'gini', 'class_weight': 'balanced'}. Best is trial 32 with value: 0.901184662791333.
[I 2026-08-26 14:23:57,087] Trial 50 finished with value: 0.8779153954493649 and parameters: {'n_estimators': 900, 'max_depth': None, 'min_samples_split': 15, 'min_samples_leaf': 2, 'max_features': 0.5, 'bootstrap': True, 'criterion': 'log_loss', 'class_weight': 'balanced'}. Best is trial 32 with value: 0.901184662791333.
[I 2026-08-26 14:24:29,288] Trial 51 finished with value: 0.8972668936713966 and parameters: {'n_estimators': 800, 'max_depth': None, 'min_samples_split': 8, 'min_samples_leaf': 4, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': 'balanced'}. Best is trial 32 with value: 0.901184662791333.
[I 2026-08-26 14:25:01,543] Trial 52 finished with value: 0.8972668936713966 and parameters: {'n_estimators': 800, 'max_depth': None, 'min_samples_split': 8, 'min_samples_leaf': 4, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': 'balanced'}. Best is trial 32 with value: 0.901184662791333.
[I 2026-08-26 14:25:33,553] Trial 53 finished with value: 0.8950116676024159 and parameters: {'n_estimators': 800, 'max_depth': None, 'min_samples_split': 11, 'min_samples_leaf': 4, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': 'balanced'}. Best is trial 32 with value: 0.901184662791333.
[I 2026-08-26 14:26:10,501] Trial 54 finished with value: 0.8985660229871903 and parameters: {'n_estimators': 900, 'max_depth': None, 'min_samples_split': 9, 'min_samples_leaf': 2, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': 'balanced'}. Best is trial 32 with value: 0.901184662791333.
[I 2026-08-26 14:26:44,030] Trial 55 finished with value: 0.8613775825595189 and parameters: {'n_estimators': 900, 'max_depth': 12, 'min_samples_split': 29, 'min_samples_leaf': 1, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': 'balanced'}. Best is trial 32 with value: 0.901184662791333.
[I 2026-08-26 14:27:24,856] Trial 56 finished with value: 0.895975415942267 and parameters: {'n_estimators': 1000, 'max_depth': None, 'min_samples_split': 12, 'min_samples_leaf': 2, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': 'balanced'}. Best is trial 32 with value: 0.901184662791333.
[I 2026-08-26 14:28:01,810] Trial 57 finished with value: 0.8927172063548989 and parameters: {'n_estimators': 900, 'max_depth': None, 'min_samples_split': 18, 'min_samples_leaf': 1, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': 'balanced'}. Best is trial 32 with value: 0.901184662791333.
[I 2026-08-26 14:28:22,272] Trial 58 finished with value: 0.8902314703703389 and parameters: {'n_estimators': 900, 'max_depth': 24, 'min_samples_split': 9, 'min_samples_leaf': 5, 'max_features': 0.3, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': 'balanced'}. Best is trial 32 with value: 0.901184662791333.
[I 2026-08-26 14:29:02,436] Trial 59 finished with value: 0.8945734693632363 and parameters: {'n_estimators': 1000, 'max_depth': None, 'min_samples_split': 13, 'min_samples_leaf': 3, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': 'balanced'}. Best is trial 32 with value: 0.901184662791333.
[I 2026-08-26 14:30:01,632] Trial 60 finished with value: 0.8112967658214612 and parameters: {'n_estimators': 800, 'max_depth': None, 'min_samples_split': 15, 'min_samples_leaf': 7, 'max_features': 1.0, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': 'balanced'}. Best is trial 32 with value: 0.901184662791333.
[I 2026-08-26 14:30:33,815] Trial 61 finished with value: 0.8972668936713966 and parameters: {'n_estimators': 800, 'max_depth': None, 'min_samples_split': 8, 'min_samples_leaf': 4, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': 'balanced'}. Best is trial 32 with value: 0.901184662791333.

  geneva: tuning XGBoost (200 trials).

[I 2026-08-26 15:58:57,281] Trial 0 finished with value: 0.8822628938173069 and parameters: {'max_depth': 9, 'learning_rate': 0.019677977348166304, 'subsample': 0.8978561926718072, 'colsample_bytree': 0.7442003345025142, 'min_child_weight': 2.1771032186203514, 'gamma': 1.8277151418544553, 'reg_alpha': 8.665537597324885e-06, 'reg_lambda': 1.0311514495138399}. Best is trial 0 with value: 0.8822628938173069.
[I 2026-08-26 15:59:09,374] Trial 1 finished with value: 0.894385703465716 and parameters: {'max_depth': 7, 'learning_rate': 0.09439831569936806, 'subsample': 0.9842104900822669, 'colsample_bytree': 0.7826484435755748, 'min_child_weight': 2.880043790954131, 'gamma': 0.3403911033599112, 'reg_alpha': 1.5100408408589772e-07, 'reg_lambda': 23.538263110950048}. Best is trial 1 with value: 0.894385703465716.
[I 2026-08-26 15:59:21,849] Trial 2 finished with value: 0.9023619060883409 and parameters: {'max_depth': 10, 'learning_rate': 0.14726161255504092, 'subsample': 0.8585642249613574, 'colsample_bytree': 0.6855299248522434, 'min_child_weight': 6.781935357780796, 'gamma': 0.41743875595471047, 'reg_alpha': 3.864031899313156e-05, 'reg_lambda': 14.610499699549097}. Best is trial 2 with value: 0.9023619060883409.
[I 2026-08-26 15:59:33,945] Trial 3 finished with value: 0.8928310242206132 and parameters: {'max_depth': 5, 'learning_rate': 0.08394754752250128, 'subsample': 0.9450697344147837, 'colsample_bytree': 0.6595392252176876, 'min_child_weight': 5.011643571251018, 'gamma': 0.4774657914394431, 'reg_alpha': 5.357340695323986e-08, 'reg_lambda': 0.18099954688158187}. Best is trial 2 with value: 0.9023619060883409.
[I 2026-08-26 15:59:46,382] Trial 4 finished with value: 0.8584298850338492 and parameters: {'max_depth': 4, 'learning_rate': 0.048769840070943336, 'subsample': 0.9178299664912868, 'colsample_bytree': 0.9963290723923126, 'min_child_weight': 13.502442798764482, 'gamma': 1.1322462171492673, 'reg_alpha': 0.00014367270092871558, 'reg_lambda': 0.1399264351773497}. Best is trial 2 with value: 0.9023619060883409.
[I 2026-08-26 16:00:01,703] Trial 5 finished with value: 0.8397212584429357 and parameters: {'max_depth': 8, 'learning_rate': 0.018099146987238985, 'subsample': 0.953044632771952, 'colsample_bytree': 0.8904231274266234, 'min_child_weight': 15.164258427643505, 'gamma': 2.130692051488852, 'reg_alpha': 0.009425386803829051, 'reg_lambda': 20.136195700340338}. Best is trial 2 with value: 0.9023619060883409.
[I 2026-08-26 16:00:24,596] Trial 6 finished with value: 0.8712380060214496 and parameters: {'max_depth': 10, 'learning_rate': 0.01918354750824495, 'subsample': 0.782598566894961, 'colsample_bytree': 0.7970893967426577, 'min_child_weight': 0.7811624819629674, 'gamma': 0.46120338258524907, 'reg_alpha': 6.963704487425356, 'reg_lambda': 0.47063847559435423}. Best is trial 2 with value: 0.9023619060883409.
[I 2026-08-26 16:00:42,297] Trial 7 finished with value: 0.8882129209955373 and parameters: {'max_depth': 10, 'learning_rate': 0.022953302153308094, 'subsample': 0.6529433178954122, 'colsample_bytree': 0.7269413610677277, 'min_child_weight': 1.7604099383967902, 'gamma': 1.266165560263202, 'reg_alpha': 2.041568273325791e-06, 'reg_lambda': 2.5538276254965817}. Best is trial 2 with value: 0.9023619060883409.
[I 2026-08-26 16:00:59,900] Trial 8 finished with value: 0.8816776424700852 and parameters: {'max_depth': 3, 'learning_rate': 0.11851328676362981, 'subsample': 0.7074625481911713, 'colsample_bytree': 0.9645659651689448, 'min_child_weight': 20.063522776432464, 'gamma': 0.047573401053791486, 'reg_alpha': 0.34420918881100815, 'reg_lambda': 4.715832950352583}. Best is trial 2 with value: 0.9023619060883409.
[I 2026-08-26 16:01:11,704] Trial 9 finished with value: 0.7819758328621575 and parameters: {'max_depth': 3, 'learning_rate': 0.033391708755025735, 'subsample': 0.8256997968048689, 'colsample_bytree': 0.837631051781117, 'min_child_weight': 8.12005959578132, 'gamma': 1.8972954750065205, 'reg_alpha': 2.437950567013768, 'reg_lambda': 6.697837558293906}. Best is trial 2 with value: 0.9023619060883409.
[I 2026-08-26 16:01:19,247] Trial 10 finished with value: 0.8413298698671238 and parameters: {'max_depth': 6, 'learning_rate': 0.17115128841996644, 'subsample': 0.8154186866999962, 'colsample_bytree': 0.6025554256995838, 'min_child_weight': 0.8625345056254972, 'gamma': 2.9869578392012968, 'reg_alpha': 1.239446148413562e-09, 'reg_lambda': 0.9684799729031198}. Best is trial 2 with value: 0.9023619060883409.
[I 2026-08-26 16:01:51,221] Trial 11 finished with value: 0.9084935370079652 and parameters: {'max_depth': 7, 'learning_rate': 0.07963679092664983, 'subsample': 0.9782175947325363, 'colsample_bytree': 0.7080525776861748, 'min_child_weight': 4.263452155975748, 'gamma': 0.0231232521247709, 'reg_alpha': 0.0003004717544533422, 'reg_lambda': 26.482920034602543}. Best is trial 11 with value: 0.9084935370079652.
[I 2026-08-26 16:02:03,617] Trial 12 finished with value: 0.8845161759578714 and parameters: {'max_depth': 8, 'learning_rate': 0.0585450019205184, 'subsample': 0.8754617904374793, 'colsample_bytree': 0.6782743329282878, 'min_child_weight': 5.621485435738427, 'gamma': 0.9246854180884267, 'reg_alpha': 0.0009910433108845519, 'reg_lambda': 11.18104428147794}. Best is trial 11 with value: 0.9084935370079652.
[I 2026-08-26 16:02:19,023] Trial 13 finished with value: 0.9042596223315856 and parameters: {'max_depth': 6, 'learning_rate': 0.19738799740979307, 'subsample': 0.7471784805954584, 'colsample_bytree': 0.6725320077667093, 'min_child_weight': 3.8908230822550127, 'gamma': 0.0874654369563248, 'reg_alpha': 0.01542774835998499, 'reg_lambda': 28.40799586072418}. Best is trial 11 with value: 0.9084935370079652.
[I 2026-08-26 16:02:49,817] Trial 14 finished with value: 0.9019333688436142 and parameters: {'max_depth': 6, 'learning_rate': 0.06690526775980236, 'subsample': 0.6153035209350135, 'colsample_bytree': 0.6067985020666221, 'min_child_weight': 3.4409161251561335, 'gamma': 0.06281619047092823, 'reg_alpha': 0.028821948481089064, 'reg_lambda': 29.79320282769025}. Best is trial 11 with value: 0.9084935370079652.
[I 2026-08-26 16:03:00,465] Trial 15 finished with value: 0.8927188199124375 and parameters: {'max_depth': 6, 'learning_rate': 0.19552025796695158, 'subsample': 0.7381684507383188, 'colsample_bytree': 0.7162113834683212, 'min_child_weight': 1.5238549913116142, 'gamma': 0.8176019870032434, 'reg_alpha': 0.0044186419258787895, 'reg_lambda': 8.471808259523181}. Best is trial 11 with value: 0.9084935370079652.
[I 2026-08-26 16:03:34,752] Trial 16 finished with value: 0.9041703685348068 and parameters: {'max_depth': 7, 'learning_rate': 0.03967552663790742, 'subsample': 0.7019973020575317, 'colsample_bytree': 0.6454066471769822, 'min_child_weight': 9.827433159084407, 'gamma': 0.022210797407799604, 'reg_alpha': 0.11991651861512725, 'reg_lambda': 3.0448988685029024}. Best is trial 11 with value: 0.9084935370079652.
[I 2026-08-26 16:03:44,282] Trial 17 finished with value: 0.8453281309708849 and parameters: {'max_depth': 5, 'learning_rate': 0.12516543455198414, 'subsample': 0.9951193607803736, 'colsample_bytree': 0.758827649993029, 'min_child_weight': 29.38805037408496, 'gamma': 0.765566598885689, 'reg_alpha': 9.298132346477619e-05, 'reg_lambda': 12.515087970033553}. Best is trial 11 with value: 0.9084935370079652.
[I 2026-08-26 16:03:55,371] Trial 18 finished with value: 0.866389348491456 and parameters: {'max_depth': 7, 'learning_rate': 0.09225532085375182, 'subsample': 0.7696987572334235, 'colsample_bytree': 0.8314618346028646, 'min_child_weight': 3.897863418148991, 'gamma': 1.4105893916491228, 'reg_alpha': 0.0015807637315907734, 'reg_lambda': 29.853985807567263}. Best is trial 11 with value: 0.9084935370079652.
[I 2026-08-26 16:04:17,210] Trial 19 finished with value: 0.8934667296332485 and parameters: {'max_depth': 5, 'learning_rate': 0.02769088718221053, 'subsample': 0.6554870713977182, 'colsample_bytree': 0.6413910206120615, 'min_child_weight': 1.1009764936879791, 'gamma': 0.6459090593224095, 'reg_alpha': 0.3214791517081728, 'reg_lambda': 5.130986908864023}. Best is trial 11 with value: 0.9084935370079652.
[I 2026-08-26 16:04:36,571] Trial 20 finished with value: 0.9081996281391964 and parameters: {'max_depth': 8, 'learning_rate': 0.065983752373723, 'subsample': 0.8417010098217245, 'colsample_bytree': 0.69976923741993, 'min_child_weight': 2.63905904725469, 'gamma': 0.25344958514561045, 'reg_alpha': 0.0004593312895991956, 'reg_lambda': 15.794576869776742}. Best is trial 11 with value: 0.9084935370079652.
[I 2026-08-26 16:04:55,088] Trial 21 finished with value: 0.9085799477033266 and parameters: {'max_depth': 8, 'learning_rate': 0.06924562519353196, 'subsample': 0.8347594297402318, 'colsample_bytree': 0.7073147237704728, 'min_child_weight': 2.5305048449427314, 'gamma': 0.28154602647921256, 'reg_alpha': 0.0007090918725798462, 'reg_lambda': 16.063636889598452}. Best is trial 21 with value: 0.9085799477033266.
[I 2026-08-26 16:05:13,300] Trial 22 finished with value: 0.9064231495703872 and parameters: {'max_depth': 8, 'learning_rate': 0.06424278718033752, 'subsample': 0.8357333248921924, 'colsample_bytree': 0.7094659591620004, 'min_child_weight': 2.4791512197359102, 'gamma': 0.3190981570244375, 'reg_alpha': 0.00018408339991178335, 'reg_lambda': 16.108135447033}. Best is trial 21 with value: 0.9085799477033266.
[I 2026-08-26 16:05:34,554] Trial 23 finished with value: 0.909367867657172 and parameters: {'max_depth': 9, 'learning_rate': 0.048147252083289196, 'subsample': 0.797125813581282, 'colsample_bytree': 0.7661279370004789, 'min_child_weight': 1.6986108410500351, 'gamma': 0.28555720928720923, 'reg_alpha': 1.4237778102835148e-06, 'reg_lambda': 9.5245069028663}. Best is trial 23 with value: 0.909367867657172.
[I 2026-08-26 16:05:51,185] Trial 24 finished with value: 0.900792743113745 and parameters: {'max_depth': 9, 'learning_rate': 0.04595975130520439, 'subsample': 0.7990285126872183, 'colsample_bytree': 0.7773121824982291, 'min_child_weight': 1.4430903451707973, 'gamma': 0.6116233530595634, 'reg_alpha': 7.400887224418553e-07, 'reg_lambda': 10.422026094821254}. Best is trial 23 with value: 0.909367867657172.
[I 2026-08-26 16:06:01,980] Trial 25 finished with value: 0.8948452242305194 and parameters: {'max_depth': 9, 'learning_rate': 0.08116752782895725, 'subsample': 0.8890488290718077, 'colsample_bytree': 0.8165719869281165, 'min_child_weight': 0.5935612761684949, 'gamma': 0.9192059057713484, 'reg_alpha': 6.139749775621481e-06, 'reg_lambda': 2.9709497905855238}. Best is trial 23 with value: 0.909367867657172.
[I 2026-08-26 16:06:19,639] Trial 26 finished with value: 0.9122195635948727 and parameters: {'max_depth': 9, 'learning_rate': 0.051580879983002634, 'subsample': 0.9195735536042786, 'colsample_bytree': 0.8721107150104113, 'min_child_weight': 1.8241492017008714, 'gamma': 0.22166146587817856, 'reg_alpha': 2.367484546938393e-08, 'reg_lambda': 5.855325749410361}. Best is trial 26 with value: 0.9122195635948727.
[I 2026-08-26 16:06:32,334] Trial 27 finished with value: 0.8997265289715687 and parameters: {'max_depth': 9, 'learning_rate': 0.051819276773546995, 'subsample': 0.9341070359689122, 'colsample_bytree': 0.8678566544113497, 'min_child_weight': 1.0393760513244503, 'gamma': 0.601431411484846, 'reg_alpha': 2.1262209343987285e-09, 'reg_lambda': 1.975435616880923}. Best is trial 26 with value: 0.9122195635948727.
[I 2026-08-26 16:06:43,749] Trial 28 finished with value: 0.856343903631991 and parameters: {'max_depth': 9, 'learning_rate': 0.03737351393150527, 'subsample': 0.9067987106560302, 'colsample_bytree': 0.9212010741316281, 'min_child_weight': 1.9666010448342721, 'gamma': 2.8144138500819156, 'reg_alpha': 1.0139452481892552e-08, 'reg_lambda': 6.24145221052672}. Best is trial 26 with value: 0.9122195635948727.
[I 2026-08-26 16:06:57,624] Trial 29 finished with value: 0.8947592519308548 and parameters: {'max_depth': 9, 'learning_rate': 0.03130069570883663, 'subsample': 0.8644163043982267, 'colsample_bytree': 0.7418108166302164, 'min_child_weight': 1.3085990179202678, 'gamma': 1.1091046956474826, 'reg_alpha': 2.6470404133087577e-07, 'reg_lambda': 1.4680879897806767}. Best is trial 26 with value: 0.9122195635948727.
[I 2026-08-26 16:07:09,898] Trial 30 finished with value: 0.883430587654022 and parameters: {'max_depth': 10, 'learning_rate': 0.04412209841286764, 'subsample': 0.8027034219058168, 'colsample_bytree': 0.9207519379228849, 'min_child_weight': 2.201288932370683, 'gamma': 1.5543130931395168, 'reg_alpha': 2.7847708828382445e-08, 'reg_lambda': 3.7811848836852895}. Best is trial 26 with value: 0.9122195635948727.
[I 2026-08-26 16:07:24,913] Trial 31 finished with value: 0.9078514356304307 and parameters: {'max_depth': 8, 'learning_rate': 0.07335055630629271, 'subsample': 0.951950623121882, 'colsample_bytree': 0.7474127746790082, 'min_child_weight': 3.171999744904933, 'gamma': 0.2239029462102208, 'reg_alpha': 1.938848805358695e-05, 'reg_lambda': 8.416673365120081}. Best is trial 26 with value: 0.9122195635948727.
[I 2026-08-26 16:07:42,773] Trial 32 finished with value: 0.9019969531460823 and parameters: {'max_depth': 7, 'learning_rate': 0.05547195344982661, 'subsample': 0.9720816582001799, 'colsample_bytree': 0.770724159975682, 'min_child_weight': 4.960528185736757, 'gamma': 0.23256475220591893, 'reg_alpha': 3.529210309417308e-06, 'reg_lambda': 18.851818991802745}. Best is trial 26 with value: 0.9122195635948727.
[I 2026-08-26 16:07:55,024] Trial 33 finished with value: 0.9066428786294065 and parameters: {'max_depth': 8, 'learning_rate': 0.09306887119493903, 'subsample': 0.9115843298573224, 'colsample_bytree': 0.8006801135162676, 'min_child_weight': 1.955361313142587, 'gamma': 0.4259324039865958, 'reg_alpha': 6.209005369809257e-07, 'reg_lambda': 8.325324664162439}. Best is trial 26 with value: 0.9122195635948727.
[I 2026-08-26 16:08:10,494] Trial 34 finished with value: 0.9047505372688264 and parameters: {'max_depth': 7, 'learning_rate': 0.07809502939546813, 'subsample': 0.9774965260758111, 'colsample_bytree': 0.8597139241910556, 'min_child_weight': 2.9554730393246373, 'gamma': 0.19401757160928915, 'reg_alpha': 2.3801069548910886e-05, 'reg_lambda': 20.416198289127422}. Best is trial 26 with value: 0.9122195635948727.
[I 2026-08-26 16:08:23,258] Trial 35 finished with value: 0.9047449748191155 and parameters: {'max_depth': 9, 'learning_rate': 0.11498984470720786, 'subsample': 0.8521812496116874, 'colsample_bytree': 0.727223906360833, 'min_child_weight': 4.192357017667249, 'gamma': 0.4439425613235627, 'reg_alpha': 3.021291465044793e-08, 'reg_lambda': 12.087631457396789}. Best is trial 26 with value: 0.9122195635948727.
[I 2026-08-26 16:08:34,265] Trial 36 finished with value: 0.90117904206787 and parameters: {'max_depth': 10, 'learning_rate': 0.10544214460880422, 'subsample': 0.8879067624687673, 'colsample_bytree': 0.6891480751995454, 'min_child_weight': 1.7114580288193666, 'gamma': 0.59317221378863, 'reg_alpha': 1.496301897045065e-07, 'reg_lambda': 4.710768256211455}. Best is trial 26 with value: 0.9122195635948727.
[I 2026-08-26 16:08:50,147] Trial 37 finished with value: 0.8962961470770837 and parameters: {'max_depth': 7, 'learning_rate': 0.056522685649488105, 'subsample': 0.932375805011315, 'colsample_bytree': 0.6323278036245177, 'min_child_weight': 0.5075384288782143, 'gamma': 0.37379613829788944, 'reg_alpha': 3.4693636635863977e-09, 'reg_lambda': 21.79492549895766}. Best is trial 26 with value: 0.9122195635948727.
[I 2026-08-26 16:09:10,618] Trial 38 finished with value: 0.9080761557538907 and parameters: {'max_depth': 8, 'learning_rate': 0.041711104770153024, 'subsample': 0.9607040727883477, 'colsample_bytree': 0.9046479790927684, 'min_child_weight': 6.697851074094307, 'gamma': 0.17471704857124193, 'reg_alpha': 5.6882864926879936e-05, 'reg_lambda': 0.31399058639720645}. Best is trial 26 with value: 0.9122195635948727.
[I 2026-08-26 16:09:32,140] Trial 39 finished with value: 0.897706455004843 and parameters: {'max_depth': 10, 'learning_rate': 0.023188345720861633, 'subsample': 0.766061568594797, 'colsample_bytree': 0.9638361387346186, 'min_child_weight': 2.3231230360072193, 'gamma': 0.7550889246014035, 'reg_alpha': 0.0030536552221186565, 'reg_lambda': 6.419869368187415}. Best is trial 26 with value: 0.9122195635948727.
[I 2026-08-26 16:09:52,099] Trial 40 finished with value: 0.9154994941412612 and parameters: {'max_depth': 9, 'learning_rate': 0.1393710797242199, 'subsample': 0.9978487579237947, 'colsample_bytree': 0.663896332790834, 'min_child_weight': 1.2645543708931894, 'gamma': 0.0037486710095065434, 'reg_alpha': 0.0003120829532626767, 'reg_lambda': 14.648280026300263}. Best is trial 40 with value: 0.9154994941412612.
[I 2026-08-26 16:10:02,222] Trial 41 finished with value: 0.8978412139741658 and parameters: {'max_depth': 9, 'learning_rate': 0.1412582242183532, 'subsample': 0.9950992320700915, 'colsample_bytree': 0.6664890343771287, 'min_child_weight': 1.1668101400070234, 'gamma': 0.3280792755522298, 'reg_alpha': 0.0002837967776166703, 'reg_lambda': 14.520343304535997}. Best is trial 40 with value: 0.9154994941412612.
[I 2026-08-26 16:10:38,485] Trial 42 finished with value: 0.9158691334810924 and parameters: {'max_depth': 8, 'learning_rate': 0.048725762060703934, 'subsample': 0.9228355608225394, 'colsample_bytree': 0.6978025307955179, 'min_child_weight': 0.826722130751743, 'gamma': 0.014642111988752537, 'reg_alpha': 0.0005352800724305713, 'reg_lambda': 8.863080979939701}. Best is trial 42 with value: 0.9158691334810924.
[I 2026-08-26 16:11:24,025] Trial 43 finished with value: 0.9158403909598091 and parameters: {'max_depth': 9, 'learning_rate': 0.035510562463122994, 'subsample': 0.9289166073036291, 'colsample_bytree': 0.6258450425139167, 'min_child_weight': 0.8901443809418318, 'gamma': 0.003674877510156549, 'reg_alpha': 1.317074995529345e-05, 'reg_lambda': 9.197251887963903}. Best is trial 42 with value: 0.9158691334810924.
[I 2026-08-26 16:12:06,921] Trial 44 finished with value: 0.9117916097674419 and parameters: {'max_depth': 10, 'learning_rate': 0.016503822031064642, 'subsample': 0.9438464562071578, 'colsample_bytree': 0.6542965147102028, 'min_child_weight': 0.8082110482362114, 'gamma': 0.12475281955313108, 'reg_alpha': 1.1924737111696177e-05, 'reg_lambda': 8.750444697376249}. Best is trial 42 with value: 0.9158691334810924.
[I 2026-08-26 16:13:04,850] Trial 45 finished with value: 0.9142859179670808 and parameters: {'max_depth': 10, 'learning_rate': 0.015269760737057807, 'subsample': 0.9368448639956566, 'colsample_bytree': 0.6336037099199829, 'min_child_weight': 0.7727395738241987, 'gamma': 0.0074592591523478516, 'reg_alpha': 7.92881362466919e-06, 'reg_lambda': 4.173812468312798}. Best is trial 42 with value: 0.9158691334810924.
[I 2026-08-26 16:13:52,191] Trial 46 finished with value: 0.9161090494923181 and parameters: {'max_depth': 10, 'learning_rate': 0.022185572069383003, 'subsample': 0.9202555865653528, 'colsample_bytree': 0.629310587976339, 'min_child_weight': 0.6671833013826846, 'gamma': 0.03650031899603208, 'reg_alpha': 4.5632347289097206e-05, 'reg_lambda': 4.1364170704680445}. Best is trial 46 with value: 0.9161090494923181.
[I 2026-08-26 16:14:46,889] Trial 47 finished with value: 0.9154802629703583 and parameters: {'max_depth': 10, 'learning_rate': 0.015565434176870585, 'subsample': 0.9265836400105572, 'colsample_bytree': 0.6242155857799384, 'min_child_weight': 0.6724651828773508, 'gamma': 0.039965823056099754, 'reg_alpha': 4.343126363513494e-05, 'reg_lambda': 4.201581765045689}. Best is trial 46 with value: 0.9161090494923181.

[4/6] Creating 80/20 split with 'greifensee' completely held out.

[I 2026-08-26 17:27:00,166] A new study created in memory with name: DecisionTree_LOSO

[4/6] Running one 5-fold search per model.
  greifensee: tuning Decision Tree (200 trials).

[I 2026-08-26 17:27:00,750] Trial 0 finished with value: 0.6619962312741732 and parameters: {'max_depth': 12, 'min_samples_split': 96, 'min_samples_leaf': 59, 'max_features': 0.6, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 1.3480180290890803e-07}. Best is trial 0 with value: 0.6619962312741732.
[I 2026-08-26 17:27:00,812] Trial 1 finished with value: 0.5619441932793402 and parameters: {'max_depth': 17, 'min_samples_split': 44, 'min_samples_leaf': 24, 'max_features': 0.8, 'criterion': 'log_loss', 'splitter': 'random', 'class_weight': None, 'ccp_alpha': 0.0043873144324354085}. Best is trial 0 with value: 0.6619962312741732.
[I 2026-08-26 17:27:00,839] Trial 2 finished with value: 0.516079875233379 and parameters: {'max_depth': 30, 'min_samples_split': 82, 'min_samples_leaf': 25, 'max_features': 'sqrt', 'criterion': 'gini', 'splitter': 'random', 'class_weight': None, 'ccp_alpha': 0.006124806805925988}. Best is trial 0 with value: 0.6619962312741732.
[I 2026-08-26 17:27:01,036] Trial 3 finished with value: 0.6269222657957375 and parameters: {'max_depth': 24, 'min_samples_split': 95, 'min_samples_leaf': 72, 'max_features': 'sqrt', 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 0.00041245717727594227}. Best is trial 0 with value: 0.6619962312741732.
[I 2026-08-26 17:27:01,139] Trial 4 finished with value: 0.5705642123292936 and parameters: {'max_depth': 4, 'min_samples_split': 99, 'min_samples_leaf': 62, 'max_features': 'log2', 'criterion': 'entropy', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 1.5027137214154575e-07}. Best is trial 0 with value: 0.6619962312741732.
[I 2026-08-26 17:27:01,975] Trial 5 finished with value: 0.664690325045893 and parameters: {'max_depth': 11, 'min_samples_split': 74, 'min_samples_leaf': 52, 'max_features': None, 'criterion': 'gini', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 2.8501838758433707e-05}. Best is trial 5 with value: 0.664690325045893.
[I 2026-08-26 17:27:01,997] Trial 6 finished with value: 0.5648354699595763 and parameters: {'max_depth': 11, 'min_samples_split': 52, 'min_samples_leaf': 73, 'max_features': 'log2', 'criterion': 'entropy', 'splitter': 'random', 'class_weight': None, 'ccp_alpha': 0.0017697543538533224}. Best is trial 5 with value: 0.664690325045893.
[I 2026-08-26 17:27:02,758] Trial 7 finished with value: 0.6617207930151341 and parameters: {'max_depth': 17, 'min_samples_split': 81, 'min_samples_leaf': 72, 'max_features': 0.8, 'criterion': 'entropy', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 1.8298712093870903e-07}. Best is trial 5 with value: 0.664690325045893.
[I 2026-08-26 17:27:02,825] Trial 8 finished with value: 0.6493424182256381 and parameters: {'max_depth': 17, 'min_samples_split': 71, 'min_samples_leaf': 30, 'max_features': None, 'criterion': 'entropy', 'splitter': 'random', 'class_weight': None, 'ccp_alpha': 1.0333896431462928e-08}. Best is trial 5 with value: 0.664690325045893.
[I 2026-08-26 17:27:03,016] Trial 9 finished with value: 0.6604681472639894 and parameters: {'max_depth': 16, 'min_samples_split': 99, 'min_samples_leaf': 20, 'max_features': 'sqrt', 'criterion': 'gini', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 1.3685182782317289e-05}. Best is trial 5 with value: 0.664690325045893.
[I 2026-08-26 17:27:03,253] Trial 10 finished with value: 0.564195943824752 and parameters: {'max_depth': 2, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': None, 'criterion': 'gini', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 2.336601710098664e-05}. Best is trial 5 with value: 0.664690325045893.
[I 2026-08-26 17:27:03,825] Trial 11 finished with value: 0.6465640192604003 and parameters: {'max_depth': 10, 'min_samples_split': 59, 'min_samples_leaf': 50, 'max_features': 0.6, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 1.7325819024028384e-06}. Best is trial 5 with value: 0.664690325045893.
[I 2026-08-26 17:27:04,432] Trial 12 finished with value: 0.6683062262478322 and parameters: {'max_depth': 12, 'min_samples_split': 35, 'min_samples_leaf': 48, 'max_features': 0.6, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 3.1205813623082966e-09}. Best is trial 12 with value: 0.6683062262478322.
[I 2026-08-26 17:27:04,669] Trial 13 finished with value: 0.6032990923286663 and parameters: {'max_depth': 6, 'min_samples_split': 22, 'min_samples_leaf': 42, 'max_features': 0.4, 'criterion': 'gini', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 1.090860668147555e-09}. Best is trial 12 with value: 0.6683062262478322.
[I 2026-08-26 17:27:05,538] Trial 14 finished with value: 0.6233850124961134 and parameters: {'max_depth': 8, 'min_samples_split': 34, 'min_samples_leaf': 42, 'max_features': None, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 0.00014678727050247952}. Best is trial 12 with value: 0.6683062262478322.
[I 2026-08-26 17:27:06,079] Trial 15 finished with value: 0.6730028488913344 and parameters: {'max_depth': 23, 'min_samples_split': 17, 'min_samples_leaf': 54, 'max_features': 0.6, 'criterion': 'gini', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 1.0921296040492856e-09}. Best is trial 15 with value: 0.6730028488913344.
[I 2026-08-26 17:27:06,663] Trial 16 finished with value: 0.6984053151380759 and parameters: {'max_depth': 24, 'min_samples_split': 16, 'min_samples_leaf': 37, 'max_features': 0.6, 'criterion': 'gini', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 1.0986475105496506e-09}. Best is trial 16 with value: 0.6984053151380759.
[I 2026-08-26 17:27:07,269] Trial 17 finished with value: 0.6999427817830417 and parameters: {'max_depth': 24, 'min_samples_split': 8, 'min_samples_leaf': 34, 'max_features': 0.6, 'criterion': 'gini', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 1.4089758776600013e-08}. Best is trial 17 with value: 0.6999427817830417.
[I 2026-08-26 17:27:07,338] Trial 18 finished with value: 0.6873308607216103 and parameters: {'max_depth': 26, 'min_samples_split': 4, 'min_samples_leaf': 10, 'max_features': 0.6, 'criterion': 'gini', 'splitter': 'random', 'class_weight': 'balanced', 'ccp_alpha': 1.9728850017588817e-08}. Best is trial 17 with value: 0.6999427817830417.
[I 2026-08-26 17:27:07,919] Trial 19 finished with value: 0.6959586971927869 and parameters: {'max_depth': 20, 'min_samples_split': 16, 'min_samples_leaf': 35, 'max_features': 0.6, 'criterion': 'gini', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 2.093549252656041e-08}. Best is trial 17 with value: 0.6999427817830417.
[I 2026-08-26 17:27:08,293] Trial 20 finished with value: 0.6823939483047685 and parameters: {'max_depth': 30, 'min_samples_split': 27, 'min_samples_leaf': 37, 'max_features': 0.4, 'criterion': 'gini', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 1.0601682115021286e-06}. Best is trial 17 with value: 0.6999427817830417.
[I 2026-08-26 17:27:08,892] Trial 21 finished with value: 0.6999427817830417 and parameters: {'max_depth': 21, 'min_samples_split': 14, 'min_samples_leaf': 34, 'max_features': 0.6, 'criterion': 'gini', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 2.1617327577514438e-08}. Best is trial 17 with value: 0.6999427817830417.
[I 2026-08-26 17:27:09,533] Trial 22 finished with value: 0.7287657278546156 and parameters: {'max_depth': 21, 'min_samples_split': 11, 'min_samples_leaf': 16, 'max_features': 0.6, 'criterion': 'gini', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 6.55410283740987e-09}. Best is trial 22 with value: 0.7287657278546156.
[I 2026-08-26 17:27:10,190] Trial 23 finished with value: 0.7404346837478941 and parameters: {'max_depth': 21, 'min_samples_split': 9, 'min_samples_leaf': 11, 'max_features': 0.6, 'criterion': 'gini', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 5.4428421410715603e-08}. Best is trial 23 with value: 0.7404346837478941.
[I 2026-08-26 17:27:10,852] Trial 24 finished with value: 0.7353714416142523 and parameters: {'max_depth': 27, 'min_samples_split': 8, 'min_samples_leaf': 14, 'max_features': 0.6, 'criterion': 'gini', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 7.732586727170022e-08}. Best is trial 23 with value: 0.7404346837478941.
[I 2026-08-26 17:27:11,507] Trial 25 finished with value: 0.7371035219628733 and parameters: {'max_depth': 28, 'min_samples_split': 27, 'min_samples_leaf': 12, 'max_features': 0.6, 'criterion': 'gini', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 7.905028841941448e-07}. Best is trial 23 with value: 0.7404346837478941.
[I 2026-08-26 17:27:11,574] Trial 26 finished with value: 0.6841225114578585 and parameters: {'max_depth': 27, 'min_samples_split': 30, 'min_samples_leaf': 7, 'max_features': 0.6, 'criterion': 'gini', 'splitter': 'random', 'class_weight': 'balanced', 'ccp_alpha': 9.074485441224073e-07}. Best is trial 23 with value: 0.7404346837478941.
[I 2026-08-26 17:27:11,987] Trial 27 finished with value: 0.7165790238411562 and parameters: {'max_depth': 28, 'min_samples_split': 39, 'min_samples_leaf': 13, 'max_features': 0.4, 'criterion': 'gini', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 4.213211049589255e-06}. Best is trial 23 with value: 0.7404346837478941.
[I 2026-08-26 17:27:12,230] Trial 28 finished with value: 0.7173468767331077 and parameters: {'max_depth': 28, 'min_samples_split': 24, 'min_samples_leaf': 2, 'max_features': 'log2', 'criterion': 'gini', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 8.66490174097436e-08}. Best is trial 23 with value: 0.7404346837478941.
[I 2026-08-26 17:27:12,950] Trial 29 finished with value: 0.7186586537067041 and parameters: {'max_depth': 25, 'min_samples_split': 21, 'min_samples_leaf': 19, 'max_features': 0.6, 'criterion': 'entropy', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 3.320972037490993e-07}. Best is trial 23 with value: 0.7404346837478941.
[I 2026-08-26 17:27:13,846] Trial 30 finished with value: 0.7552368922136192 and parameters: {'max_depth': 19, 'min_samples_split': 9, 'min_samples_leaf': 8, 'max_features': 0.8, 'criterion': 'gini', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 7.128865133257722e-08}. Best is trial 30 with value: 0.7552368922136192.
[I 2026-08-26 17:27:14,693] Trial 31 finished with value: 0.7308982581941339 and parameters: {'max_depth': 14, 'min_samples_split': 7, 'min_samples_leaf': 7, 'max_features': 0.8, 'criterion': 'gini', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 6.04357952322774e-08}. Best is trial 30 with value: 0.7552368922136192.
[I 2026-08-26 17:27:15,558] Trial 32 finished with value: 0.7392498286478901 and parameters: {'max_depth': 20, 'min_samples_split': 2, 'min_samples_leaf': 13, 'max_features': 0.8, 'criterion': 'gini', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 4.875432752004201e-08}. Best is trial 30 with value: 0.7552368922136192.
[I 2026-08-26 17:27:16,437] Trial 33 finished with value: 0.736763497148749 and parameters: {'max_depth': 19, 'min_samples_split': 43, 'min_samples_leaf': 6, 'max_features': 0.8, 'criterion': 'gini', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 3.5260685016505627e-07}. Best is trial 30 with value: 0.7552368922136192.
[I 2026-08-26 17:27:16,502] Trial 34 finished with value: 0.6470278639488989 and parameters: {'max_depth': 14, 'min_samples_split': 10, 'min_samples_leaf': 25, 'max_features': 0.8, 'criterion': 'gini', 'splitter': 'random', 'class_weight': 'balanced', 'ccp_alpha': 4.7476978002386736e-08}. Best is trial 30 with value: 0.7552368922136192.
[I 2026-08-26 17:27:17,417] Trial 35 finished with value: 0.7247212010132739 and parameters: {'max_depth': 22, 'min_samples_split': 2, 'min_samples_leaf': 21, 'max_features': 0.8, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 4.884369583074042e-06}. Best is trial 30 with value: 0.7552368922136192.
[I 2026-08-26 17:27:18,294] Trial 36 finished with value: 0.7457080693551686 and parameters: {'max_depth': 19, 'min_samples_split': 20, 'min_samples_leaf': 10, 'max_features': 0.8, 'criterion': 'gini', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 5.20481362809722e-07}. Best is trial 30 with value: 0.7552368922136192.
[I 2026-08-26 17:27:18,358] Trial 37 finished with value: 0.6558286823903208 and parameters: {'max_depth': 19, 'min_samples_split': 19, 'min_samples_leaf': 24, 'max_features': 0.8, 'criterion': 'gini', 'splitter': 'random', 'class_weight': None, 'ccp_alpha': 3.8804943243036213e-07}. Best is trial 30 with value: 0.7552368922136192.
[I 2026-08-26 17:27:19,280] Trial 38 finished with value: 0.7263303534326553 and parameters: {'max_depth': 15, 'min_samples_split': 12, 'min_samples_leaf': 17, 'max_features': 0.8, 'criterion': 'entropy', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 4.526052881512271e-08}. Best is trial 30 with value: 0.7552368922136192.
[I 2026-08-26 17:27:20,127] Trial 39 finished with value: 0.755060739257108 and parameters: {'max_depth': 20, 'min_samples_split': 6, 'min_samples_leaf': 9, 'max_features': 0.8, 'criterion': 'gini', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 1.986607473793068e-07}. Best is trial 30 with value: 0.7552368922136192.
[I 2026-08-26 17:27:20,165] Trial 40 finished with value: 0.6427603811847067 and parameters: {'max_depth': 18, 'min_samples_split': 32, 'min_samples_leaf': 3, 'max_features': 'sqrt', 'criterion': 'log_loss', 'splitter': 'random', 'class_weight': None, 'ccp_alpha': 2.14559642614391e-07}. Best is trial 30 with value: 0.7552368922136192.
[I 2026-08-26 17:27:21,032] Trial 41 finished with value: 0.7659434901692858 and parameters: {'max_depth': 22, 'min_samples_split': 6, 'min_samples_leaf': 6, 'max_features': 0.8, 'criterion': 'gini', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 5.287054376370919e-09}. Best is trial 41 with value: 0.7659434901692858.
[I 2026-08-26 17:27:21,877] Trial 42 finished with value: 0.7507228279499621 and parameters: {'max_depth': 22, 'min_samples_split': 14, 'min_samples_leaf': 9, 'max_features': 0.8, 'criterion': 'gini', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 3.730057704408271e-09}. Best is trial 41 with value: 0.7659434901692858.
[I 2026-08-26 17:27:22,738] Trial 43 finished with value: 0.7645559052833328 and parameters: {'max_depth': 18, 'min_samples_split': 14, 'min_samples_leaf': 6, 'max_features': 0.8, 'criterion': 'gini', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 8.695757328241909e-09}. Best is trial 41 with value: 0.7659434901692858.
[I 2026-08-26 17:27:23,598] Trial 44 finished with value: 0.7599387345812008 and parameters: {'max_depth': 17, 'min_samples_split': 6, 'min_samples_leaf': 5, 'max_features': 0.8, 'criterion': 'gini', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 4.882803110333423e-09}. Best is trial 41 with value: 0.7659434901692858.
[I 2026-08-26 17:27:24,592] Trial 45 finished with value: 0.7610485663401856 and parameters: {'max_depth': 17, 'min_samples_split': 6, 'min_samples_leaf': 4, 'max_features': 0.8, 'criterion': 'entropy', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 4.251912910781774e-09}. Best is trial 41 with value: 0.7659434901692858.
[I 2026-08-26 17:27:25,566] Trial 46 finished with value: 0.7485757438586312 and parameters: {'max_depth': 16, 'min_samples_split': 25, 'min_samples_leaf': 4, 'max_features': 0.8, 'criterion': 'entropy', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 2.8727145240333364e-09}. Best is trial 41 with value: 0.7659434901692858.
[I 2026-08-26 17:27:26,579] Trial 47 finished with value: 0.764536086065474 and parameters: {'max_depth': 17, 'min_samples_split': 13, 'min_samples_leaf': 2, 'max_features': 0.8, 'criterion': 'entropy', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 5.182941046489236e-09}. Best is trial 41 with value: 0.7659434901692858.
[I 2026-08-26 17:27:27,524] Trial 48 finished with value: 0.7246448917678003 and parameters: {'max_depth': 13, 'min_samples_split': 13, 'min_samples_leaf': 1, 'max_features': 0.8, 'criterion': 'entropy', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 7.0418244779526495e-09}. Best is trial 41 with value: 0.7659434901692858.
[I 2026-08-26 17:27:27,771] Trial 49 finished with value: 0.6941162657886544 and parameters: {'max_depth': 17, 'min_samples_split': 51, 'min_samples_leaf': 5, 'max_features': 'log2', 'criterion': 'entropy', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 3.732807059831021e-09}. Best is trial 41 with value: 0.7659434901692858.
[I 2026-08-26 17:27:28,785] Trial 50 finished with value: 0.76490486483543 and parameters: {'max_depth': 16, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 0.8, 'criterion': 'entropy', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 8.63035739130916e-09}. Best is trial 41 with value: 0.7659434901692858.
[I 2026-08-26 17:27:29,798] Trial 51 finished with value: 0.7648205395877014 and parameters: {'max_depth': 16, 'min_samples_split': 4, 'min_samples_leaf': 1, 'max_features': 0.8, 'criterion': 'entropy', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 7.255738554448457e-09}. Best is trial 41 with value: 0.7659434901692858.
[I 2026-08-26 17:27:30,786] Trial 52 finished with value: 0.752365903270143 and parameters: {'max_depth': 15, 'min_samples_split': 17, 'min_samples_leaf': 1, 'max_features': 0.8, 'criterion': 'entropy', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 2.110220686775117e-09}. Best is trial 41 with value: 0.7659434901692858.
[I 2026-08-26 17:27:30,998] Trial 53 finished with value: 0.6432205607618996 and parameters: {'max_depth': 10, 'min_samples_split': 4, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'criterion': 'entropy', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 1.037684923052487e-08}. Best is trial 41 with value: 0.7659434901692858.
[I 2026-08-26 17:27:31,758] Trial 54 finished with value: 0.6612188525254625 and parameters: {'max_depth': 16, 'min_samples_split': 90, 'min_samples_leaf': 68, 'max_features': 0.8, 'criterion': 'entropy', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 1.8338924049164492e-09}. Best is trial 41 with value: 0.7659434901692858.
[I 2026-08-26 17:27:32,694] Trial 55 finished with value: 0.6520948830539915 and parameters: {'max_depth': 13, 'min_samples_split': 13, 'min_samples_leaf': 78, 'max_features': None, 'criterion': 'entropy', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 2.2900308411351124e-08}. Best is trial 41 with value: 0.7659434901692858.
[I 2026-08-26 17:27:33,685] Trial 56 finished with value: 0.7606671946455582 and parameters: {'max_depth': 18, 'min_samples_split': 2, 'min_samples_leaf': 5, 'max_features': 0.8, 'criterion': 'entropy', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 9.45229752327679e-09}. Best is trial 41 with value: 0.7659434901692858.
[I 2026-08-26 17:27:33,752] Trial 57 finished with value: 0.6635243137768885 and parameters: {'max_depth': 15, 'min_samples_split': 18, 'min_samples_leaf': 16, 'max_features': 0.8, 'criterion': 'entropy', 'splitter': 'random', 'class_weight': None, 'ccp_alpha': 1.9486310717598687e-09}. Best is trial 41 with value: 0.7659434901692858.
[I 2026-08-26 17:27:34,648] Trial 58 finished with value: 0.7062672356858751 and parameters: {'max_depth': 12, 'min_samples_split': 6, 'min_samples_leaf': 3, 'max_features': 0.8, 'criterion': 'entropy', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 1.3137041657798417e-08}. Best is trial 41 with value: 0.7659434901692858.

  greifensee: tuning Random Forest (200 trials).

[I 2026-08-26 17:30:29,898] Trial 0 finished with value: 0.8141195825859597 and parameters: {'n_estimators': 300, 'max_depth': 32, 'min_samples_split': 3, 'min_samples_leaf': 15, 'max_features': 0.7, 'bootstrap': True, 'criterion': 'log_loss', 'class_weight': None}. Best is trial 0 with value: 0.8141195825859597.
[I 2026-08-26 17:30:40,431] Trial 1 finished with value: 0.7836056531618627 and parameters: {'n_estimators': 600, 'max_depth': 16, 'min_samples_split': 20, 'min_samples_leaf': 13, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'gini', 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8141195825859597.
[I 2026-08-26 17:31:14,460] Trial 2 finished with value: 0.6862657842469728 and parameters: {'n_estimators': 600, 'max_depth': 8, 'min_samples_split': 28, 'min_samples_leaf': 15, 'max_features': 0.7, 'bootstrap': True, 'criterion': 'entropy', 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8141195825859597.
[I 2026-08-26 17:31:41,721] Trial 3 finished with value: 0.7989511161882068 and parameters: {'n_estimators': 800, 'max_depth': 24, 'min_samples_split': 25, 'min_samples_leaf': 20, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'log_loss', 'class_weight': None}. Best is trial 0 with value: 0.8141195825859597.
[I 2026-08-26 17:32:03,061] Trial 4 finished with value: 0.7811786346063421 and parameters: {'n_estimators': 1000, 'max_depth': 16, 'min_samples_split': 31, 'min_samples_leaf': 15, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy', 'class_weight': None}. Best is trial 0 with value: 0.8141195825859597.
[I 2026-08-26 17:32:38,008] Trial 5 finished with value: 0.8538842367764268 and parameters: {'n_estimators': 800, 'max_depth': 48, 'min_samples_split': 18, 'min_samples_leaf': 3, 'max_features': 0.3, 'bootstrap': False, 'criterion': 'gini', 'class_weight': 'balanced'}. Best is trial 5 with value: 0.8538842367764268.
[I 2026-08-26 17:33:02,677] Trial 6 finished with value: 0.8268617427423475 and parameters: {'n_estimators': 400, 'max_depth': 48, 'min_samples_split': 34, 'min_samples_leaf': 1, 'max_features': 0.5, 'bootstrap': True, 'criterion': 'entropy', 'class_weight': 'balanced'}. Best is trial 5 with value: 0.8538842367764268.
[I 2026-08-26 17:33:54,582] Trial 7 finished with value: 0.8254889680498815 and parameters: {'n_estimators': 1000, 'max_depth': 32, 'min_samples_split': 19, 'min_samples_leaf': 15, 'max_features': 0.3, 'bootstrap': False, 'criterion': 'log_loss', 'class_weight': 'balanced'}. Best is trial 5 with value: 0.8538842367764268.
[I 2026-08-26 17:35:57,513] Trial 8 finished with value: 0.7361951658601475 and parameters: {'n_estimators': 900, 'max_depth': 24, 'min_samples_split': 40, 'min_samples_leaf': 19, 'max_features': 1.0, 'bootstrap': False, 'criterion': 'gini', 'class_weight': 'balanced_subsample'}. Best is trial 5 with value: 0.8538842367764268.
[I 2026-08-26 17:36:33,291] Trial 9 finished with value: 0.871683704457389 and parameters: {'n_estimators': 600, 'max_depth': None, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 0.3, 'bootstrap': False, 'criterion': 'log_loss', 'class_weight': 'balanced_subsample'}. Best is trial 9 with value: 0.871683704457389.
[I 2026-08-26 17:36:52,568] Trial 10 finished with value: 0.8440668810093032 and parameters: {'n_estimators': 500, 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 7, 'max_features': 'log2', 'bootstrap': False, 'criterion': 'log_loss', 'class_weight': 'balanced_subsample'}. Best is trial 9 with value: 0.871683704457389.
[I 2026-08-26 17:37:24,672] Trial 11 finished with value: 0.865446789200121 and parameters: {'n_estimators': 700, 'max_depth': 48, 'min_samples_split': 12, 'min_samples_leaf': 1, 'max_features': 0.3, 'bootstrap': False, 'criterion': 'gini', 'class_weight': 'balanced_subsample'}. Best is trial 9 with value: 0.871683704457389.
[I 2026-08-26 17:37:51,484] Trial 12 finished with value: 0.8000992915143845 and parameters: {'n_estimators': 700, 'max_depth': 12, 'min_samples_split': 11, 'min_samples_leaf': 5, 'max_features': 0.3, 'bootstrap': False, 'criterion': 'gini', 'class_weight': 'balanced_subsample'}. Best is trial 9 with value: 0.871683704457389.
[I 2026-08-26 17:38:27,330] Trial 13 finished with value: 0.8690492988023243 and parameters: {'n_estimators': 600, 'max_depth': None, 'min_samples_split': 11, 'min_samples_leaf': 1, 'max_features': 0.3, 'bootstrap': False, 'criterion': 'log_loss', 'class_weight': 'balanced_subsample'}. Best is trial 9 with value: 0.871683704457389.
[I 2026-08-26 17:38:55,099] Trial 14 finished with value: 0.8498179754867609 and parameters: {'n_estimators': 500, 'max_depth': None, 'min_samples_split': 9, 'min_samples_leaf': 8, 'max_features': 0.3, 'bootstrap': False, 'criterion': 'log_loss', 'class_weight': 'balanced_subsample'}. Best is trial 9 with value: 0.871683704457389.
[I 2026-08-26 17:39:46,607] Trial 15 finished with value: 0.87332770053839 and parameters: {'n_estimators': 500, 'max_depth': None, 'min_samples_split': 7, 'min_samples_leaf': 4, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'log_loss', 'class_weight': 'balanced_subsample'}. Best is trial 15 with value: 0.87332770053839.
[I 2026-08-26 17:40:16,099] Trial 16 finished with value: 0.8528074172518586 and parameters: {'n_estimators': 300, 'max_depth': None, 'min_samples_split': 6, 'min_samples_leaf': 9, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'log_loss', 'class_weight': 'balanced_subsample'}. Best is trial 15 with value: 0.87332770053839.
[I 2026-08-26 17:40:59,276] Trial 17 finished with value: 0.866017601159009 and parameters: {'n_estimators': 400, 'max_depth': None, 'min_samples_split': 16, 'min_samples_leaf': 4, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'log_loss', 'class_weight': 'balanced_subsample'}. Best is trial 15 with value: 0.87332770053839.
[I 2026-08-26 17:41:12,741] Trial 18 finished with value: 0.6800062724839588 and parameters: {'n_estimators': 500, 'max_depth': 8, 'min_samples_split': 7, 'min_samples_leaf': 6, 'max_features': 'log2', 'bootstrap': False, 'criterion': 'log_loss', 'class_weight': 'balanced_subsample'}. Best is trial 15 with value: 0.87332770053839.
[I 2026-08-26 17:42:22,864] Trial 19 finished with value: 0.7132827995055561 and parameters: {'n_estimators': 400, 'max_depth': 12, 'min_samples_split': 15, 'min_samples_leaf': 10, 'max_features': 1.0, 'bootstrap': False, 'criterion': 'log_loss', 'class_weight': 'balanced_subsample'}. Best is trial 15 with value: 0.87332770053839.
[I 2026-08-26 17:43:36,712] Trial 20 finished with value: 0.8767270092132208 and parameters: {'n_estimators': 700, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 3, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8767270092132208.
[I 2026-08-26 17:44:50,050] Trial 21 finished with value: 0.8767270092132208 and parameters: {'n_estimators': 700, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 3, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8767270092132208.
[I 2026-08-26 17:46:03,384] Trial 22 finished with value: 0.8767270092132208 and parameters: {'n_estimators': 700, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 3, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8767270092132208.
[I 2026-08-26 17:47:27,098] Trial 23 finished with value: 0.8760493274778103 and parameters: {'n_estimators': 800, 'max_depth': None, 'min_samples_split': 3, 'min_samples_leaf': 3, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8767270092132208.
[I 2026-08-26 17:48:40,771] Trial 24 finished with value: 0.8767270092132208 and parameters: {'n_estimators': 700, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 3, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8767270092132208.
[I 2026-08-26 17:50:11,245] Trial 25 finished with value: 0.8635585302382592 and parameters: {'n_estimators': 900, 'max_depth': None, 'min_samples_split': 14, 'min_samples_leaf': 6, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8767270092132208.
[I 2026-08-26 17:50:54,739] Trial 26 finished with value: 0.8533034854199348 and parameters: {'n_estimators': 700, 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 5, 'max_features': 0.5, 'bootstrap': True, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8767270092132208.
[I 2026-08-26 17:52:04,850] Trial 27 finished with value: 0.8046136296322286 and parameters: {'n_estimators': 800, 'max_depth': 12, 'min_samples_split': 7, 'min_samples_leaf': 11, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8767270092132208.
[I 2026-08-26 17:53:35,781] Trial 28 finished with value: 0.863490430719013 and parameters: {'n_estimators': 900, 'max_depth': 16, 'min_samples_split': 5, 'min_samples_leaf': 3, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8767270092132208.
[I 2026-08-26 17:54:32,812] Trial 29 finished with value: 0.8465199269541912 and parameters: {'n_estimators': 700, 'max_depth': 32, 'min_samples_split': 4, 'min_samples_leaf': 7, 'max_features': 0.7, 'bootstrap': True, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8767270092132208.
[I 2026-08-26 17:55:27,702] Trial 30 finished with value: 0.6862882760165975 and parameters: {'n_estimators': 800, 'max_depth': 8, 'min_samples_split': 9, 'min_samples_leaf': 2, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8767270092132208.
[I 2026-08-26 17:56:40,096] Trial 31 finished with value: 0.8724667019002015 and parameters: {'n_estimators': 700, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 4, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8767270092132208.
[I 2026-08-26 17:57:43,387] Trial 32 finished with value: 0.8749855442543932 and parameters: {'n_estimators': 600, 'max_depth': None, 'min_samples_split': 8, 'min_samples_leaf': 3, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8767270092132208.
[I 2026-08-26 17:59:19,863] Trial 33 finished with value: 0.8652711085109628 and parameters: {'n_estimators': 700, 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 5, 'max_features': 0.7, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8767270092132208.
[I 2026-08-26 17:59:58,294] Trial 34 finished with value: 0.855650802673862 and parameters: {'n_estimators': 600, 'max_depth': 32, 'min_samples_split': 13, 'min_samples_leaf': 2, 'max_features': 0.5, 'bootstrap': True, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8767270092132208.
[I 2026-08-26 18:00:30,345] Trial 35 finished with value: 0.8464324096111042 and parameters: {'n_estimators': 800, 'max_depth': 24, 'min_samples_split': 22, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8767270092132208.
[I 2026-08-26 18:00:47,129] Trial 36 finished with value: 0.81858284789689 and parameters: {'n_estimators': 700, 'max_depth': 16, 'min_samples_split': 5, 'min_samples_leaf': 6, 'max_features': 'log2', 'bootstrap': True, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8767270092132208.
[I 2026-08-26 18:02:47,373] Trial 37 finished with value: 0.7793511685278287 and parameters: {'n_estimators': 600, 'max_depth': None, 'min_samples_split': 4, 'min_samples_leaf': 4, 'max_features': 1.0, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8767270092132208.
[I 2026-08-26 18:03:08,411] Trial 38 finished with value: 0.6813543934686297 and parameters: {'n_estimators': 800, 'max_depth': 8, 'min_samples_split': 8, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'entropy', 'class_weight': 'balanced'}. Best is trial 20 with value: 0.8767270092132208.
[I 2026-08-26 18:04:01,532] Trial 39 finished with value: 0.8436810576073785 and parameters: {'n_estimators': 900, 'max_depth': 24, 'min_samples_split': 6, 'min_samples_leaf': 7, 'max_features': 0.5, 'bootstrap': True, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8767270092132208.
[I 2026-08-26 18:05:23,812] Trial 40 finished with value: 0.8697031090684337 and parameters: {'n_estimators': 600, 'max_depth': 48, 'min_samples_split': 10, 'min_samples_leaf': 3, 'max_features': 0.7, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8767270092132208.
[I 2026-08-26 18:06:45,565] Trial 41 finished with value: 0.8760493274778103 and parameters: {'n_estimators': 800, 'max_depth': None, 'min_samples_split': 3, 'min_samples_leaf': 3, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8767270092132208.
[I 2026-08-26 18:08:06,792] Trial 42 finished with value: 0.8723236509466613 and parameters: {'n_estimators': 800, 'max_depth': None, 'min_samples_split': 4, 'min_samples_leaf': 4, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8767270092132208.
[I 2026-08-26 18:09:09,576] Trial 43 finished with value: 0.8243396823068373 and parameters: {'n_estimators': 700, 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 18, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8767270092132208.
[I 2026-08-26 18:10:07,549] Trial 44 finished with value: 0.876961596199498 and parameters: {'n_estimators': 700, 'max_depth': None, 'min_samples_split': 4, 'min_samples_leaf': 1, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'gini', 'class_weight': 'balanced'}. Best is trial 44 with value: 0.876961596199498.
[I 2026-08-26 18:11:05,004] Trial 45 finished with value: 0.8719564732402507 and parameters: {'n_estimators': 700, 'max_depth': None, 'min_samples_split': 9, 'min_samples_leaf': 1, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'gini', 'class_weight': 'balanced'}. Best is trial 44 with value: 0.876961596199498.
[I 2026-08-26 18:11:56,776] Trial 46 finished with value: 0.8299555187350421 and parameters: {'n_estimators': 700, 'max_depth': 16, 'min_samples_split': 40, 'min_samples_leaf': 2, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'gini', 'class_weight': 'balanced'}. Best is trial 44 with value: 0.876961596199498.
[I 2026-08-26 18:13:31,031] Trial 47 finished with value: 0.7479548608385154 and parameters: {'n_estimators': 600, 'max_depth': None, 'min_samples_split': 37, 'min_samples_leaf': 1, 'max_features': 1.0, 'bootstrap': False, 'criterion': 'gini', 'class_weight': 'balanced'}. Best is trial 44 with value: 0.876961596199498.
[I 2026-08-26 18:13:48,658] Trial 48 finished with value: 0.8310981104006409 and parameters: {'n_estimators': 600, 'max_depth': 48, 'min_samples_split': 28, 'min_samples_leaf': 5, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'gini', 'class_weight': 'balanced'}. Best is trial 44 with value: 0.876961596199498.
[I 2026-08-26 18:14:10,845] Trial 49 finished with value: 0.8624203675945162 and parameters: {'n_estimators': 700, 'max_depth': 32, 'min_samples_split': 6, 'min_samples_leaf': 2, 'max_features': 'log2', 'bootstrap': False, 'criterion': 'gini', 'class_weight': 'balanced'}. Best is trial 44 with value: 0.876961596199498.
[I 2026-08-26 18:14:45,345] Trial 50 finished with value: 0.8549210134021313 and parameters: {'n_estimators': 700, 'max_depth': None, 'min_samples_split': 12, 'min_samples_leaf': 1, 'max_features': 0.5, 'bootstrap': True, 'criterion': 'gini', 'class_weight': 'balanced'}. Best is trial 44 with value: 0.876961596199498.
[I 2026-08-26 18:16:06,788] Trial 51 finished with value: 0.8760493274778103 and parameters: {'n_estimators': 800, 'max_depth': None, 'min_samples_split': 4, 'min_samples_leaf': 3, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 44 with value: 0.876961596199498.
[I 2026-08-26 18:17:27,407] Trial 52 finished with value: 0.8723236509466613 and parameters: {'n_estimators': 800, 'max_depth': None, 'min_samples_split': 3, 'min_samples_leaf': 4, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 44 with value: 0.876961596199498.
[I 2026-08-26 18:18:59,297] Trial 53 finished with value: 0.8765545243280017 and parameters: {'n_estimators': 900, 'max_depth': None, 'min_samples_split': 7, 'min_samples_leaf': 3, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 44 with value: 0.876961596199498.
[I 2026-08-26 18:20:38,539] Trial 54 finished with value: 0.8683135545480767 and parameters: {'n_estimators': 1000, 'max_depth': None, 'min_samples_split': 8, 'min_samples_leaf': 5, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 44 with value: 0.876961596199498.
[I 2026-08-26 18:21:37,772] Trial 55 finished with value: 0.8140799401494936 and parameters: {'n_estimators': 900, 'max_depth': 12, 'min_samples_split': 10, 'min_samples_leaf': 2, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'gini', 'class_weight': None}. Best is trial 44 with value: 0.876961596199498.
[I 2026-08-26 18:22:36,868] Trial 56 finished with value: 0.8646040841393077 and parameters: {'n_estimators': 600, 'max_depth': None, 'min_samples_split': 6, 'min_samples_leaf': 6, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 44 with value: 0.876961596199498.
[I 2026-08-26 18:24:19,031] Trial 57 finished with value: 0.8717107530827107 and parameters: {'n_estimators': 1000, 'max_depth': None, 'min_samples_split': 11, 'min_samples_leaf': 4, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': 'balanced'}. Best is trial 44 with value: 0.876961596199498.
[I 2026-08-26 18:24:48,467] Trial 58 finished with value: 0.8719499168886274 and parameters: {'n_estimators': 500, 'max_depth': 24, 'min_samples_split': 8, 'min_samples_leaf': 1, 'max_features': 0.3, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 44 with value: 0.876961596199498.
[I 2026-08-26 18:25:36,547] Trial 59 finished with value: 0.8276061086257569 and parameters: {'n_estimators': 700, 'max_depth': None, 'min_samples_split': 7, 'min_samples_leaf': 16, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'gini', 'class_weight': None}. Best is trial 44 with value: 0.876961596199498.
[I 2026-08-26 18:27:34,722] Trial 60 finished with value: 0.6241535117158207 and parameters: {'n_estimators': 900, 'max_depth': 8, 'min_samples_split': 5, 'min_samples_leaf': 3, 'max_features': 1.0, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 44 with value: 0.876961596199498.
[I 2026-08-26 18:28:56,597] Trial 61 finished with value: 0.8760493274778103 and parameters: {'n_estimators': 800, 'max_depth': None, 'min_samples_split': 3, 'min_samples_leaf': 3, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 44 with value: 0.876961596199498.

  greifensee: tuning XGBoost (200 trials).

[I 2026-08-26 21:36:46,743] Trial 0 finished with value: 0.8333218754558624 and parameters: {'max_depth': 9, 'learning_rate': 0.019677977348166304, 'subsample': 0.8978561926718072, 'colsample_bytree': 0.7442003345025142, 'min_child_weight': 2.1771032186203514, 'gamma': 1.8277151418544553, 'reg_alpha': 8.665537597324885e-06, 'reg_lambda': 1.0311514495138399}. Best is trial 0 with value: 0.8333218754558624.
[I 2026-08-26 21:37:02,093] Trial 1 finished with value: 0.852901442060953 and parameters: {'max_depth': 7, 'learning_rate': 0.09439831569936806, 'subsample': 0.9842104900822669, 'colsample_bytree': 0.7826484435755748, 'min_child_weight': 2.880043790954131, 'gamma': 0.3403911033599112, 'reg_alpha': 1.5100408408589772e-07, 'reg_lambda': 23.538263110950048}. Best is trial 1 with value: 0.852901442060953.
[I 2026-08-26 21:37:18,584] Trial 2 finished with value: 0.8757141960321035 and parameters: {'max_depth': 10, 'learning_rate': 0.14726161255504092, 'subsample': 0.8585642249613574, 'colsample_bytree': 0.6855299248522434, 'min_child_weight': 6.781935357780796, 'gamma': 0.41743875595471047, 'reg_alpha': 3.864031899313156e-05, 'reg_lambda': 14.610499699549097}. Best is trial 2 with value: 0.8757141960321035.
[I 2026-08-26 21:37:34,600] Trial 3 finished with value: 0.8508233506779087 and parameters: {'max_depth': 5, 'learning_rate': 0.08394754752250128, 'subsample': 0.9450697344147837, 'colsample_bytree': 0.6595392252176876, 'min_child_weight': 5.011643571251018, 'gamma': 0.4774657914394431, 'reg_alpha': 5.357340695323986e-08, 'reg_lambda': 0.18099954688158187}. Best is trial 2 with value: 0.8757141960321035.
[I 2026-08-26 21:37:51,031] Trial 4 finished with value: 0.7968462816598254 and parameters: {'max_depth': 4, 'learning_rate': 0.048769840070943336, 'subsample': 0.9178299664912868, 'colsample_bytree': 0.9963290723923126, 'min_child_weight': 13.502442798764482, 'gamma': 1.1322462171492673, 'reg_alpha': 0.00014367270092871558, 'reg_lambda': 0.1399264351773497}. Best is trial 2 with value: 0.8757141960321035.
[I 2026-08-26 21:38:09,622] Trial 5 finished with value: 0.7851939358891715 and parameters: {'max_depth': 8, 'learning_rate': 0.018099146987238985, 'subsample': 0.953044632771952, 'colsample_bytree': 0.8904231274266234, 'min_child_weight': 15.164258427643505, 'gamma': 2.130692051488852, 'reg_alpha': 0.009425386803829051, 'reg_lambda': 20.136195700340338}. Best is trial 2 with value: 0.8757141960321035.
[I 2026-08-26 21:38:42,870] Trial 6 finished with value: 0.8438573056263834 and parameters: {'max_depth': 10, 'learning_rate': 0.01918354750824495, 'subsample': 0.782598566894961, 'colsample_bytree': 0.7970893967426577, 'min_child_weight': 0.7811624819629674, 'gamma': 0.46120338258524907, 'reg_alpha': 6.963704487425356, 'reg_lambda': 0.47063847559435423}. Best is trial 2 with value: 0.8757141960321035.
[I 2026-08-26 21:39:07,006] Trial 7 finished with value: 0.855303794480258 and parameters: {'max_depth': 10, 'learning_rate': 0.022953302153308094, 'subsample': 0.6529433178954122, 'colsample_bytree': 0.7269413610677277, 'min_child_weight': 1.7604099383967902, 'gamma': 1.266165560263202, 'reg_alpha': 2.041568273325791e-06, 'reg_lambda': 2.5538276254965817}. Best is trial 2 with value: 0.8757141960321035.
[I 2026-08-26 21:39:26,428] Trial 8 finished with value: 0.8248858367741662 and parameters: {'max_depth': 3, 'learning_rate': 0.11851328676362981, 'subsample': 0.7074625481911713, 'colsample_bytree': 0.9645659651689448, 'min_child_weight': 20.063522776432464, 'gamma': 0.047573401053791486, 'reg_alpha': 0.34420918881100815, 'reg_lambda': 4.715832950352583}. Best is trial 2 with value: 0.8757141960321035.
[I 2026-08-26 21:39:41,248] Trial 9 finished with value: 0.7204309796452425 and parameters: {'max_depth': 3, 'learning_rate': 0.033391708755025735, 'subsample': 0.8256997968048689, 'colsample_bytree': 0.837631051781117, 'min_child_weight': 8.12005959578132, 'gamma': 1.8972954750065205, 'reg_alpha': 2.437950567013768, 'reg_lambda': 6.697837558293906}. Best is trial 2 with value: 0.8757141960321035.
[I 2026-08-26 21:39:51,680] Trial 10 finished with value: 0.7860302772798515 and parameters: {'max_depth': 6, 'learning_rate': 0.17115128841996644, 'subsample': 0.8154186866999962, 'colsample_bytree': 0.6025554256995838, 'min_child_weight': 0.8625345056254972, 'gamma': 2.9869578392012968, 'reg_alpha': 1.239446148413562e-09, 'reg_lambda': 0.9684799729031198}. Best is trial 2 with value: 0.8757141960321035.
[I 2026-08-26 21:40:11,898] Trial 11 finished with value: 0.861236200988927 and parameters: {'max_depth': 10, 'learning_rate': 0.04809950013571818, 'subsample': 0.6132599083973347, 'colsample_bytree': 0.7068708218135153, 'min_child_weight': 2.000151976177787, 'gamma': 1.1015819037394388, 'reg_alpha': 4.514632609962317e-05, 'reg_lambda': 5.019540607508096}. Best is trial 2 with value: 0.8757141960321035.
[I 2026-08-26 21:40:32,209] Trial 12 finished with value: 0.8582958809850435 and parameters: {'max_depth': 9, 'learning_rate': 0.05449774578204275, 'subsample': 0.6446773085991204, 'colsample_bytree': 0.6782743329282878, 'min_child_weight': 5.024974615071706, 'gamma': 1.0252076108694772, 'reg_alpha': 0.0009910433108845519, 'reg_lambda': 8.210034909208419}. Best is trial 2 with value: 0.8757141960321035.
[I 2026-08-26 21:40:48,758] Trial 13 finished with value: 0.8650905475875943 and parameters: {'max_depth': 10, 'learning_rate': 0.19639010434181664, 'subsample': 0.6021768360536973, 'colsample_bytree': 0.6725320077667093, 'min_child_weight': 1.334503164197373, 'gamma': 0.7848649789462945, 'reg_alpha': 6.501336646332095e-05, 'reg_lambda': 11.389015447500912}. Best is trial 2 with value: 0.8757141960321035.
[I 2026-08-26 21:41:03,947] Trial 14 finished with value: 0.8643311360775122 and parameters: {'max_depth': 8, 'learning_rate': 0.1748224970113755, 'subsample': 0.7251257998024343, 'colsample_bytree': 0.6067985020666221, 'min_child_weight': 0.5629506277333849, 'gamma': 0.7357192839349284, 'reg_alpha': 0.007366281502087388, 'reg_lambda': 15.167077457961938}. Best is trial 2 with value: 0.8757141960321035.
[I 2026-08-26 21:41:33,177] Trial 15 finished with value: 0.8721015760456575 and parameters: {'max_depth': 9, 'learning_rate': 0.19817774165410926, 'subsample': 0.8690856269930812, 'colsample_bytree': 0.6536074054839038, 'min_child_weight': 27.489547649192218, 'gamma': 0.014190871821646578, 'reg_alpha': 7.749040818304145e-07, 'reg_lambda': 11.633131249215683}. Best is trial 2 with value: 0.8757141960321035.
[I 2026-08-26 21:42:09,813] Trial 16 finished with value: 0.8675869372892585 and parameters: {'max_depth': 8, 'learning_rate': 0.13177796734730307, 'subsample': 0.8586927017191538, 'colsample_bytree': 0.6390519450381702, 'min_child_weight': 29.266819628702436, 'gamma': 0.020524823242183767, 'reg_alpha': 2.2588770720502548e-07, 'reg_lambda': 3.0830473334047306}. Best is trial 2 with value: 0.8757141960321035.
[I 2026-08-26 21:42:28,739] Trial 17 finished with value: 0.8812855328054052 and parameters: {'max_depth': 9, 'learning_rate': 0.11559880571167458, 'subsample': 0.8864095686072445, 'colsample_bytree': 0.7462766269481121, 'min_child_weight': 8.540761076488415, 'gamma': 0.262938132752185, 'reg_alpha': 2.172213690433863e-09, 'reg_lambda': 2.083558458304227}. Best is trial 17 with value: 0.8812855328054052.
[I 2026-08-26 21:42:42,437] Trial 18 finished with value: 0.836407468226269 and parameters: {'max_depth': 6, 'learning_rate': 0.0782463128351522, 'subsample': 0.7667214138864583, 'colsample_bytree': 0.7685876627442525, 'min_child_weight': 7.513754202666461, 'gamma': 1.4557408989094207, 'reg_alpha': 3.0898501493733272e-09, 'reg_lambda': 1.1357101578547972}. Best is trial 17 with value: 0.8812855328054052.
[I 2026-08-26 21:42:52,651] Trial 19 finished with value: 0.8339632602960775 and parameters: {'max_depth': 7, 'learning_rate': 0.13279314941400044, 'subsample': 0.9967124142755496, 'colsample_bytree': 0.8425310595120723, 'min_child_weight': 4.053989981004542, 'gamma': 0.7312884368852899, 'reg_alpha': 1.3760240810671025e-08, 'reg_lambda': 0.35425072033627353}. Best is trial 17 with value: 0.8812855328054052.
[I 2026-08-26 21:43:16,779] Trial 20 finished with value: 0.878500776038598 and parameters: {'max_depth': 9, 'learning_rate': 0.06418949709826452, 'subsample': 0.8681238025780942, 'colsample_bytree': 0.705568621452069, 'min_child_weight': 9.115994902439157, 'gamma': 0.31089772099195145, 'reg_alpha': 0.09095647740042732, 'reg_lambda': 2.2641434467107167}. Best is trial 17 with value: 0.8812855328054052.
[I 2026-08-26 21:43:37,269] Trial 21 finished with value: 0.8771058151709443 and parameters: {'max_depth': 9, 'learning_rate': 0.06857798114488887, 'subsample': 0.8782041330301507, 'colsample_bytree': 0.7156866437123837, 'min_child_weight': 8.748670161501403, 'gamma': 0.34181595694196115, 'reg_alpha': 0.48317265512657953, 'reg_lambda': 1.9422836377699944}. Best is trial 17 with value: 0.8812855328054052.
[I 2026-08-26 21:43:58,846] Trial 22 finished with value: 0.876101880728308 and parameters: {'max_depth': 9, 'learning_rate': 0.06651217468208913, 'subsample': 0.900149073766403, 'colsample_bytree': 0.739912759336613, 'min_child_weight': 11.554094959194167, 'gamma': 0.34106308655449113, 'reg_alpha': 0.15851927368239083, 'reg_lambda': 1.9222542302610328}. Best is trial 17 with value: 0.8812855328054052.
[I 2026-08-26 21:44:23,008] Trial 23 finished with value: 0.8814146930467521 and parameters: {'max_depth': 8, 'learning_rate': 0.10357567616016997, 'subsample': 0.8224550556193101, 'colsample_bytree': 0.8161400869086647, 'min_child_weight': 9.825653021639553, 'gamma': 0.2298959367723586, 'reg_alpha': 0.03367336652018941, 'reg_lambda': 1.616281742805327}. Best is trial 23 with value: 0.8814146930467521.
[I 2026-08-26 21:44:39,201] Trial 24 finished with value: 0.8659740328183275 and parameters: {'max_depth': 7, 'learning_rate': 0.10408414139034529, 'subsample': 0.8172555698933346, 'colsample_bytree': 0.8500368212761793, 'min_child_weight': 11.4194089410537, 'gamma': 0.6478612884614297, 'reg_alpha': 0.011601566918598627, 'reg_lambda': 0.6463820045841848}. Best is trial 23 with value: 0.8814146930467521.
[I 2026-08-26 21:45:20,071] Trial 25 finished with value: 0.8729576790809256 and parameters: {'max_depth': 8, 'learning_rate': 0.03376207213703955, 'subsample': 0.7615666242320015, 'colsample_bytree': 0.8156322899320291, 'min_child_weight': 16.79796399788668, 'gamma': 0.19348598583840332, 'reg_alpha': 0.0544165872863283, 'reg_lambda': 1.386114759754914}. Best is trial 23 with value: 0.8814146930467521.
[I 2026-08-26 21:45:33,613] Trial 26 finished with value: 0.8591352223258297 and parameters: {'max_depth': 8, 'learning_rate': 0.10264804653521425, 'subsample': 0.8380099865899632, 'colsample_bytree': 0.8981480418851177, 'min_child_weight': 3.707821157244363, 'gamma': 0.949955346389509, 'reg_alpha': 0.0003824362507556758, 'reg_lambda': 3.271475386017675}. Best is trial 23 with value: 0.8814146930467521.
[I 2026-08-26 21:46:01,276] Trial 27 finished with value: 0.8707749820159558 and parameters: {'max_depth': 7, 'learning_rate': 0.039562476336283556, 'subsample': 0.7895756603797992, 'colsample_bytree': 0.7600053655625387, 'min_child_weight': 5.984494598696171, 'gamma': 0.5912999703320375, 'reg_alpha': 0.0011105988818385128, 'reg_lambda': 0.6872518464735312}. Best is trial 23 with value: 0.8814146930467521.
[I 2026-08-26 21:46:33,289] Trial 28 finished with value: 0.8822125520233819 and parameters: {'max_depth': 9, 'learning_rate': 0.06440850471552748, 'subsample': 0.92788520711102, 'colsample_bytree': 0.9035571214411334, 'min_child_weight': 9.356929348314193, 'gamma': 0.16307760375610608, 'reg_alpha': 0.03078720565945149, 'reg_lambda': 1.7914082629340526}. Best is trial 28 with value: 0.8822125520233819.
[I 2026-08-26 21:46:54,629] Trial 29 finished with value: 0.8817149771347814 and parameters: {'max_depth': 9, 'learning_rate': 0.08240518340999604, 'subsample': 0.9241458984244015, 'colsample_bytree': 0.9177835330770112, 'min_child_weight': 10.099523253467344, 'gamma': 0.174106856033297, 'reg_alpha': 1.5900935063071773, 'reg_lambda': 1.4202338879009222}. Best is trial 28 with value: 0.8822125520233819.
[I 2026-08-26 21:47:19,080] Trial 30 finished with value: 0.8708627183295354 and parameters: {'max_depth': 6, 'learning_rate': 0.0867007426495319, 'subsample': 0.9213323604010056, 'colsample_bytree': 0.9256774211214311, 'min_child_weight': 18.52606494933626, 'gamma': 0.18922466229762414, 'reg_alpha': 0.912619853645507, 'reg_lambda': 0.2565511024442974}. Best is trial 28 with value: 0.8822125520233819.
[I 2026-08-26 21:47:33,630] Trial 31 finished with value: 0.8506917041211806 and parameters: {'max_depth': 9, 'learning_rate': 0.11321933353495126, 'subsample': 0.9521730931579598, 'colsample_bytree': 0.8900715317553145, 'min_child_weight': 11.870956011452801, 'gamma': 0.17942344583682485, 'reg_alpha': 7.899617664387512, 'reg_lambda': 1.5208346220440563}. Best is trial 28 with value: 0.8822125520233819.
[I 2026-08-26 21:47:49,724] Trial 32 finished with value: 0.8704026224300161 and parameters: {'max_depth': 8, 'learning_rate': 0.07423148918991787, 'subsample': 0.909675369976811, 'colsample_bytree': 0.942676755303653, 'min_child_weight': 2.898965829295511, 'gamma': 0.555079421282228, 'reg_alpha': 0.031315264630833645, 'reg_lambda': 0.9314326575690436}. Best is trial 28 with value: 0.8822125520233819.
[I 2026-08-26 21:48:09,196] Trial 33 finished with value: 0.8752479287777362 and parameters: {'max_depth': 9, 'learning_rate': 0.09241418546947341, 'subsample': 0.9626094209085595, 'colsample_bytree': 0.9103274874490116, 'min_child_weight': 9.89521112813443, 'gamma': 0.23043584594516697, 'reg_alpha': 0.0023840731945147815, 'reg_lambda': 4.02067526434441}. Best is trial 28 with value: 0.8822125520233819.
[I 2026-08-26 21:48:20,433] Trial 34 finished with value: 0.8579204289101637 and parameters: {'max_depth': 10, 'learning_rate': 0.1518842040197946, 'subsample': 0.9292978984893309, 'colsample_bytree': 0.86212959718046, 'min_child_weight': 6.099993119114918, 'gamma': 0.861013138183663, 'reg_alpha': 1.3727077453139833e-05, 'reg_lambda': 1.561814380642602}. Best is trial 28 with value: 0.8822125520233819.
[I 2026-08-26 21:48:37,944] Trial 35 finished with value: 0.8662801710165509 and parameters: {'max_depth': 8, 'learning_rate': 0.057010858584817074, 'subsample': 0.8944197818424651, 'colsample_bytree': 0.8100029298045003, 'min_child_weight': 4.570559446360607, 'gamma': 0.4764376888548519, 'reg_alpha': 1.7576291074546322, 'reg_lambda': 0.683470361192524}. Best is trial 28 with value: 0.8822125520233819.
[I 2026-08-26 21:49:13,739] Trial 36 finished with value: 0.8882106965408004 and parameters: {'max_depth': 9, 'learning_rate': 0.08982640409595438, 'subsample': 0.9673067055647784, 'colsample_bytree': 0.9817231978849792, 'min_child_weight': 6.792053069314797, 'gamma': 0.010605540133719948, 'reg_alpha': 4.132132693963929e-06, 'reg_lambda': 1.2355485254037823}. Best is trial 36 with value: 0.8882106965408004.
[I 2026-08-26 21:49:51,364] Trial 37 finished with value: 0.8716110993309781 and parameters: {'max_depth': 7, 'learning_rate': 0.08669917060972619, 'subsample': 0.962260182993426, 'colsample_bytree': 0.9818601919020656, 'min_child_weight': 23.283636956535414, 'gamma': 0.03782190750454989, 'reg_alpha': 0.02785340972067378, 'reg_lambda': 1.1957810589334728}. Best is trial 36 with value: 0.8882106965408004.
[I 2026-08-26 21:50:03,813] Trial 38 finished with value: 0.814529608327398 and parameters: {'max_depth': 10, 'learning_rate': 0.04541667453160724, 'subsample': 0.9787589022945167, 'colsample_bytree': 0.9477598757675095, 'min_child_weight': 13.524863151702444, 'gamma': 2.4823784489962373, 'reg_alpha': 6.308644008714772e-06, 'reg_lambda': 0.36602219292840216}. Best is trial 36 with value: 0.8882106965408004.
[I 2026-08-26 21:50:21,932] Trial 39 finished with value: 0.8699619869440898 and parameters: {'max_depth': 8, 'learning_rate': 0.057261058612808335, 'subsample': 0.9404280965666576, 'colsample_bytree': 0.8692875091984876, 'min_child_weight': 6.168735091929674, 'gamma': 0.42613754722450303, 'reg_alpha': 0.2528940634799023, 'reg_lambda': 0.4846101257736862}. Best is trial 36 with value: 0.8882106965408004.
[I 2026-08-26 21:50:42,070] Trial 40 finished with value: 0.884651333583062 and parameters: {'max_depth': 9, 'learning_rate': 0.07493170390880019, 'subsample': 0.9815306222155666, 'colsample_bytree': 0.999305161588293, 'min_child_weight': 3.4173088627354278, 'gamma': 0.1434293523944605, 'reg_alpha': 0.0033025400308090516, 'reg_lambda': 0.8460465685637126}. Best is trial 36 with value: 0.8882106965408004.
[I 2026-08-26 21:51:01,491] Trial 41 finished with value: 0.8846793920851432 and parameters: {'max_depth': 9, 'learning_rate': 0.07750280815349883, 'subsample': 0.9830228751428519, 'colsample_bytree': 0.9939012453038283, 'min_child_weight': 2.940326083666783, 'gamma': 0.14280316953901168, 'reg_alpha': 0.005261305923071801, 'reg_lambda': 0.9238191884439705}. Best is trial 36 with value: 0.8882106965408004.
[I 2026-08-26 21:51:22,745] Trial 42 finished with value: 0.8880148032140106 and parameters: {'max_depth': 9, 'learning_rate': 0.07917021352021131, 'subsample': 0.9795345021012682, 'colsample_bytree': 0.9965330569757932, 'min_child_weight': 2.732031486157331, 'gamma': 0.10642662702366446, 'reg_alpha': 0.004925234039702298, 'reg_lambda': 0.8971076251976886}. Best is trial 36 with value: 0.8882106965408004.
[I 2026-08-26 21:52:02,569] Trial 43 finished with value: 0.8918165359868387 and parameters: {'max_depth': 10, 'learning_rate': 0.0699730157356162, 'subsample': 0.9977750023987588, 'colsample_bytree': 0.9911399017919301, 'min_child_weight': 3.1022930402499185, 'gamma': 0.0020141758083612547, 'reg_alpha': 0.00030278344495877327, 'reg_lambda': 0.8628437661010019}. Best is trial 43 with value: 0.8918165359868387.
[I 2026-08-26 21:52:17,129] Trial 44 finished with value: 0.8682071670519009 and parameters: {'max_depth': 10, 'learning_rate': 0.07542502701628394, 'subsample': 0.9802210951745423, 'colsample_bytree': 0.9938659886774387, 'min_child_weight': 2.900549971149225, 'gamma': 0.45088535366267235, 'reg_alpha': 0.00021945822156636783, 'reg_lambda': 0.8625129728033897}. Best is trial 43 with value: 0.8918165359868387.
[I 2026-08-26 21:52:42,416] Trial 45 finished with value: 0.8930049985339764 and parameters: {'max_depth': 10, 'learning_rate': 0.0931596044337545, 'subsample': 0.9955847720590199, 'colsample_bytree': 0.9693441429495487, 'min_child_weight': 1.5190506219825952, 'gamma': 0.009640764574187222, 'reg_alpha': 0.002630213073400189, 'reg_lambda': 0.5256857088982793}. Best is trial 45 with value: 0.8930049985339764.
[I 2026-08-26 21:53:41,198] Trial 46 finished with value: 0.8918477990674966 and parameters: {'max_depth': 10, 'learning_rate': 0.023161487976618184, 'subsample': 0.9979825067170404, 'colsample_bytree': 0.9699538459387548, 'min_child_weight': 1.5256989948531683, 'gamma': 0.025822303300362462, 'reg_alpha': 0.0009422902166924894, 'reg_lambda': 0.11160501150690928}. Best is trial 45 with value: 0.8930049985339764.
[I 2026-08-26 21:54:48,464] Trial 47 finished with value: 0.8880719684609144 and parameters: {'max_depth': 10, 'learning_rate': 0.01582412540660521, 'subsample': 0.9965813909014373, 'colsample_bytree': 0.966911755204195, 'min_child_weight': 1.548098752405863, 'gamma': 0.04012072807287252, 'reg_alpha': 0.0008863958819334944, 'reg_lambda': 0.10527598360394627}. Best is trial 45 with value: 0.8930049985339764.

[5/6] Creating 80/20 split with 'mendota' completely held out.

[I 2026-08-26 23:52:31,754] A new study created in memory with name: DecisionTree_LOSO

[5/6] Running one 5-fold search per model.
  mendota: tuning Decision Tree (200 trials).

[I 2026-08-26 23:52:32,367] Trial 0 finished with value: 0.6553585863540555 and parameters: {'max_depth': 12, 'min_samples_split': 96, 'min_samples_leaf': 59, 'max_features': 0.6, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 1.3480180290890803e-07}. Best is trial 0 with value: 0.6553585863540555.
[I 2026-08-26 23:52:32,450] Trial 1 finished with value: 0.5548661393778292 and parameters: {'max_depth': 17, 'min_samples_split': 44, 'min_samples_leaf': 24, 'max_features': 0.8, 'criterion': 'log_loss', 'splitter': 'random', 'class_weight': None, 'ccp_alpha': 0.0043873144324354085}. Best is trial 0 with value: 0.6553585863540555.
[I 2026-08-26 23:52:32,481] Trial 2 finished with value: 0.5072259363337743 and parameters: {'max_depth': 30, 'min_samples_split': 82, 'min_samples_leaf': 25, 'max_features': 'sqrt', 'criterion': 'gini', 'splitter': 'random', 'class_weight': None, 'ccp_alpha': 0.006124806805925988}. Best is trial 0 with value: 0.6553585863540555.
[I 2026-08-26 23:52:32,691] Trial 3 finished with value: 0.6262011315441411 and parameters: {'max_depth': 24, 'min_samples_split': 95, 'min_samples_leaf': 72, 'max_features': 'sqrt', 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 0.00041245717727594227}. Best is trial 0 with value: 0.6553585863540555.
[I 2026-08-26 23:52:32,799] Trial 4 finished with value: 0.5681685851061552 and parameters: {'max_depth': 4, 'min_samples_split': 99, 'min_samples_leaf': 62, 'max_features': 'log2', 'criterion': 'entropy', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 1.5027137214154575e-07}. Best is trial 0 with value: 0.6553585863540555.
[I 2026-08-26 23:52:33,673] Trial 5 finished with value: 0.6558043406956037 and parameters: {'max_depth': 11, 'min_samples_split': 74, 'min_samples_leaf': 52, 'max_features': None, 'criterion': 'gini', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 2.8501838758433707e-05}. Best is trial 5 with value: 0.6558043406956037.
[I 2026-08-26 23:52:33,698] Trial 6 finished with value: 0.5610270892672088 and parameters: {'max_depth': 11, 'min_samples_split': 52, 'min_samples_leaf': 73, 'max_features': 'log2', 'criterion': 'entropy', 'splitter': 'random', 'class_weight': None, 'ccp_alpha': 0.0017697543538533224}. Best is trial 5 with value: 0.6558043406956037.
[I 2026-08-26 23:52:34,489] Trial 7 finished with value: 0.6587416876955358 and parameters: {'max_depth': 17, 'min_samples_split': 81, 'min_samples_leaf': 72, 'max_features': 0.8, 'criterion': 'entropy', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 1.8298712093870903e-07}. Best is trial 7 with value: 0.6587416876955358.
[I 2026-08-26 23:52:34,563] Trial 8 finished with value: 0.653221331056351 and parameters: {'max_depth': 17, 'min_samples_split': 71, 'min_samples_leaf': 30, 'max_features': None, 'criterion': 'entropy', 'splitter': 'random', 'class_weight': None, 'ccp_alpha': 1.0333896431462928e-08}. Best is trial 7 with value: 0.6587416876955358.
[I 2026-08-26 23:52:34,768] Trial 9 finished with value: 0.6557280847616954 and parameters: {'max_depth': 16, 'min_samples_split': 99, 'min_samples_leaf': 20, 'max_features': 'sqrt', 'criterion': 'gini', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 1.3685182782317289e-05}. Best is trial 7 with value: 0.6587416876955358.
[I 2026-08-26 23:52:34,928] Trial 10 finished with value: 0.5596050112696085 and parameters: {'max_depth': 3, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 0.4, 'criterion': 'entropy', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 1.3381271619726983e-09}. Best is trial 7 with value: 0.6587416876955358.
[I 2026-08-26 23:52:35,786] Trial 11 finished with value: 0.6336044652635934 and parameters: {'max_depth': 9, 'min_samples_split': 65, 'min_samples_leaf': 46, 'max_features': None, 'criterion': 'gini', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 7.780462950625712e-06}. Best is trial 7 with value: 0.6587416876955358.
[I 2026-08-26 23:52:36,543] Trial 12 finished with value: 0.6808379096104638 and parameters: {'max_depth': 22, 'min_samples_split': 41, 'min_samples_leaf': 47, 'max_features': 0.8, 'criterion': 'gini', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 5.88256804402977e-06}. Best is trial 12 with value: 0.6808379096104638.
[I 2026-08-26 23:52:37,249] Trial 13 finished with value: 0.6515428179546873 and parameters: {'max_depth': 22, 'min_samples_split': 24, 'min_samples_leaf': 80, 'max_features': 0.8, 'criterion': 'gini', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 7.808721364002951e-07}. Best is trial 12 with value: 0.6808379096104638.
[I 2026-08-26 23:52:38,152] Trial 14 finished with value: 0.686856353030452 and parameters: {'max_depth': 24, 'min_samples_split': 34, 'min_samples_leaf': 40, 'max_features': 0.8, 'criterion': 'entropy', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 8.169966361917122e-07}. Best is trial 14 with value: 0.686856353030452.
[I 2026-08-26 23:52:39,029] Trial 15 finished with value: 0.6924302403225706 and parameters: {'max_depth': 25, 'min_samples_split': 30, 'min_samples_leaf': 39, 'max_features': 0.8, 'criterion': 'entropy', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 1.981870083915325e-06}. Best is trial 15 with value: 0.6924302403225706.
[I 2026-08-26 23:52:39,924] Trial 16 finished with value: 0.6956177903898724 and parameters: {'max_depth': 29, 'min_samples_split': 23, 'min_samples_leaf': 37, 'max_features': 0.8, 'criterion': 'entropy', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 0.00010697124005528724}. Best is trial 16 with value: 0.6956177903898724.
[I 2026-08-26 23:52:40,355] Trial 17 finished with value: 0.6793143850226315 and parameters: {'max_depth': 30, 'min_samples_split': 17, 'min_samples_leaf': 37, 'max_features': 0.4, 'criterion': 'entropy', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 0.00014703801271882184}. Best is trial 16 with value: 0.6956177903898724.
[I 2026-08-26 23:52:40,434] Trial 18 finished with value: 0.6839529588838487 and parameters: {'max_depth': 27, 'min_samples_split': 8, 'min_samples_leaf': 10, 'max_features': 0.6, 'criterion': 'entropy', 'splitter': 'random', 'class_weight': 'balanced', 'ccp_alpha': 0.00013098976900088977}. Best is trial 16 with value: 0.6956177903898724.
[I 2026-08-26 23:52:41,337] Trial 19 finished with value: 0.6947267384275637 and parameters: {'max_depth': 27, 'min_samples_split': 26, 'min_samples_leaf': 35, 'max_features': 0.8, 'criterion': 'entropy', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 1.6799088957042346e-06}. Best is trial 16 with value: 0.6956177903898724.
[I 2026-08-26 23:52:42,257] Trial 20 finished with value: 0.6963543186708534 and parameters: {'max_depth': 27, 'min_samples_split': 15, 'min_samples_leaf': 32, 'max_features': 0.8, 'criterion': 'entropy', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 5.724815041812275e-05}. Best is trial 20 with value: 0.6963543186708534.
[I 2026-08-26 23:52:43,168] Trial 21 finished with value: 0.6965016138420471 and parameters: {'max_depth': 27, 'min_samples_split': 19, 'min_samples_leaf': 34, 'max_features': 0.8, 'criterion': 'entropy', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 8.018294994700074e-05}. Best is trial 21 with value: 0.6965016138420471.
[I 2026-08-26 23:52:44,163] Trial 22 finished with value: 0.7333490150843249 and parameters: {'max_depth': 28, 'min_samples_split': 16, 'min_samples_leaf': 15, 'max_features': 0.8, 'criterion': 'entropy', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 5.1904830858415424e-05}. Best is trial 22 with value: 0.7333490150843249.
[I 2026-08-26 23:52:45,218] Trial 23 finished with value: 0.7311894465736517 and parameters: {'max_depth': 20, 'min_samples_split': 13, 'min_samples_leaf': 11, 'max_features': 0.8, 'criterion': 'entropy', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 0.0008343607151346607}. Best is trial 22 with value: 0.7333490150843249.
[I 2026-08-26 23:52:46,242] Trial 24 finished with value: 0.726803637840609 and parameters: {'max_depth': 20, 'min_samples_split': 12, 'min_samples_leaf': 13, 'max_features': 0.8, 'criterion': 'entropy', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 0.000779453998595457}. Best is trial 22 with value: 0.7333490150843249.
[I 2026-08-26 23:52:47,264] Trial 25 finished with value: 0.7213568624434852 and parameters: {'max_depth': 19, 'min_samples_split': 9, 'min_samples_leaf': 14, 'max_features': 0.8, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 0.0008133987650164101}. Best is trial 22 with value: 0.7333490150843249.
[I 2026-08-26 23:52:47,377] Trial 26 finished with value: 0.6839930982263104 and parameters: {'max_depth': 20, 'min_samples_split': 9, 'min_samples_leaf': 3, 'max_features': 0.6, 'criterion': 'entropy', 'splitter': 'random', 'class_weight': 'balanced', 'ccp_alpha': 0.00046559637553929853}. Best is trial 22 with value: 0.7333490150843249.
[I 2026-08-26 23:52:47,843] Trial 27 finished with value: 0.6567885306200326 and parameters: {'max_depth': 14, 'min_samples_split': 34, 'min_samples_leaf': 11, 'max_features': 0.4, 'criterion': 'entropy', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 0.001562541631075915}. Best is trial 22 with value: 0.7333490150843249.
[I 2026-08-26 23:52:48,105] Trial 28 finished with value: 0.6934275803701685 and parameters: {'max_depth': 20, 'min_samples_split': 2, 'min_samples_leaf': 17, 'max_features': 'log2', 'criterion': 'entropy', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 0.0003227113474925329}. Best is trial 22 with value: 0.7333490150843249.
[I 2026-08-26 23:52:48,662] Trial 29 finished with value: 0.620869333885565 and parameters: {'max_depth': 8, 'min_samples_split': 14, 'min_samples_leaf': 7, 'max_features': 0.6, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 0.0018362693706525386}. Best is trial 22 with value: 0.7333490150843249.
[I 2026-08-26 23:52:49,620] Trial 30 finished with value: 0.5538694654383438 and parameters: {'max_depth': 14, 'min_samples_split': 43, 'min_samples_leaf': 21, 'max_features': 0.8, 'criterion': 'entropy', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 0.008450202429177014}. Best is trial 22 with value: 0.7333490150843249.
[I 2026-08-26 23:52:50,610] Trial 31 finished with value: 0.7216282653597912 and parameters: {'max_depth': 20, 'min_samples_split': 11, 'min_samples_leaf': 15, 'max_features': 0.8, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 0.0007457331540019733}. Best is trial 22 with value: 0.7333490150843249.
[I 2026-08-26 23:52:51,661] Trial 32 finished with value: 0.7502619439931529 and parameters: {'max_depth': 22, 'min_samples_split': 12, 'min_samples_leaf': 7, 'max_features': 0.8, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 2.564967935058499e-05}. Best is trial 32 with value: 0.7502619439931529.
[I 2026-08-26 23:52:52,711] Trial 33 finished with value: 0.7519063269133495 and parameters: {'max_depth': 22, 'min_samples_split': 21, 'min_samples_leaf': 6, 'max_features': 0.8, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 4.061567776345653e-05}. Best is trial 33 with value: 0.7519063269133495.
[I 2026-08-26 23:52:52,800] Trial 34 finished with value: 0.6989585208234838 and parameters: {'max_depth': 22, 'min_samples_split': 21, 'min_samples_leaf': 8, 'max_features': 0.8, 'criterion': 'log_loss', 'splitter': 'random', 'class_weight': 'balanced', 'ccp_alpha': 1.9845501204646827e-05}. Best is trial 33 with value: 0.7519063269133495.
[I 2026-08-26 23:52:53,057] Trial 35 finished with value: 0.6814941920475901 and parameters: {'max_depth': 24, 'min_samples_split': 52, 'min_samples_leaf': 25, 'max_features': 'sqrt', 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 4.423001177850657e-05}. Best is trial 33 with value: 0.7519063269133495.
[I 2026-08-26 23:52:54,125] Trial 36 finished with value: 0.7484197711515613 and parameters: {'max_depth': 25, 'min_samples_split': 29, 'min_samples_leaf': 4, 'max_features': 0.8, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 1.0919157335610923e-05}. Best is trial 33 with value: 0.7519063269133495.
[I 2026-08-26 23:52:54,207] Trial 37 finished with value: 0.6887117074398625 and parameters: {'max_depth': 25, 'min_samples_split': 30, 'min_samples_leaf': 5, 'max_features': 0.8, 'criterion': 'log_loss', 'splitter': 'random', 'class_weight': None, 'ccp_alpha': 4.237844268457373e-06}. Best is trial 33 with value: 0.7519063269133495.
[I 2026-08-26 23:52:54,454] Trial 38 finished with value: 0.6791925858183627 and parameters: {'max_depth': 29, 'min_samples_split': 38, 'min_samples_leaf': 27, 'max_features': 'log2', 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 1.6363134454174837e-05}. Best is trial 33 with value: 0.7519063269133495.
[I 2026-08-26 23:52:55,653] Trial 39 finished with value: 0.7156589641846363 and parameters: {'max_depth': 23, 'min_samples_split': 55, 'min_samples_leaf': 19, 'max_features': None, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 2.8130373852924847e-06}. Best is trial 33 with value: 0.7519063269133495.
[I 2026-08-26 23:52:55,701] Trial 40 finished with value: 0.6762994853642877 and parameters: {'max_depth': 26, 'min_samples_split': 29, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'criterion': 'log_loss', 'splitter': 'random', 'class_weight': 'balanced', 'ccp_alpha': 4.5056250008776727e-07}. Best is trial 33 with value: 0.7519063269133495.
[I 2026-08-26 23:52:56,783] Trial 41 finished with value: 0.7546671152547192 and parameters: {'max_depth': 18, 'min_samples_split': 17, 'min_samples_leaf': 5, 'max_features': 0.8, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 3.018755482356877e-05}. Best is trial 41 with value: 0.7546671152547192.
[I 2026-08-26 23:52:57,833] Trial 42 finished with value: 0.74960678091365 and parameters: {'max_depth': 18, 'min_samples_split': 19, 'min_samples_leaf': 8, 'max_features': 0.8, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 2.9044729378373537e-05}. Best is trial 41 with value: 0.7546671152547192.
[I 2026-08-26 23:52:58,927] Trial 43 finished with value: 0.7520676383310747 and parameters: {'max_depth': 18, 'min_samples_split': 5, 'min_samples_leaf': 6, 'max_features': 0.8, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 2.810539698884863e-05}. Best is trial 41 with value: 0.7546671152547192.
[I 2026-08-26 23:52:59,951] Trial 44 finished with value: 0.7511829751731331 and parameters: {'max_depth': 18, 'min_samples_split': 5, 'min_samples_leaf': 7, 'max_features': 0.8, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 0.00023585448574495223}. Best is trial 41 with value: 0.7546671152547192.
[I 2026-08-26 23:53:00,952] Trial 45 finished with value: 0.7425716638108535 and parameters: {'max_depth': 15, 'min_samples_split': 6, 'min_samples_leaf': 5, 'max_features': 0.8, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 0.00019047328027897028}. Best is trial 41 with value: 0.7546671152547192.
[I 2026-08-26 23:53:02,258] Trial 46 finished with value: 0.7561333330510238 and parameters: {'max_depth': 18, 'min_samples_split': 3, 'min_samples_leaf': 8, 'max_features': None, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 0.00022515464222252658}. Best is trial 46 with value: 0.7561333330510238.
[I 2026-08-26 23:53:03,641] Trial 47 finished with value: 0.5908017736719675 and parameters: {'max_depth': 18, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': None, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 0.004104035366052291}. Best is trial 46 with value: 0.7561333330510238.
[I 2026-08-26 23:53:04,835] Trial 48 finished with value: 0.7203345577479862 and parameters: {'max_depth': 16, 'min_samples_split': 2, 'min_samples_leaf': 21, 'max_features': None, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 0.00025592524549474145}. Best is trial 46 with value: 0.7561333330510238.
[I 2026-08-26 23:53:06,007] Trial 49 finished with value: 0.7079100627666056 and parameters: {'max_depth': 12, 'min_samples_split': 6, 'min_samples_leaf': 10, 'max_features': None, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 8.545769347826296e-06}. Best is trial 46 with value: 0.7561333330510238.
[I 2026-08-26 23:53:07,264] Trial 50 finished with value: 0.7291924930435184 and parameters: {'max_depth': 17, 'min_samples_split': 22, 'min_samples_leaf': 17, 'max_features': None, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 0.00010121974731458862}. Best is trial 46 with value: 0.7561333330510238.
[I 2026-08-26 23:53:07,767] Trial 51 finished with value: 0.7383751331767916 and parameters: {'max_depth': 21, 'min_samples_split': 10, 'min_samples_leaf': 7, 'max_features': 0.4, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 2.9449165287914546e-05}. Best is trial 46 with value: 0.7561333330510238.
[I 2026-08-26 23:53:08,048] Trial 52 finished with value: 0.7203341508083483 and parameters: {'max_depth': 18, 'min_samples_split': 6, 'min_samples_leaf': 4, 'max_features': 'log2', 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 4.0821118481749396e-05}. Best is trial 46 with value: 0.7561333330510238.
[I 2026-08-26 23:53:09,031] Trial 53 finished with value: 0.7329446472428012 and parameters: {'max_depth': 16, 'min_samples_split': 17, 'min_samples_leaf': 11, 'max_features': 0.8, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 6.808115462528129e-08}. Best is trial 46 with value: 0.7561333330510238.
[I 2026-08-26 23:53:09,255] Trial 54 finished with value: 0.6687457535032698 and parameters: {'max_depth': 22, 'min_samples_split': 90, 'min_samples_leaf': 7, 'max_features': 'sqrt', 'criterion': 'gini', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 1.704183342263618e-05}. Best is trial 46 with value: 0.7561333330510238.
[I 2026-08-26 23:53:10,180] Trial 55 finished with value: 0.7186821326934602 and parameters: {'max_depth': 13, 'min_samples_split': 25, 'min_samples_leaf': 13, 'max_features': 0.8, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 7.866735789771315e-05}. Best is trial 46 with value: 0.7561333330510238.
[I 2026-08-26 23:53:10,990] Trial 56 finished with value: 0.7494429903048302 and parameters: {'max_depth': 19, 'min_samples_split': 13, 'min_samples_leaf': 1, 'max_features': 0.6, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 0.0001759975587891604}. Best is trial 46 with value: 0.7561333330510238.
[I 2026-08-26 23:53:11,070] Trial 57 finished with value: 0.6693540306497398 and parameters: {'max_depth': 23, 'min_samples_split': 5, 'min_samples_leaf': 17, 'max_features': 0.8, 'criterion': 'log_loss', 'splitter': 'random', 'class_weight': 'balanced', 'ccp_alpha': 0.0003742883683594934}. Best is trial 46 with value: 0.7561333330510238.
[I 2026-08-26 23:53:12,201] Trial 58 finished with value: 0.7478602616289469 and parameters: {'max_depth': 21, 'min_samples_split': 18, 'min_samples_leaf': 10, 'max_features': None, 'criterion': 'gini', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 7.3547682145448425e-06}. Best is trial 46 with value: 0.7561333330510238.

  mendota: tuning Random Forest (200 trials).

[I 2026-08-26 23:56:13,386] Trial 0 finished with value: 0.8079387017336854 and parameters: {'n_estimators': 300, 'max_depth': 32, 'min_samples_split': 3, 'min_samples_leaf': 15, 'max_features': 0.7, 'bootstrap': True, 'criterion': 'log_loss', 'class_weight': None}. Best is trial 0 with value: 0.8079387017336854.
[I 2026-08-26 23:56:24,328] Trial 1 finished with value: 0.7797815416509644 and parameters: {'n_estimators': 600, 'max_depth': 16, 'min_samples_split': 20, 'min_samples_leaf': 13, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'gini', 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8079387017336854.
[I 2026-08-26 23:56:59,459] Trial 2 finished with value: 0.6869162115321914 and parameters: {'n_estimators': 600, 'max_depth': 8, 'min_samples_split': 28, 'min_samples_leaf': 15, 'max_features': 0.7, 'bootstrap': True, 'criterion': 'entropy', 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8079387017336854.
[I 2026-08-26 23:57:27,730] Trial 3 finished with value: 0.7922159070523682 and parameters: {'n_estimators': 800, 'max_depth': 24, 'min_samples_split': 25, 'min_samples_leaf': 20, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'log_loss', 'class_weight': None}. Best is trial 0 with value: 0.8079387017336854.
[I 2026-08-26 23:57:49,985] Trial 4 finished with value: 0.7757903459100138 and parameters: {'n_estimators': 1000, 'max_depth': 16, 'min_samples_split': 31, 'min_samples_leaf': 15, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy', 'class_weight': None}. Best is trial 0 with value: 0.8079387017336854.
[I 2026-08-26 23:58:26,392] Trial 5 finished with value: 0.8485377988444963 and parameters: {'n_estimators': 800, 'max_depth': 48, 'min_samples_split': 18, 'min_samples_leaf': 3, 'max_features': 0.3, 'bootstrap': False, 'criterion': 'gini', 'class_weight': 'balanced'}. Best is trial 5 with value: 0.8485377988444963.
[I 2026-08-26 23:58:51,602] Trial 6 finished with value: 0.8211442723800781 and parameters: {'n_estimators': 400, 'max_depth': 48, 'min_samples_split': 34, 'min_samples_leaf': 1, 'max_features': 0.5, 'bootstrap': True, 'criterion': 'entropy', 'class_weight': 'balanced'}. Best is trial 5 with value: 0.8485377988444963.
[I 2026-08-26 23:59:44,798] Trial 7 finished with value: 0.8200060537421251 and parameters: {'n_estimators': 1000, 'max_depth': 32, 'min_samples_split': 19, 'min_samples_leaf': 15, 'max_features': 0.3, 'bootstrap': False, 'criterion': 'log_loss', 'class_weight': 'balanced'}. Best is trial 5 with value: 0.8485377988444963.
[I 2026-08-27 00:01:50,712] Trial 8 finished with value: 0.7218438484098519 and parameters: {'n_estimators': 900, 'max_depth': 24, 'min_samples_split': 40, 'min_samples_leaf': 19, 'max_features': 1.0, 'bootstrap': False, 'criterion': 'gini', 'class_weight': 'balanced_subsample'}. Best is trial 5 with value: 0.8485377988444963.
[I 2026-08-27 00:02:27,486] Trial 9 finished with value: 0.8617510634496609 and parameters: {'n_estimators': 600, 'max_depth': None, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 0.3, 'bootstrap': False, 'criterion': 'log_loss', 'class_weight': 'balanced_subsample'}. Best is trial 9 with value: 0.8617510634496609.
[I 2026-08-27 00:02:47,249] Trial 10 finished with value: 0.8371053069360942 and parameters: {'n_estimators': 500, 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 7, 'max_features': 'log2', 'bootstrap': False, 'criterion': 'log_loss', 'class_weight': 'balanced_subsample'}. Best is trial 9 with value: 0.8617510634496609.
[I 2026-08-27 00:03:20,947] Trial 11 finished with value: 0.8573333470952615 and parameters: {'n_estimators': 700, 'max_depth': 48, 'min_samples_split': 12, 'min_samples_leaf': 1, 'max_features': 0.3, 'bootstrap': False, 'criterion': 'gini', 'class_weight': 'balanced_subsample'}. Best is trial 9 with value: 0.8617510634496609.
[I 2026-08-27 00:03:48,281] Trial 12 finished with value: 0.7984065704508485 and parameters: {'n_estimators': 700, 'max_depth': 12, 'min_samples_split': 11, 'min_samples_leaf': 5, 'max_features': 0.3, 'bootstrap': False, 'criterion': 'gini', 'class_weight': 'balanced_subsample'}. Best is trial 9 with value: 0.8617510634496609.
[I 2026-08-27 00:04:24,969] Trial 13 finished with value: 0.8608149862464064 and parameters: {'n_estimators': 600, 'max_depth': None, 'min_samples_split': 11, 'min_samples_leaf': 1, 'max_features': 0.3, 'bootstrap': False, 'criterion': 'log_loss', 'class_weight': 'balanced_subsample'}. Best is trial 9 with value: 0.8617510634496609.
[I 2026-08-27 00:04:53,282] Trial 14 finished with value: 0.843778998222659 and parameters: {'n_estimators': 500, 'max_depth': None, 'min_samples_split': 9, 'min_samples_leaf': 8, 'max_features': 0.3, 'bootstrap': False, 'criterion': 'log_loss', 'class_weight': 'balanced_subsample'}. Best is trial 9 with value: 0.8617510634496609.
[I 2026-08-27 00:05:45,898] Trial 15 finished with value: 0.8651108493569024 and parameters: {'n_estimators': 500, 'max_depth': None, 'min_samples_split': 7, 'min_samples_leaf': 4, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'log_loss', 'class_weight': 'balanced_subsample'}. Best is trial 15 with value: 0.8651108493569024.
[I 2026-08-27 00:06:16,194] Trial 16 finished with value: 0.8472248494562462 and parameters: {'n_estimators': 300, 'max_depth': None, 'min_samples_split': 6, 'min_samples_leaf': 9, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'log_loss', 'class_weight': 'balanced_subsample'}. Best is trial 15 with value: 0.8651108493569024.
[I 2026-08-27 00:06:58,188] Trial 17 finished with value: 0.8569981895822728 and parameters: {'n_estimators': 400, 'max_depth': None, 'min_samples_split': 16, 'min_samples_leaf': 4, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'log_loss', 'class_weight': 'balanced_subsample'}. Best is trial 15 with value: 0.8651108493569024.
[I 2026-08-27 00:07:11,397] Trial 18 finished with value: 0.676447676465042 and parameters: {'n_estimators': 500, 'max_depth': 8, 'min_samples_split': 7, 'min_samples_leaf': 6, 'max_features': 'log2', 'bootstrap': False, 'criterion': 'log_loss', 'class_weight': 'balanced_subsample'}. Best is trial 15 with value: 0.8651108493569024.
[I 2026-08-27 00:08:22,970] Trial 19 finished with value: 0.7136584571040443 and parameters: {'n_estimators': 400, 'max_depth': 12, 'min_samples_split': 15, 'min_samples_leaf': 10, 'max_features': 1.0, 'bootstrap': False, 'criterion': 'log_loss', 'class_weight': 'balanced_subsample'}. Best is trial 15 with value: 0.8651108493569024.
[I 2026-08-27 00:09:35,914] Trial 20 finished with value: 0.8689628538531503 and parameters: {'n_estimators': 700, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 3, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8689628538531503.
[I 2026-08-27 00:10:48,749] Trial 21 finished with value: 0.8689628538531503 and parameters: {'n_estimators': 700, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 3, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8689628538531503.
[I 2026-08-27 00:12:01,857] Trial 22 finished with value: 0.8689628538531503 and parameters: {'n_estimators': 700, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 3, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8689628538531503.
[I 2026-08-27 00:13:25,601] Trial 23 finished with value: 0.8690244868967678 and parameters: {'n_estimators': 800, 'max_depth': None, 'min_samples_split': 3, 'min_samples_leaf': 3, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 23 with value: 0.8690244868967678.
[I 2026-08-27 00:14:48,774] Trial 24 finished with value: 0.8690244868967678 and parameters: {'n_estimators': 800, 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 3, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 23 with value: 0.8690244868967678.
[I 2026-08-27 00:16:09,234] Trial 25 finished with value: 0.8573369438769219 and parameters: {'n_estimators': 800, 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 6, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 23 with value: 0.8690244868967678.
[I 2026-08-27 00:17:04,920] Trial 26 finished with value: 0.8452599206369611 and parameters: {'n_estimators': 900, 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 5, 'max_features': 0.5, 'bootstrap': True, 'criterion': 'entropy', 'class_weight': None}. Best is trial 23 with value: 0.8690244868967678.
[I 2026-08-27 00:18:24,129] Trial 27 finished with value: 0.8023932661484812 and parameters: {'n_estimators': 900, 'max_depth': 12, 'min_samples_split': 8, 'min_samples_leaf': 11, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 23 with value: 0.8690244868967678.
[I 2026-08-27 00:19:44,128] Trial 28 finished with value: 0.8555837484317952 and parameters: {'n_estimators': 800, 'max_depth': 16, 'min_samples_split': 13, 'min_samples_leaf': 3, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 23 with value: 0.8690244868967678.
[I 2026-08-27 00:20:57,035] Trial 29 finished with value: 0.8384656676617575 and parameters: {'n_estimators': 900, 'max_depth': 32, 'min_samples_split': 4, 'min_samples_leaf': 7, 'max_features': 0.7, 'bootstrap': True, 'criterion': 'entropy', 'class_weight': None}. Best is trial 23 with value: 0.8690244868967678.
[I 2026-08-27 00:21:51,418] Trial 30 finished with value: 0.690159151959606 and parameters: {'n_estimators': 800, 'max_depth': 8, 'min_samples_split': 4, 'min_samples_leaf': 2, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 23 with value: 0.8690244868967678.
[I 2026-08-27 00:23:06,105] Trial 31 finished with value: 0.8659026475288227 and parameters: {'n_estimators': 700, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 4, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 23 with value: 0.8690244868967678.
[I 2026-08-27 00:24:21,142] Trial 32 finished with value: 0.8679116261995524 and parameters: {'n_estimators': 700, 'max_depth': None, 'min_samples_split': 8, 'min_samples_leaf': 3, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 23 with value: 0.8690244868967678.
[I 2026-08-27 00:25:56,723] Trial 33 finished with value: 0.8570801083815709 and parameters: {'n_estimators': 700, 'max_depth': None, 'min_samples_split': 4, 'min_samples_leaf': 5, 'max_features': 0.7, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 23 with value: 0.8690244868967678.
[I 2026-08-27 00:26:48,659] Trial 34 finished with value: 0.8591558823346069 and parameters: {'n_estimators': 800, 'max_depth': 32, 'min_samples_split': 2, 'min_samples_leaf': 2, 'max_features': 0.5, 'bootstrap': True, 'criterion': 'entropy', 'class_weight': None}. Best is trial 23 with value: 0.8690244868967678.
[I 2026-08-27 00:27:12,669] Trial 35 finished with value: 0.8350716324499701 and parameters: {'n_estimators': 600, 'max_depth': 24, 'min_samples_split': 22, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 23 with value: 0.8690244868967678.
[I 2026-08-27 00:27:31,747] Trial 36 finished with value: 0.8104659153499206 and parameters: {'n_estimators': 800, 'max_depth': 16, 'min_samples_split': 6, 'min_samples_leaf': 6, 'max_features': 'log2', 'bootstrap': True, 'criterion': 'entropy', 'class_weight': None}. Best is trial 23 with value: 0.8690244868967678.
[I 2026-08-27 00:30:30,563] Trial 37 finished with value: 0.7673601376859244 and parameters: {'n_estimators': 900, 'max_depth': None, 'min_samples_split': 14, 'min_samples_leaf': 4, 'max_features': 1.0, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 23 with value: 0.8690244868967678.
[I 2026-08-27 00:30:46,425] Trial 38 finished with value: 0.6785853581197806 and parameters: {'n_estimators': 600, 'max_depth': 8, 'min_samples_split': 9, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'entropy', 'class_weight': 'balanced'}. Best is trial 23 with value: 0.8690244868967678.
[I 2026-08-27 00:31:46,759] Trial 39 finished with value: 0.8357180439949881 and parameters: {'n_estimators': 1000, 'max_depth': 24, 'min_samples_split': 4, 'min_samples_leaf': 7, 'max_features': 0.5, 'bootstrap': True, 'criterion': 'entropy', 'class_weight': None}. Best is trial 23 with value: 0.8690244868967678.
[I 2026-08-27 00:33:39,036] Trial 40 finished with value: 0.8647065368595708 and parameters: {'n_estimators': 800, 'max_depth': 48, 'min_samples_split': 6, 'min_samples_leaf': 3, 'max_features': 0.7, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 23 with value: 0.8690244868967678.
[I 2026-08-27 00:34:51,921] Trial 41 finished with value: 0.8689628538531503 and parameters: {'n_estimators': 700, 'max_depth': None, 'min_samples_split': 6, 'min_samples_leaf': 3, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 23 with value: 0.8690244868967678.
[I 2026-08-27 00:36:04,002] Trial 42 finished with value: 0.8659026475288227 and parameters: {'n_estimators': 700, 'max_depth': None, 'min_samples_split': 4, 'min_samples_leaf': 4, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 23 with value: 0.8690244868967678.
[I 2026-08-27 00:37:08,086] Trial 43 finished with value: 0.8172816592968133 and parameters: {'n_estimators': 700, 'max_depth': None, 'min_samples_split': 10, 'min_samples_leaf': 18, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 23 with value: 0.8690244868967678.
[I 2026-08-27 00:38:16,155] Trial 44 finished with value: 0.8673149094354626 and parameters: {'n_estimators': 800, 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'gini', 'class_weight': 'balanced'}. Best is trial 23 with value: 0.8690244868967678.
[I 2026-08-27 00:39:17,252] Trial 45 finished with value: 0.861374562163147 and parameters: {'n_estimators': 600, 'max_depth': None, 'min_samples_split': 8, 'min_samples_leaf': 5, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 23 with value: 0.8690244868967678.
[I 2026-08-27 00:40:25,485] Trial 46 finished with value: 0.8291758845194058 and parameters: {'n_estimators': 700, 'max_depth': 16, 'min_samples_split': 40, 'min_samples_leaf': 2, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 23 with value: 0.8690244868967678.
[I 2026-08-27 00:41:58,785] Trial 47 finished with value: 0.7406441078875265 and parameters: {'n_estimators': 600, 'max_depth': None, 'min_samples_split': 37, 'min_samples_leaf': 3, 'max_features': 1.0, 'bootstrap': False, 'criterion': 'gini', 'class_weight': 'balanced'}. Best is trial 23 with value: 0.8690244868967678.
[I 2026-08-27 00:42:34,363] Trial 48 finished with value: 0.8294319998864472 and parameters: {'n_estimators': 900, 'max_depth': 48, 'min_samples_split': 28, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 23 with value: 0.8690244868967678.
[I 2026-08-27 00:43:06,166] Trial 49 finished with value: 0.8416190667938193 and parameters: {'n_estimators': 800, 'max_depth': 32, 'min_samples_split': 12, 'min_samples_leaf': 5, 'max_features': 'log2', 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 23 with value: 0.8690244868967678.
[I 2026-08-27 00:43:38,389] Trial 50 finished with value: 0.823878742492874 and parameters: {'n_estimators': 700, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 8, 'max_features': 0.5, 'bootstrap': True, 'criterion': 'gini', 'class_weight': None}. Best is trial 23 with value: 0.8690244868967678.
[I 2026-08-27 00:44:51,288] Trial 51 finished with value: 0.8689628538531503 and parameters: {'n_estimators': 700, 'max_depth': None, 'min_samples_split': 6, 'min_samples_leaf': 3, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 23 with value: 0.8690244868967678.
[I 2026-08-27 00:46:04,208] Trial 52 finished with value: 0.8689628538531503 and parameters: {'n_estimators': 700, 'max_depth': None, 'min_samples_split': 3, 'min_samples_leaf': 3, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 23 with value: 0.8690244868967678.
[I 2026-08-27 00:47:05,794] Trial 53 finished with value: 0.8659276352260867 and parameters: {'n_estimators': 600, 'max_depth': None, 'min_samples_split': 7, 'min_samples_leaf': 4, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 23 with value: 0.8690244868967678.
[I 2026-08-27 00:48:29,817] Trial 54 finished with value: 0.8680178444130486 and parameters: {'n_estimators': 800, 'max_depth': None, 'min_samples_split': 10, 'min_samples_leaf': 2, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 23 with value: 0.8690244868967678.
[I 2026-08-27 00:49:32,490] Trial 55 finished with value: 0.8130548860402204 and parameters: {'n_estimators': 700, 'max_depth': 12, 'min_samples_split': 5, 'min_samples_leaf': 6, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 23 with value: 0.8690244868967678.
[I 2026-08-27 00:50:59,696] Trial 56 finished with value: 0.8733681785024416 and parameters: {'n_estimators': 800, 'max_depth': None, 'min_samples_split': 3, 'min_samples_leaf': 1, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': 'balanced'}. Best is trial 56 with value: 0.8733681785024416.
[I 2026-08-27 00:52:27,196] Trial 57 finished with value: 0.8738380472245174 and parameters: {'n_estimators': 800, 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': 'balanced'}. Best is trial 57 with value: 0.8738380472245174.
[I 2026-08-27 00:53:23,093] Trial 58 finished with value: 0.8677367932329748 and parameters: {'n_estimators': 900, 'max_depth': 24, 'min_samples_split': 3, 'min_samples_leaf': 1, 'max_features': 0.3, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': 'balanced'}. Best is trial 57 with value: 0.8738380472245174.
[I 2026-08-27 00:54:39,566] Trial 59 finished with value: 0.867289626809875 and parameters: {'n_estimators': 900, 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'gini', 'class_weight': 'balanced'}. Best is trial 57 with value: 0.8738380472245174.
[I 2026-08-27 00:56:27,744] Trial 60 finished with value: 0.6265831114316098 and parameters: {'n_estimators': 800, 'max_depth': 8, 'min_samples_split': 3, 'min_samples_leaf': 2, 'max_features': 1.0, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': 'balanced'}. Best is trial 57 with value: 0.8738380472245174.
[I 2026-08-27 00:57:54,233] Trial 61 finished with value: 0.8721956782467413 and parameters: {'n_estimators': 800, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 2, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': 'balanced'}. Best is trial 57 with value: 0.8738380472245174.

  mendota: tuning XGBoost (200 trials).

[I 2026-08-27 04:41:15,575] Trial 0 finished with value: 0.8309371670651698 and parameters: {'max_depth': 9, 'learning_rate': 0.019677977348166304, 'subsample': 0.8978561926718072, 'colsample_bytree': 0.7442003345025142, 'min_child_weight': 2.1771032186203514, 'gamma': 1.8277151418544553, 'reg_alpha': 8.665537597324885e-06, 'reg_lambda': 1.0311514495138399}. Best is trial 0 with value: 0.8309371670651698.
[I 2026-08-27 04:41:30,900] Trial 1 finished with value: 0.8499635522299238 and parameters: {'max_depth': 7, 'learning_rate': 0.09439831569936806, 'subsample': 0.9842104900822669, 'colsample_bytree': 0.7826484435755748, 'min_child_weight': 2.880043790954131, 'gamma': 0.3403911033599112, 'reg_alpha': 1.5100408408589772e-07, 'reg_lambda': 23.538263110950048}. Best is trial 1 with value: 0.8499635522299238.
[I 2026-08-27 04:41:47,191] Trial 2 finished with value: 0.8705289719295306 and parameters: {'max_depth': 10, 'learning_rate': 0.14726161255504092, 'subsample': 0.8585642249613574, 'colsample_bytree': 0.6855299248522434, 'min_child_weight': 6.781935357780796, 'gamma': 0.41743875595471047, 'reg_alpha': 3.864031899313156e-05, 'reg_lambda': 14.610499699549097}. Best is trial 2 with value: 0.8705289719295306.
[I 2026-08-27 04:42:02,956] Trial 3 finished with value: 0.84684086783254 and parameters: {'max_depth': 5, 'learning_rate': 0.08394754752250128, 'subsample': 0.9450697344147837, 'colsample_bytree': 0.6595392252176876, 'min_child_weight': 5.011643571251018, 'gamma': 0.4774657914394431, 'reg_alpha': 5.357340695323986e-08, 'reg_lambda': 0.18099954688158187}. Best is trial 2 with value: 0.8705289719295306.
[I 2026-08-27 04:42:18,621] Trial 4 finished with value: 0.7998871006231227 and parameters: {'max_depth': 4, 'learning_rate': 0.048769840070943336, 'subsample': 0.9178299664912868, 'colsample_bytree': 0.9963290723923126, 'min_child_weight': 13.502442798764482, 'gamma': 1.1322462171492673, 'reg_alpha': 0.00014367270092871558, 'reg_lambda': 0.1399264351773497}. Best is trial 2 with value: 0.8705289719295306.
[I 2026-08-27 04:42:36,876] Trial 5 finished with value: 0.7868993525630612 and parameters: {'max_depth': 8, 'learning_rate': 0.018099146987238985, 'subsample': 0.953044632771952, 'colsample_bytree': 0.8904231274266234, 'min_child_weight': 15.164258427643505, 'gamma': 2.130692051488852, 'reg_alpha': 0.009425386803829051, 'reg_lambda': 20.136195700340338}. Best is trial 2 with value: 0.8705289719295306.
[I 2026-08-27 04:43:10,096] Trial 6 finished with value: 0.8400498956270003 and parameters: {'max_depth': 10, 'learning_rate': 0.01918354750824495, 'subsample': 0.782598566894961, 'colsample_bytree': 0.7970893967426577, 'min_child_weight': 0.7811624819629674, 'gamma': 0.46120338258524907, 'reg_alpha': 6.963704487425356, 'reg_lambda': 0.47063847559435423}. Best is trial 2 with value: 0.8705289719295306.
[I 2026-08-27 04:43:34,020] Trial 7 finished with value: 0.8524069854188573 and parameters: {'max_depth': 10, 'learning_rate': 0.022953302153308094, 'subsample': 0.6529433178954122, 'colsample_bytree': 0.7269413610677277, 'min_child_weight': 1.7604099383967902, 'gamma': 1.266165560263202, 'reg_alpha': 2.041568273325791e-06, 'reg_lambda': 2.5538276254965817}. Best is trial 2 with value: 0.8705289719295306.
[I 2026-08-27 04:43:52,996] Trial 8 finished with value: 0.825698853754715 and parameters: {'max_depth': 3, 'learning_rate': 0.11851328676362981, 'subsample': 0.7074625481911713, 'colsample_bytree': 0.9645659651689448, 'min_child_weight': 20.063522776432464, 'gamma': 0.047573401053791486, 'reg_alpha': 0.34420918881100815, 'reg_lambda': 4.715832950352583}. Best is trial 2 with value: 0.8705289719295306.
[I 2026-08-27 04:44:07,822] Trial 9 finished with value: 0.725322325680499 and parameters: {'max_depth': 3, 'learning_rate': 0.033391708755025735, 'subsample': 0.8256997968048689, 'colsample_bytree': 0.837631051781117, 'min_child_weight': 8.12005959578132, 'gamma': 1.8972954750065205, 'reg_alpha': 2.437950567013768, 'reg_lambda': 6.697837558293906}. Best is trial 2 with value: 0.8705289719295306.
[I 2026-08-27 04:44:17,909] Trial 10 finished with value: 0.7806728194152078 and parameters: {'max_depth': 6, 'learning_rate': 0.17115128841996644, 'subsample': 0.8154186866999962, 'colsample_bytree': 0.6025554256995838, 'min_child_weight': 0.8625345056254972, 'gamma': 2.9869578392012968, 'reg_alpha': 1.239446148413562e-09, 'reg_lambda': 0.9684799729031198}. Best is trial 2 with value: 0.8705289719295306.
[I 2026-08-27 04:44:38,317] Trial 11 finished with value: 0.855577405767691 and parameters: {'max_depth': 10, 'learning_rate': 0.04809950013571818, 'subsample': 0.6132599083973347, 'colsample_bytree': 0.7068708218135153, 'min_child_weight': 2.000151976177787, 'gamma': 1.1015819037394388, 'reg_alpha': 4.514632609962317e-05, 'reg_lambda': 5.019540607508096}. Best is trial 2 with value: 0.8705289719295306.
[I 2026-08-27 04:44:58,682] Trial 12 finished with value: 0.8523819630924319 and parameters: {'max_depth': 9, 'learning_rate': 0.05449774578204275, 'subsample': 0.6446773085991204, 'colsample_bytree': 0.6782743329282878, 'min_child_weight': 5.024974615071706, 'gamma': 1.0252076108694772, 'reg_alpha': 0.0009910433108845519, 'reg_lambda': 8.210034909208419}. Best is trial 2 with value: 0.8705289719295306.
[I 2026-08-27 04:45:15,088] Trial 13 finished with value: 0.8621288094084342 and parameters: {'max_depth': 10, 'learning_rate': 0.19639010434181664, 'subsample': 0.6021768360536973, 'colsample_bytree': 0.6725320077667093, 'min_child_weight': 1.334503164197373, 'gamma': 0.7848649789462945, 'reg_alpha': 6.501336646332095e-05, 'reg_lambda': 11.389015447500912}. Best is trial 2 with value: 0.8705289719295306.
[I 2026-08-27 04:45:30,256] Trial 14 finished with value: 0.8594792985887171 and parameters: {'max_depth': 8, 'learning_rate': 0.1748224970113755, 'subsample': 0.7251257998024343, 'colsample_bytree': 0.6067985020666221, 'min_child_weight': 0.5629506277333849, 'gamma': 0.7357192839349284, 'reg_alpha': 0.007366281502087388, 'reg_lambda': 15.167077457961938}. Best is trial 2 with value: 0.8705289719295306.
[I 2026-08-27 04:45:59,397] Trial 15 finished with value: 0.8664305822992168 and parameters: {'max_depth': 9, 'learning_rate': 0.19817774165410926, 'subsample': 0.8690856269930812, 'colsample_bytree': 0.6536074054839038, 'min_child_weight': 27.489547649192218, 'gamma': 0.014190871821646578, 'reg_alpha': 7.749040818304145e-07, 'reg_lambda': 11.633131249215683}. Best is trial 2 with value: 0.8705289719295306.
[I 2026-08-27 04:46:35,879] Trial 16 finished with value: 0.8635484001383708 and parameters: {'max_depth': 8, 'learning_rate': 0.13177796734730307, 'subsample': 0.8586927017191538, 'colsample_bytree': 0.6390519450381702, 'min_child_weight': 29.266819628702436, 'gamma': 0.020524823242183767, 'reg_alpha': 2.2588770720502548e-07, 'reg_lambda': 3.0830473334047306}. Best is trial 2 with value: 0.8705289719295306.
[I 2026-08-27 04:46:54,718] Trial 17 finished with value: 0.8750890212014643 and parameters: {'max_depth': 9, 'learning_rate': 0.11559880571167458, 'subsample': 0.8864095686072445, 'colsample_bytree': 0.7462766269481121, 'min_child_weight': 8.540761076488415, 'gamma': 0.262938132752185, 'reg_alpha': 2.172213690433863e-09, 'reg_lambda': 2.083558458304227}. Best is trial 17 with value: 0.8750890212014643.
[I 2026-08-27 04:47:08,447] Trial 18 finished with value: 0.8337050363892743 and parameters: {'max_depth': 6, 'learning_rate': 0.0782463128351522, 'subsample': 0.7667214138864583, 'colsample_bytree': 0.7685876627442525, 'min_child_weight': 7.513754202666461, 'gamma': 1.4557408989094207, 'reg_alpha': 3.0898501493733272e-09, 'reg_lambda': 1.1357101578547972}. Best is trial 17 with value: 0.8750890212014643.
[I 2026-08-27 04:47:17,730] Trial 19 finished with value: 0.8339082702362663 and parameters: {'max_depth': 7, 'learning_rate': 0.13279314941400044, 'subsample': 0.9967124142755496, 'colsample_bytree': 0.8425310595120723, 'min_child_weight': 4.053989981004542, 'gamma': 0.7312884368852899, 'reg_alpha': 1.3760240810671025e-08, 'reg_lambda': 0.35425072033627353}. Best is trial 17 with value: 0.8750890212014643.
[I 2026-08-27 04:47:41,765] Trial 20 finished with value: 0.8738338150445074 and parameters: {'max_depth': 9, 'learning_rate': 0.06418949709826452, 'subsample': 0.8681238025780942, 'colsample_bytree': 0.705568621452069, 'min_child_weight': 9.115994902439157, 'gamma': 0.31089772099195145, 'reg_alpha': 0.09095647740042732, 'reg_lambda': 2.2641434467107167}. Best is trial 17 with value: 0.8750890212014643.
[I 2026-08-27 04:48:02,294] Trial 21 finished with value: 0.8707419853410616 and parameters: {'max_depth': 9, 'learning_rate': 0.06857798114488887, 'subsample': 0.8782041330301507, 'colsample_bytree': 0.7156866437123837, 'min_child_weight': 8.748670161501403, 'gamma': 0.34181595694196115, 'reg_alpha': 0.48317265512657953, 'reg_lambda': 1.9422836377699944}. Best is trial 17 with value: 0.8750890212014643.
[I 2026-08-27 04:48:23,825] Trial 22 finished with value: 0.8696105782425281 and parameters: {'max_depth': 9, 'learning_rate': 0.06651217468208913, 'subsample': 0.900149073766403, 'colsample_bytree': 0.739912759336613, 'min_child_weight': 11.554094959194167, 'gamma': 0.34106308655449113, 'reg_alpha': 0.15851927368239083, 'reg_lambda': 1.9222542302610328}. Best is trial 17 with value: 0.8750890212014643.
[I 2026-08-27 04:48:47,992] Trial 23 finished with value: 0.874165314689672 and parameters: {'max_depth': 8, 'learning_rate': 0.10357567616016997, 'subsample': 0.8224550556193101, 'colsample_bytree': 0.8161400869086647, 'min_child_weight': 9.825653021639553, 'gamma': 0.2298959367723586, 'reg_alpha': 0.03367336652018941, 'reg_lambda': 1.616281742805327}. Best is trial 17 with value: 0.8750890212014643.
[I 2026-08-27 04:49:04,487] Trial 24 finished with value: 0.8631252767140254 and parameters: {'max_depth': 7, 'learning_rate': 0.10408414139034529, 'subsample': 0.8172555698933346, 'colsample_bytree': 0.8500368212761793, 'min_child_weight': 11.4194089410537, 'gamma': 0.6478612884614297, 'reg_alpha': 0.011601566918598627, 'reg_lambda': 0.6463820045841848}. Best is trial 17 with value: 0.8750890212014643.
[I 2026-08-27 04:49:45,735] Trial 25 finished with value: 0.8641723682409594 and parameters: {'max_depth': 8, 'learning_rate': 0.03376207213703955, 'subsample': 0.7615666242320015, 'colsample_bytree': 0.8156322899320291, 'min_child_weight': 16.79796399788668, 'gamma': 0.19348598583840332, 'reg_alpha': 0.0544165872863283, 'reg_lambda': 1.386114759754914}. Best is trial 17 with value: 0.8750890212014643.
[I 2026-08-27 04:49:59,061] Trial 26 finished with value: 0.8581847782022303 and parameters: {'max_depth': 8, 'learning_rate': 0.10264804653521425, 'subsample': 0.8380099865899632, 'colsample_bytree': 0.8981480418851177, 'min_child_weight': 3.707821157244363, 'gamma': 0.949955346389509, 'reg_alpha': 0.0003824362507556758, 'reg_lambda': 3.271475386017675}. Best is trial 17 with value: 0.8750890212014643.
[I 2026-08-27 04:50:23,603] Trial 27 finished with value: 0.8669677243053607 and parameters: {'max_depth': 7, 'learning_rate': 0.039562476336283556, 'subsample': 0.7895756603797992, 'colsample_bytree': 0.7600053655625387, 'min_child_weight': 5.984494598696171, 'gamma': 0.5912999703320375, 'reg_alpha': 0.0011105988818385128, 'reg_lambda': 0.6872518464735312}. Best is trial 17 with value: 0.8750890212014643.
[I 2026-08-27 04:50:51,582] Trial 28 finished with value: 0.8759823653487171 and parameters: {'max_depth': 9, 'learning_rate': 0.06440850471552748, 'subsample': 0.92788520711102, 'colsample_bytree': 0.9035571214411334, 'min_child_weight': 9.356929348314193, 'gamma': 0.16307760375610608, 'reg_alpha': 0.03078720565945149, 'reg_lambda': 1.7914082629340526}. Best is trial 28 with value: 0.8759823653487171.
[I 2026-08-27 04:51:12,032] Trial 29 finished with value: 0.8759012178756664 and parameters: {'max_depth': 9, 'learning_rate': 0.08240518340999604, 'subsample': 0.9241458984244015, 'colsample_bytree': 0.9177835330770112, 'min_child_weight': 10.099523253467344, 'gamma': 0.174106856033297, 'reg_alpha': 1.5900935063071773, 'reg_lambda': 1.4202338879009222}. Best is trial 28 with value: 0.8759823653487171.
[I 2026-08-27 04:51:25,009] Trial 30 finished with value: 0.8422666173429768 and parameters: {'max_depth': 9, 'learning_rate': 0.0867007426495319, 'subsample': 0.9279628822484165, 'colsample_bytree': 0.9256774211214311, 'min_child_weight': 17.615678469659315, 'gamma': 0.8704176806234408, 'reg_alpha': 0.912619853645507, 'reg_lambda': 0.2565511024442974}. Best is trial 28 with value: 0.8759823653487171.
[I 2026-08-27 04:51:38,369] Trial 31 finished with value: 0.8444892536820395 and parameters: {'max_depth': 8, 'learning_rate': 0.11321933353495126, 'subsample': 0.9649585431081329, 'colsample_bytree': 0.8900715317553145, 'min_child_weight': 11.870956011452801, 'gamma': 0.17942344583682485, 'reg_alpha': 7.899617664387512, 'reg_lambda': 1.5208346220440563}. Best is trial 28 with value: 0.8759823653487171.
[I 2026-08-27 04:52:08,755] Trial 32 finished with value: 0.8685140538192939 and parameters: {'max_depth': 9, 'learning_rate': 0.07423148918991787, 'subsample': 0.909675369976811, 'colsample_bytree': 0.942676755303653, 'min_child_weight': 22.165997395137644, 'gamma': 0.21161042326574936, 'reg_alpha': 0.031315264630833645, 'reg_lambda': 0.9314326575690436}. Best is trial 28 with value: 0.8759823653487171.
[I 2026-08-27 04:52:26,447] Trial 33 finished with value: 0.8683792456264028 and parameters: {'max_depth': 8, 'learning_rate': 0.09241418546947341, 'subsample': 0.884449035166676, 'colsample_bytree': 0.9103274874490116, 'min_child_weight': 9.89521112813443, 'gamma': 0.45624620808148064, 'reg_alpha': 0.0023840731945147815, 'reg_lambda': 4.02067526434441}. Best is trial 28 with value: 0.8759823653487171.
[I 2026-08-27 04:52:37,473] Trial 34 finished with value: 0.8582389528214728 and parameters: {'max_depth': 10, 'learning_rate': 0.1518842040197946, 'subsample': 0.972546088847288, 'colsample_bytree': 0.86212959718046, 'min_child_weight': 6.099993119114918, 'gamma': 0.5654177682075594, 'reg_alpha': 1.3727077453139833e-05, 'reg_lambda': 1.561814380642602}. Best is trial 28 with value: 0.8759823653487171.
[I 2026-08-27 04:52:58,766] Trial 35 finished with value: 0.8722002712315845 and parameters: {'max_depth': 7, 'learning_rate': 0.057010858584817074, 'subsample': 0.9424240064805532, 'colsample_bytree': 0.8100029298045003, 'min_child_weight': 3.971121098849584, 'gamma': 0.17607982394743638, 'reg_alpha': 1.7576291074546322, 'reg_lambda': 0.683470361192524}. Best is trial 28 with value: 0.8759823653487171.
[I 2026-08-27 04:53:09,494] Trial 36 finished with value: 0.780443126057452 and parameters: {'max_depth': 6, 'learning_rate': 0.08982640409595438, 'subsample': 0.9140461488336601, 'colsample_bytree': 0.9817231978849792, 'min_child_weight': 2.990249280584988, 'gamma': 2.7487401913156297, 'reg_alpha': 4.132132693963929e-06, 'reg_lambda': 1.2355485254037823}. Best is trial 28 with value: 0.8759823653487171.
[I 2026-08-27 04:53:22,851] Trial 37 finished with value: 0.8667746128218073 and parameters: {'max_depth': 10, 'learning_rate': 0.12276122262746605, 'subsample': 0.932375805011315, 'colsample_bytree': 0.8674037391984981, 'min_child_weight': 5.2572706663202045, 'gamma': 0.49783530413082216, 'reg_alpha': 0.02562594847196976, 'reg_lambda': 2.8622239421249454}. Best is trial 28 with value: 0.8759823653487171.
[I 2026-08-27 04:53:41,065] Trial 38 finished with value: 0.8771675086250916 and parameters: {'max_depth': 9, 'learning_rate': 0.10031978723371286, 'subsample': 0.8924225652853496, 'colsample_bytree': 0.93813156925849, 'min_child_weight': 6.815700128823182, 'gamma': 0.2736613551856823, 'reg_alpha': 0.14729646187469195, 'reg_lambda': 0.46788856796196493}. Best is trial 38 with value: 0.8771675086250916.
[I 2026-08-27 04:54:01,222] Trial 39 finished with value: 0.8709363869372642 and parameters: {'max_depth': 9, 'learning_rate': 0.07876808535802723, 'subsample': 0.8878213075673229, 'colsample_bytree': 0.9483657085002307, 'min_child_weight': 13.861935169574851, 'gamma': 0.3907145241727707, 'reg_alpha': 4.864594119581704e-08, 'reg_lambda': 0.1255083073345048}. Best is trial 38 with value: 0.8771675086250916.
[I 2026-08-27 04:54:14,962] Trial 40 finished with value: 0.839738182940445 and parameters: {'max_depth': 10, 'learning_rate': 0.05561247359334463, 'subsample': 0.8462516264518701, 'colsample_bytree': 0.9986174516811182, 'min_child_weight': 7.016721571809928, 'gamma': 1.347971371267619, 'reg_alpha': 2.0122101247024515, 'reg_lambda': 0.325677351616332}. Best is trial 38 with value: 0.8771675086250916.
[I 2026-08-27 04:54:33,665] Trial 41 finished with value: 0.8786872697443442 and parameters: {'max_depth': 9, 'learning_rate': 0.10307203944162678, 'subsample': 0.9588046540630358, 'colsample_bytree': 0.9255517550827884, 'min_child_weight': 7.060975218534914, 'gamma': 0.151445675225869, 'reg_alpha': 0.19146783899566103, 'reg_lambda': 0.5207717991609646}. Best is trial 41 with value: 0.8786872697443442.
[I 2026-08-27 04:54:50,938] Trial 42 finished with value: 0.8810320172295689 and parameters: {'max_depth': 9, 'learning_rate': 0.15327631216486937, 'subsample': 0.9529213709820022, 'colsample_bytree': 0.9214776573823018, 'min_child_weight': 7.013110183282827, 'gamma': 0.10642662702366446, 'reg_alpha': 0.30746871869994175, 'reg_lambda': 0.18455137497022647}. Best is trial 42 with value: 0.8810320172295689.
[I 2026-08-27 04:55:12,474] Trial 43 finished with value: 0.8819465402331472 and parameters: {'max_depth': 9, 'learning_rate': 0.15569158037441488, 'subsample': 0.9539029439494215, 'colsample_bytree': 0.9248488050803509, 'min_child_weight': 6.479833233524313, 'gamma': 0.0028172764960247287, 'reg_alpha': 0.24979500393990256, 'reg_lambda': 0.21239121810304054}. Best is trial 43 with value: 0.8819465402331472.
[I 2026-08-27 04:55:28,599] Trial 44 finished with value: 0.8861343607023449 and parameters: {'max_depth': 10, 'learning_rate': 0.14677224838042968, 'subsample': 0.9851398025911507, 'colsample_bytree': 0.9610443932753171, 'min_child_weight': 3.2055025879334256, 'gamma': 0.04484555459140935, 'reg_alpha': 0.20172518317120286, 'reg_lambda': 0.16478488521827642}. Best is trial 44 with value: 0.8861343607023449.
[I 2026-08-27 04:55:44,274] Trial 45 finished with value: 0.8883825126099829 and parameters: {'max_depth': 10, 'learning_rate': 0.14762515896056433, 'subsample': 0.98472289760005, 'colsample_bytree': 0.9722037697949377, 'min_child_weight': 2.461889341097133, 'gamma': 0.008931907202626266, 'reg_alpha': 0.18309087346287928, 'reg_lambda': 0.16920015134750324}. Best is trial 45 with value: 0.8883825126099829.
[I 2026-08-27 04:55:58,371] Trial 46 finished with value: 0.8850207291910401 and parameters: {'max_depth': 10, 'learning_rate': 0.15406256161095544, 'subsample': 0.9968163177634469, 'colsample_bytree': 0.9695673687651456, 'min_child_weight': 2.327966353268698, 'gamma': 0.033949120465310595, 'reg_alpha': 0.3289873033179792, 'reg_lambda': 0.18302234886341742}. Best is trial 45 with value: 0.8883825126099829.
[I 2026-08-27 04:56:12,724] Trial 47 finished with value: 0.8869229676644472 and parameters: {'max_depth': 10, 'learning_rate': 0.15507758072671712, 'subsample': 0.9888059261710743, 'colsample_bytree': 0.9741778130684731, 'min_child_weight': 2.6348447187185493, 'gamma': 0.04007029345848031, 'reg_alpha': 0.6752129962673824, 'reg_lambda': 0.16279881372894608}. Best is trial 45 with value: 0.8883825126099829.
[I 2026-08-27 04:56:25,230] Trial 48 finished with value: 0.8753832566006752 and parameters: {'max_depth': 10, 'learning_rate': 0.16695325848924206, 'subsample': 0.998439823259808, 'colsample_bytree': 0.9708703637889466, 'min_child_weight': 1.5116804587139485, 'gamma': 0.025005388090370666, 'reg_alpha': 4.133181301930363, 'reg_lambda': 0.10417228621425464}. Best is trial 45 with value: 0.8883825126099829.

[6/6] Creating 80/20 split with 'venice' completely held out.

[I 2026-08-27 05:38:37,687] A new study created in memory with name: DecisionTree_LOSO

[6/6] Running one 5-fold search per model.
  venice: tuning Decision Tree (200 trials).

[I 2026-08-27 05:38:38,250] Trial 0 finished with value: 0.6563241507058202 and parameters: {'max_depth': 12, 'min_samples_split': 96, 'min_samples_leaf': 59, 'max_features': 0.6, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 1.3480180290890803e-07}. Best is trial 0 with value: 0.6563241507058202.
[I 2026-08-27 05:38:38,320] Trial 1 finished with value: 0.5634130049761991 and parameters: {'max_depth': 17, 'min_samples_split': 44, 'min_samples_leaf': 24, 'max_features': 0.8, 'criterion': 'log_loss', 'splitter': 'random', 'class_weight': None, 'ccp_alpha': 0.0043873144324354085}. Best is trial 0 with value: 0.6563241507058202.
[I 2026-08-27 05:38:38,347] Trial 2 finished with value: 0.5071353293726183 and parameters: {'max_depth': 30, 'min_samples_split': 82, 'min_samples_leaf': 25, 'max_features': 'sqrt', 'criterion': 'gini', 'splitter': 'random', 'class_weight': None, 'ccp_alpha': 0.006124806805925988}. Best is trial 0 with value: 0.6563241507058202.
[I 2026-08-27 05:38:38,529] Trial 3 finished with value: 0.6254649636421721 and parameters: {'max_depth': 24, 'min_samples_split': 95, 'min_samples_leaf': 72, 'max_features': 'sqrt', 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 0.00041245717727594227}. Best is trial 0 with value: 0.6563241507058202.
[I 2026-08-27 05:38:38,626] Trial 4 finished with value: 0.5657425068301214 and parameters: {'max_depth': 4, 'min_samples_split': 99, 'min_samples_leaf': 62, 'max_features': 'log2', 'criterion': 'entropy', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 1.5027137214154575e-07}. Best is trial 0 with value: 0.6563241507058202.
[I 2026-08-27 05:38:39,405] Trial 5 finished with value: 0.6622885154206145 and parameters: {'max_depth': 11, 'min_samples_split': 74, 'min_samples_leaf': 52, 'max_features': None, 'criterion': 'gini', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 2.8501838758433707e-05}. Best is trial 5 with value: 0.6622885154206145.
[I 2026-08-27 05:38:39,428] Trial 6 finished with value: 0.5614378926706893 and parameters: {'max_depth': 11, 'min_samples_split': 52, 'min_samples_leaf': 73, 'max_features': 'log2', 'criterion': 'entropy', 'splitter': 'random', 'class_weight': None, 'ccp_alpha': 0.0017697543538533224}. Best is trial 5 with value: 0.6622885154206145.
[I 2026-08-27 05:38:40,157] Trial 7 finished with value: 0.6679794076815909 and parameters: {'max_depth': 17, 'min_samples_split': 81, 'min_samples_leaf': 72, 'max_features': 0.8, 'criterion': 'entropy', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 1.8298712093870903e-07}. Best is trial 7 with value: 0.6679794076815909.
[I 2026-08-27 05:38:40,218] Trial 8 finished with value: 0.6446618047377609 and parameters: {'max_depth': 17, 'min_samples_split': 71, 'min_samples_leaf': 30, 'max_features': None, 'criterion': 'entropy', 'splitter': 'random', 'class_weight': None, 'ccp_alpha': 1.0333896431462928e-08}. Best is trial 7 with value: 0.6679794076815909.
[I 2026-08-27 05:38:40,400] Trial 9 finished with value: 0.657703676375181 and parameters: {'max_depth': 16, 'min_samples_split': 99, 'min_samples_leaf': 20, 'max_features': 'sqrt', 'criterion': 'gini', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 1.3685182782317289e-05}. Best is trial 7 with value: 0.6679794076815909.
[I 2026-08-27 05:38:40,546] Trial 10 finished with value: 0.5670299344152916 and parameters: {'max_depth': 3, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 0.4, 'criterion': 'entropy', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 1.3381271619726983e-09}. Best is trial 7 with value: 0.6679794076815909.
[I 2026-08-27 05:38:41,296] Trial 11 finished with value: 0.6410965428747815 and parameters: {'max_depth': 9, 'min_samples_split': 65, 'min_samples_leaf': 46, 'max_features': None, 'criterion': 'gini', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 7.780462950625712e-06}. Best is trial 7 with value: 0.6679794076815909.
[I 2026-08-27 05:38:41,969] Trial 12 finished with value: 0.6875066900146961 and parameters: {'max_depth': 22, 'min_samples_split': 41, 'min_samples_leaf': 47, 'max_features': 0.8, 'criterion': 'gini', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 5.88256804402977e-06}. Best is trial 12 with value: 0.6875066900146961.
[I 2026-08-27 05:38:42,586] Trial 13 finished with value: 0.6617994534763081 and parameters: {'max_depth': 22, 'min_samples_split': 24, 'min_samples_leaf': 80, 'max_features': 0.8, 'criterion': 'gini', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 7.808721364002951e-07}. Best is trial 12 with value: 0.6875066900146961.
[I 2026-08-27 05:38:43,379] Trial 14 finished with value: 0.6952316232430725 and parameters: {'max_depth': 24, 'min_samples_split': 34, 'min_samples_leaf': 40, 'max_features': 0.8, 'criterion': 'entropy', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 8.169966361917122e-07}. Best is trial 14 with value: 0.6952316232430725.
[I 2026-08-27 05:38:44,171] Trial 15 finished with value: 0.6926780413007207 and parameters: {'max_depth': 25, 'min_samples_split': 30, 'min_samples_leaf': 39, 'max_features': 0.8, 'criterion': 'entropy', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 1.981870083915325e-06}. Best is trial 14 with value: 0.6952316232430725.
[I 2026-08-27 05:38:44,973] Trial 16 finished with value: 0.6912382003624047 and parameters: {'max_depth': 29, 'min_samples_split': 23, 'min_samples_leaf': 37, 'max_features': 0.8, 'criterion': 'entropy', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 0.00010697124005528724}. Best is trial 14 with value: 0.6952316232430725.
[I 2026-08-27 05:38:45,432] Trial 17 finished with value: 0.7404701011811345 and parameters: {'max_depth': 26, 'min_samples_split': 24, 'min_samples_leaf': 9, 'max_features': 0.4, 'criterion': 'entropy', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 1.7939622855533723e-06}. Best is trial 17 with value: 0.7404701011811345.
[I 2026-08-27 05:38:45,487] Trial 18 finished with value: 0.6747683258528381 and parameters: {'max_depth': 27, 'min_samples_split': 6, 'min_samples_leaf': 8, 'max_features': 0.4, 'criterion': 'entropy', 'splitter': 'random', 'class_weight': 'balanced', 'ccp_alpha': 1.6811067194681347e-08}. Best is trial 17 with value: 0.7404701011811345.
[I 2026-08-27 05:38:46,182] Trial 19 finished with value: 0.7250948324636457 and parameters: {'max_depth': 21, 'min_samples_split': 14, 'min_samples_leaf': 15, 'max_features': 0.6, 'criterion': 'entropy', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 6.091579582816418e-07}. Best is trial 17 with value: 0.7404701011811345.
[I 2026-08-27 05:38:46,888] Trial 20 finished with value: 0.730293864683566 and parameters: {'max_depth': 20, 'min_samples_split': 13, 'min_samples_leaf': 14, 'max_features': 0.6, 'criterion': 'entropy', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 2.6870819059195422e-08}. Best is trial 17 with value: 0.7404701011811345.
[I 2026-08-27 05:38:47,587] Trial 21 finished with value: 0.7390385953338579 and parameters: {'max_depth': 20, 'min_samples_split': 13, 'min_samples_leaf': 13, 'max_features': 0.6, 'criterion': 'entropy', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 2.1617327577514438e-08}. Best is trial 17 with value: 0.7404701011811345.
[I 2026-08-27 05:38:48,304] Trial 22 finished with value: 0.7442726335081312 and parameters: {'max_depth': 19, 'min_samples_split': 14, 'min_samples_leaf': 11, 'max_features': 0.6, 'criterion': 'entropy', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 1.0779905314585888e-08}. Best is trial 22 with value: 0.7442726335081312.
[I 2026-08-27 05:38:49,060] Trial 23 finished with value: 0.7510549699667601 and parameters: {'max_depth': 19, 'min_samples_split': 16, 'min_samples_leaf': 2, 'max_features': 0.6, 'criterion': 'entropy', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 3.440765696140843e-09}. Best is trial 23 with value: 0.7510549699667601.
[I 2026-08-27 05:38:49,502] Trial 24 finished with value: 0.7248374590556098 and parameters: {'max_depth': 14, 'min_samples_split': 21, 'min_samples_leaf': 2, 'max_features': 0.4, 'criterion': 'entropy', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 1.2430508504579793e-09}. Best is trial 23 with value: 0.7510549699667601.
[I 2026-08-27 05:38:50,230] Trial 25 finished with value: 0.7427678724063157 and parameters: {'max_depth': 26, 'min_samples_split': 33, 'min_samples_leaf': 7, 'max_features': 0.6, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 4.1190104086750976e-09}. Best is trial 23 with value: 0.7510549699667601.
[I 2026-08-27 05:38:50,268] Trial 26 finished with value: 0.591808178415824 and parameters: {'max_depth': 7, 'min_samples_split': 35, 'min_samples_leaf': 6, 'max_features': 0.6, 'criterion': 'log_loss', 'splitter': 'random', 'class_weight': 'balanced', 'ccp_alpha': 4.507188496968598e-09}. Best is trial 23 with value: 0.7510549699667601.
[I 2026-08-27 05:38:50,947] Trial 27 finished with value: 0.7148661611607954 and parameters: {'max_depth': 28, 'min_samples_split': 53, 'min_samples_leaf': 20, 'max_features': 0.6, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 4.164251617726668e-09}. Best is trial 23 with value: 0.7510549699667601.
[I 2026-08-27 05:38:51,675] Trial 28 finished with value: 0.7514478898879022 and parameters: {'max_depth': 19, 'min_samples_split': 9, 'min_samples_leaf': 6, 'max_features': 0.6, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 4.423726734938565e-08}. Best is trial 28 with value: 0.7514478898879022.
[I 2026-08-27 05:38:52,384] Trial 29 finished with value: 0.7373156679455187 and parameters: {'max_depth': 14, 'min_samples_split': 8, 'min_samples_leaf': 1, 'max_features': 0.6, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 6.098192666002708e-08}. Best is trial 28 with value: 0.7514478898879022.
[I 2026-08-27 05:38:53,070] Trial 30 finished with value: 0.7236763259645718 and parameters: {'max_depth': 19, 'min_samples_split': 17, 'min_samples_leaf': 18, 'max_features': 0.6, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 7.128865133257722e-08}. Best is trial 28 with value: 0.7514478898879022.
[I 2026-08-27 05:38:53,744] Trial 31 finished with value: 0.7239017534023736 and parameters: {'max_depth': 14, 'min_samples_split': 30, 'min_samples_leaf': 9, 'max_features': 0.6, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 4.570019350778928e-09}. Best is trial 28 with value: 0.7514478898879022.
[I 2026-08-27 05:38:54,472] Trial 32 finished with value: 0.7514478898879022 and parameters: {'max_depth': 19, 'min_samples_split': 7, 'min_samples_leaf': 6, 'max_features': 0.6, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 2.7727967953322756e-09}. Best is trial 28 with value: 0.7514478898879022.
[I 2026-08-27 05:38:55,175] Trial 33 finished with value: 0.7394559478615632 and parameters: {'max_depth': 19, 'min_samples_split': 3, 'min_samples_leaf': 12, 'max_features': 0.6, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 5.379937069098533e-08}. Best is trial 28 with value: 0.7514478898879022.
[I 2026-08-27 05:38:55,231] Trial 34 finished with value: 0.6486313265485868 and parameters: {'max_depth': 18, 'min_samples_split': 9, 'min_samples_leaf': 24, 'max_features': 0.6, 'criterion': 'log_loss', 'splitter': 'random', 'class_weight': 'balanced', 'ccp_alpha': 8.787190162389402e-09}. Best is trial 28 with value: 0.7514478898879022.
[I 2026-08-27 05:38:55,879] Trial 35 finished with value: 0.6953168927210702 and parameters: {'max_depth': 23, 'min_samples_split': 18, 'min_samples_leaf': 30, 'max_features': 0.6, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 1.3897945194840648e-09}. Best is trial 28 with value: 0.7514478898879022.
[I 2026-08-27 05:38:56,133] Trial 36 finished with value: 0.7268662616968398 and parameters: {'max_depth': 21, 'min_samples_split': 10, 'min_samples_leaf': 4, 'max_features': 'log2', 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 1.7997258599885267e-07}. Best is trial 28 with value: 0.7514478898879022.
[I 2026-08-27 05:38:56,163] Trial 37 finished with value: 0.6046156063026092 and parameters: {'max_depth': 15, 'min_samples_split': 17, 'min_samples_leaf': 17, 'max_features': 'sqrt', 'criterion': 'log_loss', 'splitter': 'random', 'class_weight': None, 'ccp_alpha': 2.7163157026888063e-09}. Best is trial 28 with value: 0.7514478898879022.
[I 2026-08-27 05:38:56,771] Trial 38 finished with value: 0.6893826884126781 and parameters: {'max_depth': 12, 'min_samples_split': 27, 'min_samples_leaf': 25, 'max_features': 0.6, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 3.0850535210385855e-08}. Best is trial 28 with value: 0.7514478898879022.
[I 2026-08-27 05:38:57,006] Trial 39 finished with value: 0.6995746207572164 and parameters: {'max_depth': 17, 'min_samples_split': 2, 'min_samples_leaf': 10, 'max_features': 'log2', 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 1.1723384896752559e-08}. Best is trial 28 with value: 0.7514478898879022.
[I 2026-08-27 05:38:57,068] Trial 40 finished with value: 0.6656831568443569 and parameters: {'max_depth': 18, 'min_samples_split': 41, 'min_samples_leaf': 5, 'max_features': 0.6, 'criterion': 'entropy', 'splitter': 'random', 'class_weight': 'balanced', 'ccp_alpha': 2.5122587085393225e-07}. Best is trial 28 with value: 0.7514478898879022.
[I 2026-08-27 05:38:57,772] Trial 41 finished with value: 0.7322175624052052 and parameters: {'max_depth': 23, 'min_samples_split': 47, 'min_samples_leaf': 5, 'max_features': 0.6, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 7.820379384820639e-09}. Best is trial 28 with value: 0.7514478898879022.
[I 2026-08-27 05:38:58,501] Trial 42 finished with value: 0.7415988591453317 and parameters: {'max_depth': 30, 'min_samples_split': 8, 'min_samples_leaf': 11, 'max_features': 0.6, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 2.8967221876096188e-09}. Best is trial 28 with value: 0.7514478898879022.
[I 2026-08-27 05:38:59,699] Trial 43 finished with value: 0.7558675242866653 and parameters: {'max_depth': 19, 'min_samples_split': 18, 'min_samples_leaf': 7, 'max_features': None, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 2.0228615949949153e-09}. Best is trial 43 with value: 0.7558675242866653.
[I 2026-08-27 05:39:00,769] Trial 44 finished with value: 0.7270843864591539 and parameters: {'max_depth': 16, 'min_samples_split': 19, 'min_samples_leaf': 21, 'max_features': None, 'criterion': 'log_loss', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 1.5595647657165098e-09}. Best is trial 43 with value: 0.7558675242866653.
[I 2026-08-27 05:39:01,890] Trial 45 finished with value: 0.7618306543644704 and parameters: {'max_depth': 19, 'min_samples_split': 13, 'min_samples_leaf': 1, 'max_features': None, 'criterion': 'gini', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 7.884683236734928e-09}. Best is trial 45 with value: 0.7618306543644704.
[I 2026-08-27 05:39:03,029] Trial 46 finished with value: 0.7644047102964227 and parameters: {'max_depth': 21, 'min_samples_split': 12, 'min_samples_leaf': 2, 'max_features': None, 'criterion': 'gini', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 3.908327617472764e-08}. Best is trial 46 with value: 0.7644047102964227.
[I 2026-08-27 05:39:04,202] Trial 47 finished with value: 0.7682022611351078 and parameters: {'max_depth': 22, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': None, 'criterion': 'gini', 'splitter': 'best', 'class_weight': 'balanced', 'ccp_alpha': 1.175060844481843e-07}. Best is trial 47 with value: 0.7682022611351078.
[I 2026-08-27 05:39:05,308] Trial 48 finished with value: 0.7721804005028391 and parameters: {'max_depth': 22, 'min_samples_split': 4, 'min_samples_leaf': 1, 'max_features': None, 'criterion': 'gini', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 1.0119837446826463e-07}. Best is trial 48 with value: 0.7721804005028391.
[I 2026-08-27 05:39:06,422] Trial 49 finished with value: 0.774898025974836 and parameters: {'max_depth': 24, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': None, 'criterion': 'gini', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 4.0393555171617235e-07}. Best is trial 49 with value: 0.774898025974836.
[I 2026-08-27 05:39:07,544] Trial 50 finished with value: 0.774898025974836 and parameters: {'max_depth': 24, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': None, 'criterion': 'gini', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 3.781855190347504e-07}. Best is trial 49 with value: 0.774898025974836.
[I 2026-08-27 05:39:08,658] Trial 51 finished with value: 0.7743558462556959 and parameters: {'max_depth': 24, 'min_samples_split': 4, 'min_samples_leaf': 1, 'max_features': None, 'criterion': 'gini', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 4.193724438171176e-07}. Best is trial 49 with value: 0.774898025974836.
[I 2026-08-27 05:39:09,767] Trial 52 finished with value: 0.7741597205057523 and parameters: {'max_depth': 24, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': None, 'criterion': 'gini', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 3.2182407400765e-07}. Best is trial 49 with value: 0.774898025974836.
[I 2026-08-27 05:39:10,835] Trial 53 finished with value: 0.7732996858069225 and parameters: {'max_depth': 24, 'min_samples_split': 2, 'min_samples_leaf': 4, 'max_features': None, 'criterion': 'gini', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 4.2959889831577103e-07}. Best is trial 49 with value: 0.774898025974836.
[I 2026-08-27 05:39:11,911] Trial 54 finished with value: 0.7726891488004789 and parameters: {'max_depth': 25, 'min_samples_split': 2, 'min_samples_leaf': 4, 'max_features': None, 'criterion': 'gini', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 3.7425989089102095e-07}. Best is trial 49 with value: 0.774898025974836.
[I 2026-08-27 05:39:12,882] Trial 55 finished with value: 0.7420567244873408 and parameters: {'max_depth': 25, 'min_samples_split': 2, 'min_samples_leaf': 15, 'max_features': None, 'criterion': 'gini', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 3.87047887185982e-07}. Best is trial 49 with value: 0.774898025974836.
[I 2026-08-27 05:39:13,946] Trial 56 finished with value: 0.7726891488004789 and parameters: {'max_depth': 25, 'min_samples_split': 6, 'min_samples_leaf': 4, 'max_features': None, 'criterion': 'gini', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 1.6806734202260689e-06}. Best is trial 49 with value: 0.774898025974836.
[I 2026-08-27 05:39:14,033] Trial 57 finished with value: 0.6981445664556529 and parameters: {'max_depth': 27, 'min_samples_split': 5, 'min_samples_leaf': 10, 'max_features': None, 'criterion': 'gini', 'splitter': 'random', 'class_weight': None, 'ccp_alpha': 3.5450106702366812e-06}. Best is trial 49 with value: 0.774898025974836.
[I 2026-08-27 05:39:15,062] Trial 58 finished with value: 0.7618976871773128 and parameters: {'max_depth': 24, 'min_samples_split': 11, 'min_samples_leaf': 8, 'max_features': None, 'criterion': 'gini', 'splitter': 'best', 'class_weight': None, 'ccp_alpha': 4.1490015400543845e-07}. Best is trial 49 with value: 0.774898025974836.

  venice: tuning Random Forest (200 trials).

[I 2026-08-27 05:41:56,478] Trial 0 finished with value: 0.8142192395082845 and parameters: {'n_estimators': 300, 'max_depth': 32, 'min_samples_split': 3, 'min_samples_leaf': 15, 'max_features': 0.7, 'bootstrap': True, 'criterion': 'log_loss', 'class_weight': None}. Best is trial 0 with value: 0.8142192395082845.
[I 2026-08-27 05:42:06,657] Trial 1 finished with value: 0.7841686774269815 and parameters: {'n_estimators': 600, 'max_depth': 16, 'min_samples_split': 20, 'min_samples_leaf': 13, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'gini', 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8142192395082845.
[I 2026-08-27 05:42:38,756] Trial 2 finished with value: 0.6873521315223428 and parameters: {'n_estimators': 600, 'max_depth': 8, 'min_samples_split': 28, 'min_samples_leaf': 15, 'max_features': 0.7, 'bootstrap': True, 'criterion': 'entropy', 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8142192395082845.
[I 2026-08-27 05:43:04,752] Trial 3 finished with value: 0.7969819162323186 and parameters: {'n_estimators': 800, 'max_depth': 24, 'min_samples_split': 25, 'min_samples_leaf': 20, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'log_loss', 'class_weight': None}. Best is trial 0 with value: 0.8142192395082845.
[I 2026-08-27 05:43:24,934] Trial 4 finished with value: 0.7773067885815796 and parameters: {'n_estimators': 1000, 'max_depth': 16, 'min_samples_split': 31, 'min_samples_leaf': 15, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy', 'class_weight': None}. Best is trial 0 with value: 0.8142192395082845.
[I 2026-08-27 05:43:58,404] Trial 5 finished with value: 0.8468428851001096 and parameters: {'n_estimators': 800, 'max_depth': 48, 'min_samples_split': 18, 'min_samples_leaf': 3, 'max_features': 0.3, 'bootstrap': False, 'criterion': 'gini', 'class_weight': 'balanced'}. Best is trial 5 with value: 0.8468428851001096.
[I 2026-08-27 05:44:21,602] Trial 6 finished with value: 0.8254909160074618 and parameters: {'n_estimators': 400, 'max_depth': 48, 'min_samples_split': 34, 'min_samples_leaf': 1, 'max_features': 0.5, 'bootstrap': True, 'criterion': 'entropy', 'class_weight': 'balanced'}. Best is trial 5 with value: 0.8468428851001096.
[I 2026-08-27 05:45:10,681] Trial 7 finished with value: 0.8237851689855102 and parameters: {'n_estimators': 1000, 'max_depth': 32, 'min_samples_split': 19, 'min_samples_leaf': 15, 'max_features': 0.3, 'bootstrap': False, 'criterion': 'log_loss', 'class_weight': 'balanced'}. Best is trial 5 with value: 0.8468428851001096.
[I 2026-08-27 05:47:04,771] Trial 8 finished with value: 0.7338314610037868 and parameters: {'n_estimators': 900, 'max_depth': 24, 'min_samples_split': 40, 'min_samples_leaf': 19, 'max_features': 1.0, 'bootstrap': False, 'criterion': 'gini', 'class_weight': 'balanced_subsample'}. Best is trial 5 with value: 0.8468428851001096.
[I 2026-08-27 05:47:38,879] Trial 9 finished with value: 0.8652706445537721 and parameters: {'n_estimators': 600, 'max_depth': None, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 0.3, 'bootstrap': False, 'criterion': 'log_loss', 'class_weight': 'balanced_subsample'}. Best is trial 9 with value: 0.8652706445537721.
[I 2026-08-27 05:47:57,021] Trial 10 finished with value: 0.8371353722406253 and parameters: {'n_estimators': 500, 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 7, 'max_features': 'log2', 'bootstrap': False, 'criterion': 'log_loss', 'class_weight': 'balanced_subsample'}. Best is trial 9 with value: 0.8652706445537721.
[I 2026-08-27 05:48:26,800] Trial 11 finished with value: 0.8561799450627585 and parameters: {'n_estimators': 700, 'max_depth': 48, 'min_samples_split': 12, 'min_samples_leaf': 1, 'max_features': 0.3, 'bootstrap': False, 'criterion': 'gini', 'class_weight': 'balanced_subsample'}. Best is trial 9 with value: 0.8652706445537721.
[I 2026-08-27 05:48:51,303] Trial 12 finished with value: 0.797905321574276 and parameters: {'n_estimators': 700, 'max_depth': 12, 'min_samples_split': 11, 'min_samples_leaf': 5, 'max_features': 0.3, 'bootstrap': False, 'criterion': 'gini', 'class_weight': 'balanced_subsample'}. Best is trial 9 with value: 0.8652706445537721.
[I 2026-08-27 05:49:24,900] Trial 13 finished with value: 0.8629674044726843 and parameters: {'n_estimators': 600, 'max_depth': None, 'min_samples_split': 11, 'min_samples_leaf': 1, 'max_features': 0.3, 'bootstrap': False, 'criterion': 'log_loss', 'class_weight': 'balanced_subsample'}. Best is trial 9 with value: 0.8652706445537721.
[I 2026-08-27 05:49:50,939] Trial 14 finished with value: 0.8457735252178962 and parameters: {'n_estimators': 500, 'max_depth': None, 'min_samples_split': 9, 'min_samples_leaf': 8, 'max_features': 0.3, 'bootstrap': False, 'criterion': 'log_loss', 'class_weight': 'balanced_subsample'}. Best is trial 9 with value: 0.8652706445537721.
[I 2026-08-27 05:50:39,444] Trial 15 finished with value: 0.871418146220989 and parameters: {'n_estimators': 500, 'max_depth': None, 'min_samples_split': 7, 'min_samples_leaf': 4, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'log_loss', 'class_weight': 'balanced_subsample'}. Best is trial 15 with value: 0.871418146220989.
[I 2026-08-27 05:51:07,185] Trial 16 finished with value: 0.8519422392250171 and parameters: {'n_estimators': 300, 'max_depth': None, 'min_samples_split': 6, 'min_samples_leaf': 9, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'log_loss', 'class_weight': 'balanced_subsample'}. Best is trial 15 with value: 0.871418146220989.
[I 2026-08-27 05:51:45,659] Trial 17 finished with value: 0.865087290161086 and parameters: {'n_estimators': 400, 'max_depth': None, 'min_samples_split': 16, 'min_samples_leaf': 4, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'log_loss', 'class_weight': 'balanced_subsample'}. Best is trial 15 with value: 0.871418146220989.
[I 2026-08-27 05:51:57,831] Trial 18 finished with value: 0.6819011337113509 and parameters: {'n_estimators': 500, 'max_depth': 8, 'min_samples_split': 7, 'min_samples_leaf': 6, 'max_features': 'log2', 'bootstrap': False, 'criterion': 'log_loss', 'class_weight': 'balanced_subsample'}. Best is trial 15 with value: 0.871418146220989.
[I 2026-08-27 05:53:01,790] Trial 19 finished with value: 0.7103385148869126 and parameters: {'n_estimators': 400, 'max_depth': 12, 'min_samples_split': 15, 'min_samples_leaf': 10, 'max_features': 1.0, 'bootstrap': False, 'criterion': 'log_loss', 'class_weight': 'balanced_subsample'}. Best is trial 15 with value: 0.871418146220989.
[I 2026-08-27 05:54:09,440] Trial 20 finished with value: 0.8741203892114644 and parameters: {'n_estimators': 700, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 3, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8741203892114644.
[I 2026-08-27 05:55:16,861] Trial 21 finished with value: 0.8741203892114644 and parameters: {'n_estimators': 700, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 3, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8741203892114644.
[I 2026-08-27 05:56:24,348] Trial 22 finished with value: 0.8741203892114644 and parameters: {'n_estimators': 700, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 3, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8741203892114644.
[I 2026-08-27 05:57:41,839] Trial 23 finished with value: 0.8739344535778043 and parameters: {'n_estimators': 800, 'max_depth': None, 'min_samples_split': 3, 'min_samples_leaf': 3, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8741203892114644.
[I 2026-08-27 05:58:49,094] Trial 24 finished with value: 0.8741203892114644 and parameters: {'n_estimators': 700, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 3, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8741203892114644.
[I 2026-08-27 06:00:12,524] Trial 25 finished with value: 0.8620763178415807 and parameters: {'n_estimators': 900, 'max_depth': None, 'min_samples_split': 14, 'min_samples_leaf': 6, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8741203892114644.
[I 2026-08-27 06:00:52,594] Trial 26 finished with value: 0.8487951694756048 and parameters: {'n_estimators': 700, 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 5, 'max_features': 0.5, 'bootstrap': True, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8741203892114644.
[I 2026-08-27 06:01:55,930] Trial 27 finished with value: 0.8011903112506322 and parameters: {'n_estimators': 800, 'max_depth': 12, 'min_samples_split': 7, 'min_samples_leaf': 11, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8741203892114644.
[I 2026-08-27 06:03:18,716] Trial 28 finished with value: 0.8602540912949689 and parameters: {'n_estimators': 900, 'max_depth': 16, 'min_samples_split': 5, 'min_samples_leaf': 3, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8741203892114644.
[I 2026-08-27 06:04:11,473] Trial 29 finished with value: 0.8436406708617767 and parameters: {'n_estimators': 700, 'max_depth': 32, 'min_samples_split': 4, 'min_samples_leaf': 7, 'max_features': 0.7, 'bootstrap': True, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8741203892114644.
[I 2026-08-27 06:05:01,081] Trial 30 finished with value: 0.6935184299304724 and parameters: {'n_estimators': 800, 'max_depth': 8, 'min_samples_split': 9, 'min_samples_leaf': 2, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8741203892114644.
[I 2026-08-27 06:06:07,737] Trial 31 finished with value: 0.8707896941848527 and parameters: {'n_estimators': 700, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 4, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8741203892114644.
[I 2026-08-27 06:07:05,452] Trial 32 finished with value: 0.8717973003888855 and parameters: {'n_estimators': 600, 'max_depth': None, 'min_samples_split': 8, 'min_samples_leaf': 3, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8741203892114644.
[I 2026-08-27 06:08:34,287] Trial 33 finished with value: 0.863038958285616 and parameters: {'n_estimators': 700, 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 5, 'max_features': 0.7, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8741203892114644.
[I 2026-08-27 06:09:09,847] Trial 34 finished with value: 0.8515645849014897 and parameters: {'n_estimators': 600, 'max_depth': 32, 'min_samples_split': 13, 'min_samples_leaf': 2, 'max_features': 0.5, 'bootstrap': True, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8741203892114644.
[I 2026-08-27 06:09:39,053] Trial 35 finished with value: 0.8380073124924212 and parameters: {'n_estimators': 800, 'max_depth': 24, 'min_samples_split': 22, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8741203892114644.
[I 2026-08-27 06:09:54,303] Trial 36 finished with value: 0.8119513430941983 and parameters: {'n_estimators': 700, 'max_depth': 16, 'min_samples_split': 5, 'min_samples_leaf': 6, 'max_features': 'log2', 'bootstrap': True, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8741203892114644.
[I 2026-08-27 06:11:43,661] Trial 37 finished with value: 0.7821494914330354 and parameters: {'n_estimators': 600, 'max_depth': None, 'min_samples_split': 4, 'min_samples_leaf': 4, 'max_features': 1.0, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8741203892114644.
[I 2026-08-27 06:12:03,150] Trial 38 finished with value: 0.6824783987581319 and parameters: {'n_estimators': 800, 'max_depth': 8, 'min_samples_split': 8, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'entropy', 'class_weight': 'balanced'}. Best is trial 20 with value: 0.8741203892114644.
[I 2026-08-27 06:12:53,429] Trial 39 finished with value: 0.8393878240474331 and parameters: {'n_estimators': 900, 'max_depth': 24, 'min_samples_split': 6, 'min_samples_leaf': 7, 'max_features': 0.5, 'bootstrap': True, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8741203892114644.
[I 2026-08-27 06:14:10,881] Trial 40 finished with value: 0.8670273595432058 and parameters: {'n_estimators': 600, 'max_depth': 48, 'min_samples_split': 10, 'min_samples_leaf': 3, 'max_features': 0.7, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8741203892114644.
[I 2026-08-27 06:15:27,625] Trial 41 finished with value: 0.8739344535778043 and parameters: {'n_estimators': 800, 'max_depth': None, 'min_samples_split': 3, 'min_samples_leaf': 3, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8741203892114644.
[I 2026-08-27 06:16:43,637] Trial 42 finished with value: 0.8714314277445252 and parameters: {'n_estimators': 800, 'max_depth': None, 'min_samples_split': 4, 'min_samples_leaf': 4, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8741203892114644.
[I 2026-08-27 06:17:43,381] Trial 43 finished with value: 0.8228549213344142 and parameters: {'n_estimators': 700, 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 18, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8741203892114644.
[I 2026-08-27 06:18:36,896] Trial 44 finished with value: 0.8701216592278935 and parameters: {'n_estimators': 700, 'max_depth': None, 'min_samples_split': 4, 'min_samples_leaf': 1, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'gini', 'class_weight': 'balanced'}. Best is trial 20 with value: 0.8741203892114644.
[I 2026-08-27 06:19:51,903] Trial 45 finished with value: 0.8664849326709974 and parameters: {'n_estimators': 800, 'max_depth': None, 'min_samples_split': 9, 'min_samples_leaf': 5, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8741203892114644.
[I 2026-08-27 06:21:11,887] Trial 46 finished with value: 0.8316690324275005 and parameters: {'n_estimators': 900, 'max_depth': 16, 'min_samples_split': 40, 'min_samples_leaf': 2, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8741203892114644.
[I 2026-08-27 06:22:50,043] Trial 47 finished with value: 0.7451564532818382 and parameters: {'n_estimators': 700, 'max_depth': None, 'min_samples_split': 37, 'min_samples_leaf': 3, 'max_features': 1.0, 'bootstrap': False, 'criterion': 'gini', 'class_weight': 'balanced'}. Best is trial 20 with value: 0.8741203892114644.
[I 2026-08-27 06:23:12,130] Trial 48 finished with value: 0.8311333645825358 and parameters: {'n_estimators': 600, 'max_depth': 48, 'min_samples_split': 28, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8741203892114644.
[I 2026-08-27 06:23:48,515] Trial 49 finished with value: 0.8446047183774885 and parameters: {'n_estimators': 1000, 'max_depth': 32, 'min_samples_split': 6, 'min_samples_leaf': 5, 'max_features': 'log2', 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8741203892114644.
[I 2026-08-27 06:24:21,975] Trial 50 finished with value: 0.8272376199596566 and parameters: {'n_estimators': 800, 'max_depth': None, 'min_samples_split': 11, 'min_samples_leaf': 8, 'max_features': 0.5, 'bootstrap': True, 'criterion': 'gini', 'class_weight': None}. Best is trial 20 with value: 0.8741203892114644.
[I 2026-08-27 06:25:38,807] Trial 51 finished with value: 0.8739344535778043 and parameters: {'n_estimators': 800, 'max_depth': None, 'min_samples_split': 3, 'min_samples_leaf': 3, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8741203892114644.
[I 2026-08-27 06:26:46,274] Trial 52 finished with value: 0.8741203892114644 and parameters: {'n_estimators': 700, 'max_depth': None, 'min_samples_split': 3, 'min_samples_leaf': 3, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8741203892114644.
[I 2026-08-27 06:27:53,139] Trial 53 finished with value: 0.8707896941848527 and parameters: {'n_estimators': 700, 'max_depth': None, 'min_samples_split': 7, 'min_samples_leaf': 4, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 20 with value: 0.8741203892114644.
[I 2026-08-27 06:28:51,755] Trial 54 finished with value: 0.8775006291612234 and parameters: {'n_estimators': 600, 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 2, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 54 with value: 0.8775006291612234.
[I 2026-08-27 06:29:40,992] Trial 55 finished with value: 0.8159790040062418 and parameters: {'n_estimators': 600, 'max_depth': 12, 'min_samples_split': 5, 'min_samples_leaf': 2, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 54 with value: 0.8775006291612234.
[I 2026-08-27 06:30:31,398] Trial 56 finished with value: 0.8787210602058131 and parameters: {'n_estimators': 500, 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': 'balanced'}. Best is trial 56 with value: 0.8787210602058131.
[I 2026-08-27 06:31:21,320] Trial 57 finished with value: 0.8762922182783169 and parameters: {'n_estimators': 500, 'max_depth': None, 'min_samples_split': 8, 'min_samples_leaf': 1, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': 'balanced'}. Best is trial 56 with value: 0.8787210602058131.
[I 2026-08-27 06:31:49,253] Trial 58 finished with value: 0.860881309353234 and parameters: {'n_estimators': 500, 'max_depth': 24, 'min_samples_split': 12, 'min_samples_leaf': 1, 'max_features': 0.3, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': 'balanced'}. Best is trial 56 with value: 0.8787210602058131.
[I 2026-08-27 06:32:27,785] Trial 59 finished with value: 0.8672007539106932 and parameters: {'n_estimators': 500, 'max_depth': None, 'min_samples_split': 8, 'min_samples_leaf': 1, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'gini', 'class_weight': 'balanced'}. Best is trial 56 with value: 0.8787210602058131.
[I 2026-08-27 06:34:03,437] Trial 60 finished with value: 0.780009821169016 and parameters: {'n_estimators': 500, 'max_depth': None, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 1.0, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': 'balanced'}. Best is trial 56 with value: 0.8787210602058131.
[I 2026-08-27 06:34:43,163] Trial 61 finished with value: 0.8754903562886509 and parameters: {'n_estimators': 400, 'max_depth': None, 'min_samples_split': 6, 'min_samples_leaf': 2, 'max_features': 0.5, 'bootstrap': False, 'criterion': 'entropy', 'class_weight': 'balanced'}. Best is trial 56 with value: 0.8787210602058131.

  venice: tuning XGBoost (200 trials).

[I 2026-08-27 08:19:53,600] Trial 0 finished with value: 0.8330644788546315 and parameters: {'max_depth': 9, 'learning_rate': 0.019677977348166304, 'subsample': 0.8978561926718072, 'colsample_bytree': 0.7442003345025142, 'min_child_weight': 2.1771032186203514, 'gamma': 1.8277151418544553, 'reg_alpha': 8.665537597324885e-06, 'reg_lambda': 1.0311514495138399}. Best is trial 0 with value: 0.8330644788546315.
[I 2026-08-27 08:20:09,857] Trial 1 finished with value: 0.8554768025671576 and parameters: {'max_depth': 7, 'learning_rate': 0.09439831569936806, 'subsample': 0.9842104900822669, 'colsample_bytree': 0.7826484435755748, 'min_child_weight': 2.880043790954131, 'gamma': 0.3403911033599112, 'reg_alpha': 1.5100408408589772e-07, 'reg_lambda': 23.538263110950048}. Best is trial 1 with value: 0.8554768025671576.
[I 2026-08-27 08:20:25,839] Trial 2 finished with value: 0.8727881912840747 and parameters: {'max_depth': 10, 'learning_rate': 0.14726161255504092, 'subsample': 0.8585642249613574, 'colsample_bytree': 0.6855299248522434, 'min_child_weight': 6.781935357780796, 'gamma': 0.41743875595471047, 'reg_alpha': 3.864031899313156e-05, 'reg_lambda': 14.610499699549097}. Best is trial 2 with value: 0.8727881912840747.
[I 2026-08-27 08:20:41,271] Trial 3 finished with value: 0.8543777834846493 and parameters: {'max_depth': 5, 'learning_rate': 0.08394754752250128, 'subsample': 0.9450697344147837, 'colsample_bytree': 0.6595392252176876, 'min_child_weight': 5.011643571251018, 'gamma': 0.4774657914394431, 'reg_alpha': 5.357340695323986e-08, 'reg_lambda': 0.18099954688158187}. Best is trial 2 with value: 0.8727881912840747.
[I 2026-08-27 08:20:56,497] Trial 4 finished with value: 0.8061522990100844 and parameters: {'max_depth': 4, 'learning_rate': 0.048769840070943336, 'subsample': 0.9178299664912868, 'colsample_bytree': 0.9963290723923126, 'min_child_weight': 13.502442798764482, 'gamma': 1.1322462171492673, 'reg_alpha': 0.00014367270092871558, 'reg_lambda': 0.1399264351773497}. Best is trial 2 with value: 0.8727881912840747.
[I 2026-08-27 08:21:14,351] Trial 5 finished with value: 0.7885066397251064 and parameters: {'max_depth': 8, 'learning_rate': 0.018099146987238985, 'subsample': 0.953044632771952, 'colsample_bytree': 0.8904231274266234, 'min_child_weight': 15.164258427643505, 'gamma': 2.130692051488852, 'reg_alpha': 0.009425386803829051, 'reg_lambda': 20.136195700340338}. Best is trial 2 with value: 0.8727881912840747.
[I 2026-08-27 08:21:47,044] Trial 6 finished with value: 0.8416985869971396 and parameters: {'max_depth': 10, 'learning_rate': 0.01918354750824495, 'subsample': 0.782598566894961, 'colsample_bytree': 0.7970893967426577, 'min_child_weight': 0.7811624819629674, 'gamma': 0.46120338258524907, 'reg_alpha': 6.963704487425356, 'reg_lambda': 0.47063847559435423}. Best is trial 2 with value: 0.8727881912840747.
[I 2026-08-27 08:22:10,705] Trial 7 finished with value: 0.8555837356930995 and parameters: {'max_depth': 10, 'learning_rate': 0.022953302153308094, 'subsample': 0.6529433178954122, 'colsample_bytree': 0.7269413610677277, 'min_child_weight': 1.7604099383967902, 'gamma': 1.266165560263202, 'reg_alpha': 2.041568273325791e-06, 'reg_lambda': 2.5538276254965817}. Best is trial 2 with value: 0.8727881912840747.
[I 2026-08-27 08:22:29,462] Trial 8 finished with value: 0.8312718980913367 and parameters: {'max_depth': 3, 'learning_rate': 0.11851328676362981, 'subsample': 0.7074625481911713, 'colsample_bytree': 0.9645659651689448, 'min_child_weight': 20.063522776432464, 'gamma': 0.047573401053791486, 'reg_alpha': 0.34420918881100815, 'reg_lambda': 4.715832950352583}. Best is trial 2 with value: 0.8727881912840747.
[I 2026-08-27 08:22:43,746] Trial 9 finished with value: 0.7300092020681866 and parameters: {'max_depth': 3, 'learning_rate': 0.033391708755025735, 'subsample': 0.8256997968048689, 'colsample_bytree': 0.837631051781117, 'min_child_weight': 8.12005959578132, 'gamma': 1.8972954750065205, 'reg_alpha': 2.437950567013768, 'reg_lambda': 6.697837558293906}. Best is trial 2 with value: 0.8727881912840747.
[I 2026-08-27 08:22:53,587] Trial 10 finished with value: 0.7908186853594091 and parameters: {'max_depth': 6, 'learning_rate': 0.17115128841996644, 'subsample': 0.8154186866999962, 'colsample_bytree': 0.6025554256995838, 'min_child_weight': 0.8625345056254972, 'gamma': 2.9869578392012968, 'reg_alpha': 1.239446148413562e-09, 'reg_lambda': 0.9684799729031198}. Best is trial 2 with value: 0.8727881912840747.
[I 2026-08-27 08:23:13,195] Trial 11 finished with value: 0.8599526598920336 and parameters: {'max_depth': 10, 'learning_rate': 0.04809950013571818, 'subsample': 0.6132599083973347, 'colsample_bytree': 0.7068708218135153, 'min_child_weight': 2.000151976177787, 'gamma': 1.1015819037394388, 'reg_alpha': 4.514632609962317e-05, 'reg_lambda': 5.019540607508096}. Best is trial 2 with value: 0.8727881912840747.
[I 2026-08-27 08:23:32,952] Trial 12 finished with value: 0.8546608769302703 and parameters: {'max_depth': 9, 'learning_rate': 0.05449774578204275, 'subsample': 0.6446773085991204, 'colsample_bytree': 0.6782743329282878, 'min_child_weight': 5.024974615071706, 'gamma': 1.0252076108694772, 'reg_alpha': 0.0009910433108845519, 'reg_lambda': 8.210034909208419}. Best is trial 2 with value: 0.8727881912840747.
[I 2026-08-27 08:23:48,831] Trial 13 finished with value: 0.8624044717365378 and parameters: {'max_depth': 10, 'learning_rate': 0.19639010434181664, 'subsample': 0.6021768360536973, 'colsample_bytree': 0.6725320077667093, 'min_child_weight': 1.334503164197373, 'gamma': 0.7848649789462945, 'reg_alpha': 6.501336646332095e-05, 'reg_lambda': 11.389015447500912}. Best is trial 2 with value: 0.8727881912840747.
[I 2026-08-27 08:24:03,561] Trial 14 finished with value: 0.8620390011457493 and parameters: {'max_depth': 8, 'learning_rate': 0.1748224970113755, 'subsample': 0.7251257998024343, 'colsample_bytree': 0.6067985020666221, 'min_child_weight': 0.5629506277333849, 'gamma': 0.7357192839349284, 'reg_alpha': 0.007366281502087388, 'reg_lambda': 15.167077457961938}. Best is trial 2 with value: 0.8727881912840747.
[I 2026-08-27 08:24:31,908] Trial 15 finished with value: 0.8694503838434328 and parameters: {'max_depth': 9, 'learning_rate': 0.19817774165410926, 'subsample': 0.8690856269930812, 'colsample_bytree': 0.6536074054839038, 'min_child_weight': 27.489547649192218, 'gamma': 0.014190871821646578, 'reg_alpha': 7.749040818304145e-07, 'reg_lambda': 11.633131249215683}. Best is trial 2 with value: 0.8727881912840747.
[I 2026-08-27 08:25:08,861] Trial 16 finished with value: 0.8684761409918978 and parameters: {'max_depth': 8, 'learning_rate': 0.13177796734730307, 'subsample': 0.8586927017191538, 'colsample_bytree': 0.6390519450381702, 'min_child_weight': 29.266819628702436, 'gamma': 0.020524823242183767, 'reg_alpha': 2.2588770720502548e-07, 'reg_lambda': 3.0830473334047306}. Best is trial 2 with value: 0.8727881912840747.
[I 2026-08-27 08:25:27,073] Trial 17 finished with value: 0.8816454702401959 and parameters: {'max_depth': 9, 'learning_rate': 0.11559880571167458, 'subsample': 0.8864095686072445, 'colsample_bytree': 0.7462766269481121, 'min_child_weight': 8.540761076488415, 'gamma': 0.262938132752185, 'reg_alpha': 2.172213690433863e-09, 'reg_lambda': 2.083558458304227}. Best is trial 17 with value: 0.8816454702401959.
[I 2026-08-27 08:25:40,483] Trial 18 finished with value: 0.8399800471096395 and parameters: {'max_depth': 6, 'learning_rate': 0.0782463128351522, 'subsample': 0.7667214138864583, 'colsample_bytree': 0.7685876627442525, 'min_child_weight': 7.513754202666461, 'gamma': 1.4557408989094207, 'reg_alpha': 3.0898501493733272e-09, 'reg_lambda': 1.1357101578547972}. Best is trial 17 with value: 0.8816454702401959.
[I 2026-08-27 08:25:49,829] Trial 19 finished with value: 0.841983396479679 and parameters: {'max_depth': 7, 'learning_rate': 0.13279314941400044, 'subsample': 0.9967124142755496, 'colsample_bytree': 0.8425310595120723, 'min_child_weight': 4.053989981004542, 'gamma': 0.7312884368852899, 'reg_alpha': 1.3760240810671025e-08, 'reg_lambda': 0.35425072033627353}. Best is trial 17 with value: 0.8816454702401959.
[I 2026-08-27 08:26:12,848] Trial 20 finished with value: 0.8771485015635772 and parameters: {'max_depth': 9, 'learning_rate': 0.06418949709826452, 'subsample': 0.8681238025780942, 'colsample_bytree': 0.705568621452069, 'min_child_weight': 9.115994902439157, 'gamma': 0.31089772099195145, 'reg_alpha': 0.09095647740042732, 'reg_lambda': 2.2641434467107167}. Best is trial 17 with value: 0.8816454702401959.
[I 2026-08-27 08:26:32,702] Trial 21 finished with value: 0.8764992941722545 and parameters: {'max_depth': 9, 'learning_rate': 0.06857798114488887, 'subsample': 0.8782041330301507, 'colsample_bytree': 0.7156866437123837, 'min_child_weight': 8.748670161501403, 'gamma': 0.34181595694196115, 'reg_alpha': 0.48317265512657953, 'reg_lambda': 1.9422836377699944}. Best is trial 17 with value: 0.8816454702401959.
[I 2026-08-27 08:26:53,509] Trial 22 finished with value: 0.8742456889312089 and parameters: {'max_depth': 9, 'learning_rate': 0.06651217468208913, 'subsample': 0.900149073766403, 'colsample_bytree': 0.739912759336613, 'min_child_weight': 11.554094959194167, 'gamma': 0.34106308655449113, 'reg_alpha': 0.15851927368239083, 'reg_lambda': 1.9222542302610328}. Best is trial 17 with value: 0.8816454702401959.
[I 2026-08-27 08:27:16,892] Trial 23 finished with value: 0.8797945272966287 and parameters: {'max_depth': 8, 'learning_rate': 0.10357567616016997, 'subsample': 0.8224550556193101, 'colsample_bytree': 0.8161400869086647, 'min_child_weight': 9.825653021639553, 'gamma': 0.2298959367723586, 'reg_alpha': 0.03367336652018941, 'reg_lambda': 1.616281742805327}. Best is trial 17 with value: 0.8816454702401959.
[I 2026-08-27 08:27:32,978] Trial 24 finished with value: 0.8657853931118964 and parameters: {'max_depth': 7, 'learning_rate': 0.10408414139034529, 'subsample': 0.8172555698933346, 'colsample_bytree': 0.8500368212761793, 'min_child_weight': 11.4194089410537, 'gamma': 0.6478612884614297, 'reg_alpha': 0.011601566918598627, 'reg_lambda': 0.6463820045841848}. Best is trial 17 with value: 0.8816454702401959.
[I 2026-08-27 08:28:13,954] Trial 25 finished with value: 0.8698359797104287 and parameters: {'max_depth': 8, 'learning_rate': 0.03376207213703955, 'subsample': 0.7615666242320015, 'colsample_bytree': 0.8156322899320291, 'min_child_weight': 16.79796399788668, 'gamma': 0.19348598583840332, 'reg_alpha': 0.0544165872863283, 'reg_lambda': 1.386114759754914}. Best is trial 17 with value: 0.8816454702401959.
[I 2026-08-27 08:28:26,898] Trial 26 finished with value: 0.8645322037009716 and parameters: {'max_depth': 8, 'learning_rate': 0.10264804653521425, 'subsample': 0.8380099865899632, 'colsample_bytree': 0.8981480418851177, 'min_child_weight': 3.707821157244363, 'gamma': 0.949955346389509, 'reg_alpha': 0.0003824362507556758, 'reg_lambda': 3.271475386017675}. Best is trial 17 with value: 0.8816454702401959.
[I 2026-08-27 08:28:50,488] Trial 27 finished with value: 0.871331210973867 and parameters: {'max_depth': 7, 'learning_rate': 0.039562476336283556, 'subsample': 0.7895756603797992, 'colsample_bytree': 0.7600053655625387, 'min_child_weight': 5.984494598696171, 'gamma': 0.5912999703320375, 'reg_alpha': 0.0011105988818385128, 'reg_lambda': 0.6872518464735312}. Best is trial 17 with value: 0.8816454702401959.
[I 2026-08-27 08:29:17,613] Trial 28 finished with value: 0.881979777972656 and parameters: {'max_depth': 9, 'learning_rate': 0.06440850471552748, 'subsample': 0.92788520711102, 'colsample_bytree': 0.9035571214411334, 'min_child_weight': 9.356929348314193, 'gamma': 0.16307760375610608, 'reg_alpha': 0.03078720565945149, 'reg_lambda': 1.7914082629340526}. Best is trial 28 with value: 0.881979777972656.
[I 2026-08-27 08:29:37,383] Trial 29 finished with value: 0.8815187856878474 and parameters: {'max_depth': 9, 'learning_rate': 0.08240518340999604, 'subsample': 0.9241458984244015, 'colsample_bytree': 0.9177835330770112, 'min_child_weight': 10.099523253467344, 'gamma': 0.174106856033297, 'reg_alpha': 1.5900935063071773, 'reg_lambda': 1.4202338879009222}. Best is trial 28 with value: 0.881979777972656.
[I 2026-08-27 08:29:50,011] Trial 30 finished with value: 0.844612800193741 and parameters: {'max_depth': 9, 'learning_rate': 0.0867007426495319, 'subsample': 0.9279628822484165, 'colsample_bytree': 0.9256774211214311, 'min_child_weight': 17.615678469659315, 'gamma': 0.8704176806234408, 'reg_alpha': 0.912619853645507, 'reg_lambda': 0.2565511024442974}. Best is trial 28 with value: 0.881979777972656.
[I 2026-08-27 08:30:02,958] Trial 31 finished with value: 0.8437901438458967 and parameters: {'max_depth': 8, 'learning_rate': 0.11321933353495126, 'subsample': 0.9649585431081329, 'colsample_bytree': 0.8900715317553145, 'min_child_weight': 11.870956011452801, 'gamma': 0.17942344583682485, 'reg_alpha': 7.899617664387512, 'reg_lambda': 1.5208346220440563}. Best is trial 28 with value: 0.881979777972656.
[I 2026-08-27 08:30:32,676] Trial 32 finished with value: 0.8730705378473738 and parameters: {'max_depth': 9, 'learning_rate': 0.07423148918991787, 'subsample': 0.909675369976811, 'colsample_bytree': 0.942676755303653, 'min_child_weight': 22.165997395137644, 'gamma': 0.21161042326574936, 'reg_alpha': 0.031315264630833645, 'reg_lambda': 0.9314326575690436}. Best is trial 28 with value: 0.881979777972656.
[I 2026-08-27 08:30:49,736] Trial 33 finished with value: 0.8740596885435359 and parameters: {'max_depth': 8, 'learning_rate': 0.09241418546947341, 'subsample': 0.884449035166676, 'colsample_bytree': 0.9103274874490116, 'min_child_weight': 9.89521112813443, 'gamma': 0.45624620808148064, 'reg_alpha': 0.0023840731945147815, 'reg_lambda': 4.02067526434441}. Best is trial 28 with value: 0.881979777972656.
[I 2026-08-27 08:31:00,498] Trial 34 finished with value: 0.864317172830612 and parameters: {'max_depth': 10, 'learning_rate': 0.1518842040197946, 'subsample': 0.972546088847288, 'colsample_bytree': 0.86212959718046, 'min_child_weight': 6.099993119114918, 'gamma': 0.5654177682075594, 'reg_alpha': 1.3727077453139833e-05, 'reg_lambda': 1.561814380642602}. Best is trial 28 with value: 0.881979777972656.
[I 2026-08-27 08:31:20,958] Trial 35 finished with value: 0.8766761164733223 and parameters: {'max_depth': 7, 'learning_rate': 0.057010858584817074, 'subsample': 0.9424240064805532, 'colsample_bytree': 0.8100029298045003, 'min_child_weight': 3.971121098849584, 'gamma': 0.17607982394743638, 'reg_alpha': 1.7576291074546322, 'reg_lambda': 0.683470361192524}. Best is trial 28 with value: 0.881979777972656.
[I 2026-08-27 08:31:31,444] Trial 36 finished with value: 0.784370958246851 and parameters: {'max_depth': 6, 'learning_rate': 0.08982640409595438, 'subsample': 0.9140461488336601, 'colsample_bytree': 0.9817231978849792, 'min_child_weight': 2.990249280584988, 'gamma': 2.7487401913156297, 'reg_alpha': 4.132132693963929e-06, 'reg_lambda': 1.2355485254037823}. Best is trial 28 with value: 0.881979777972656.
[I 2026-08-27 08:31:44,372] Trial 37 finished with value: 0.8698186485897276 and parameters: {'max_depth': 10, 'learning_rate': 0.12276122262746605, 'subsample': 0.932375805011315, 'colsample_bytree': 0.8674037391984981, 'min_child_weight': 5.2572706663202045, 'gamma': 0.49783530413082216, 'reg_alpha': 0.02562594847196976, 'reg_lambda': 2.8622239421249454}. Best is trial 28 with value: 0.881979777972656.
[I 2026-08-27 08:32:01,803] Trial 38 finished with value: 0.8825448027926578 and parameters: {'max_depth': 9, 'learning_rate': 0.10031978723371286, 'subsample': 0.8924225652853496, 'colsample_bytree': 0.93813156925849, 'min_child_weight': 6.815700128823182, 'gamma': 0.2736613551856823, 'reg_alpha': 0.14729646187469195, 'reg_lambda': 0.46788856796196493}. Best is trial 38 with value: 0.8825448027926578.
[I 2026-08-27 08:32:21,454] Trial 39 finished with value: 0.8745594795874206 and parameters: {'max_depth': 9, 'learning_rate': 0.07876808535802723, 'subsample': 0.8878213075673229, 'colsample_bytree': 0.9483657085002307, 'min_child_weight': 13.861935169574851, 'gamma': 0.3907145241727707, 'reg_alpha': 4.864594119581704e-08, 'reg_lambda': 0.1255083073345048}. Best is trial 38 with value: 0.8825448027926578.
[I 2026-08-27 08:32:34,833] Trial 40 finished with value: 0.839445128511195 and parameters: {'max_depth': 10, 'learning_rate': 0.05561247359334463, 'subsample': 0.8462516264518701, 'colsample_bytree': 0.9986174516811182, 'min_child_weight': 7.016721571809928, 'gamma': 1.347971371267619, 'reg_alpha': 2.0122101247024515, 'reg_lambda': 0.325677351616332}. Best is trial 38 with value: 0.8825448027926578.
[I 2026-08-27 08:32:52,790] Trial 41 finished with value: 0.8828489454457783 and parameters: {'max_depth': 9, 'learning_rate': 0.10307203944162678, 'subsample': 0.9588046540630358, 'colsample_bytree': 0.9255517550827884, 'min_child_weight': 7.060975218534914, 'gamma': 0.151445675225869, 'reg_alpha': 0.19146783899566103, 'reg_lambda': 0.5207717991609646}. Best is trial 41 with value: 0.8828489454457783.
[I 2026-08-27 08:33:08,725] Trial 42 finished with value: 0.8865851418930649 and parameters: {'max_depth': 9, 'learning_rate': 0.15327631216486937, 'subsample': 0.9529213709820022, 'colsample_bytree': 0.9214776573823018, 'min_child_weight': 7.013110183282827, 'gamma': 0.10642662702366446, 'reg_alpha': 0.30746871869994175, 'reg_lambda': 0.18455137497022647}. Best is trial 42 with value: 0.8865851418930649.
[I 2026-08-27 08:33:31,190] Trial 43 finished with value: 0.8885642507474621 and parameters: {'max_depth': 9, 'learning_rate': 0.14416117925901117, 'subsample': 0.9539029439494215, 'colsample_bytree': 0.9579049288720979, 'min_child_weight': 6.406169878771643, 'gamma': 0.0027489230804911002, 'reg_alpha': 0.24979500393990256, 'reg_lambda': 0.21239121810304054}. Best is trial 43 with value: 0.8885642507474621.
[I 2026-08-27 08:33:45,879] Trial 44 finished with value: 0.8910431212661498 and parameters: {'max_depth': 10, 'learning_rate': 0.14400834671259607, 'subsample': 0.9851398025911507, 'colsample_bytree': 0.9610443932753171, 'min_child_weight': 3.2055025879334256, 'gamma': 0.04484018730534913, 'reg_alpha': 0.20172518317120286, 'reg_lambda': 0.16478488521827642}. Best is trial 44 with value: 0.8910431212661498.
[I 2026-08-27 08:34:01,010] Trial 45 finished with value: 0.8934095587178585 and parameters: {'max_depth': 10, 'learning_rate': 0.14605479901423182, 'subsample': 0.98472289760005, 'colsample_bytree': 0.9722037697949377, 'min_child_weight': 2.461889341097133, 'gamma': 0.008931907202626266, 'reg_alpha': 0.18309087346287928, 'reg_lambda': 0.16920015134750324}. Best is trial 45 with value: 0.8934095587178585.
[I 2026-08-27 08:34:14,054] Trial 46 finished with value: 0.8896207237615219 and parameters: {'max_depth': 10, 'learning_rate': 0.15406256161095544, 'subsample': 0.9968163177634469, 'colsample_bytree': 0.9695673687651456, 'min_child_weight': 2.327966353268698, 'gamma': 0.033949120465310595, 'reg_alpha': 0.3289873033179792, 'reg_lambda': 0.18302234886341742}. Best is trial 45 with value: 0.8934095587178585.
[I 2026-08-27 08:34:28,339] Trial 47 finished with value: 0.8917937893694571 and parameters: {'max_depth': 10, 'learning_rate': 0.15507758072671712, 'subsample': 0.9888059261710743, 'colsample_bytree': 0.9741778130684731, 'min_child_weight': 2.6348447187185493, 'gamma': 0.04007029345848031, 'reg_alpha': 0.6752129962673824, 'reg_lambda': 0.16279881372894608}. Best is trial 45 with value: 0.8934095587178585.
[I 2026-08-27 08:34:39,127] Trial 48 finished with value: 0.8759509833702472 and parameters: {'max_depth': 10, 'learning_rate': 0.1716073086433985, 'subsample': 0.998439823259808, 'colsample_bytree': 0.9708703637889466, 'min_child_weight': 1.5116804587139485, 'gamma': 0.02500231017840442, 'reg_alpha': 4.133181301930363, 'reg_lambda': 0.10417228621425464}. Best is trial 45 with value: 0.8934095587178585.

LOSO comparison written to /Users/airahaghi/Documents/Trishna/Scripts/LSWT-ML-thin-cloud-masking/outputs/leave_one_site_out/leave_one_site_out_results.csv.

{'results': '/Users/airahaghi/Documents/Trishna/Scripts/LSWT-ML-thin-cloud-masking/outputs/leave_one_site_out/leave_one_site_out_results.csv',
 'summary': '/Users/airahaghi/Documents/Trishna/Scripts/LSWT-ML-thin-cloud-masking/outputs/leave_one_site_out/leave_one_site_out_summary_by_model.csv',
 'manifest': '/Users/airahaghi/Documents/Trishna/Scripts/LSWT-ML-thin-cloud-masking/outputs/leave_one_site_out/leave_one_site_out_manifest.json'}

## 3. Inspect per-site and across-site robustness

In [4]:
columns = [
    "held_out_site", "model",
    "train_balanced_accuracy",
    "test_balanced_accuracy",
    "leave_out_site_balanced_accuracy",
    "cv_selection_score_mean",
    "cv_selection_score_std",
    "model_path",
]
loso_result["results"][columns]

,held_out_site,model,train_balanced_accuracy,test_balanced_accuracy,leave_out_site_balanced_accuracy,cv_selection_score_mean,cv_selection_score_std,model_path
0,ageri,decision_tree,0.979093,0.514771,0.447309,0.770884,0.005259,/Users/airahaghi/Documents/Trishna/Scripts/LSW...
1,ageri,random_forest,1.000000,0.591702,0.447770,0.866919,0.004889,/Users/airahaghi/Documents/Trishna/Scripts/LSW...
2,ageri,xgboost,1.000000,0.589719,0.450999,0.887538,0.006792,/Users/airahaghi/Documents/Trishna/Scripts/LSW...
3,bianco,decision_tree,0.998832,0.513764,0.223253,0.783450,0.007787,/Users/airahaghi/Documents/Trishna/Scripts/LSW...
4,bianco,random_forest,1.000000,0.556266,0.172798,0.876120,0.004257,/Users/airahaghi/Documents/Trishna/Scripts/LSW...
5,bianco,xgboost,1.000000,0.561460,0.395196,0.893878,0.003507,/Users/airahaghi/Documents/Trishna/Scripts/LSW...
6,geneva,decision_tree,1.000000,0.475172,0.462393,0.829066,0.006319,/Users/airahaghi/Documents/Trishna/Scripts/LSW...
7,geneva,random_forest,1.000000,0.511905,0.488964,0.903275,0.005840,/Users/airahaghi/Documents/Trishna/Scripts/LSW...
8,geneva,xgboost,1.000000,0.517801,0.496206,0.919213,0.008527,/Users/airahaghi/Documents/Trishna/Scripts/LSW...
9,greifensee,decision_tree,0.993749,0.465735,0.536441,0.785863,0.003106,/Users/airahaghi/Documents/Trishna/Scripts/LSW...
10,greifensee,random_forest,1.000000,0.510546,0.665474,0.882273,0.005203,/Users/airahaghi/Documents/Trishna/Scripts/LSW...
11,greifensee,xgboost,1.000000,0.517088,0.687257,0.897321,0.004743,/Users/airahaghi/Documents/Trishna/Scripts/LSW...
12,mendota,decision_tree,0.940556,0.493603,0.485278,0.769987,0.005712,/Users/airahaghi/Documents/Trishna/Scripts/LSW...
13,mendota,random_forest,1.000000,0.558194,0.544259,0.874301,0.002040,/Users/airahaghi/Documents/Trishna/Scripts/LSW...
14,mendota,xgboost,1.000000,0.558889,0.557593,0.892286,0.002521,/Users/airahaghi/Documents/Trishna/Scripts/LSW...
15,venice,decision_tree,0.985553,0.517624,0.461617,0.781476,0.010567,/Users/airahaghi/Documents/Trishna/Scripts/LSW...
16,venice,random_forest,1.000000,0.549278,0.512449,0.879006,0.004725,/Users/airahaghi/Documents/Trishna/Scripts/LSW...
17,venice,xgboost,1.000000,0.550547,0.527597,0.896094,0.004071,/Users/airahaghi/Documents/Trishna/Scripts/LSW...

In [5]:
loso_result["summary"]

,model,n_sites,train_balanced_accuracy_mean,train_balanced_accuracy_std,train_balanced_accuracy_min,train_balanced_accuracy_max,test_balanced_accuracy_mean,test_balanced_accuracy_std,test_balanced_accuracy_min,test_balanced_accuracy_max,leave_out_site_balanced_accuracy_mean,leave_out_site_balanced_accuracy_std,leave_out_site_balanced_accuracy_min,leave_out_site_balanced_accuracy_max
0,decision_tree,6,0.982964,0.022264,0.940556,1.0,0.496778,0.022304,0.465735,0.517624,0.436049,0.108866,0.223253,0.536441
1,random_forest,6,1.000000,0.000000,1.000000,1.0,0.546315,0.030895,0.510546,0.591702,0.471952,0.164126,0.172798,0.665474
2,xgboost,6,1.000000,0.000000,1.000000,1.0,0.549251,0.027946,0.517088,0.589719,0.519141,0.100344,0.395196,0.687257

Each `datasets/held_out_*` folder contains its train, scene-disjoint test, held-out-site CSVs, split summary, and `scene_split_manifest.csv`. Each parallel `models/held_out_*` folder contains the three final models, one study and trials table per classifier, detailed metrics, confusion matrices, classification reports, and metadata. The root results CSV provides the 18 site/model comparisons.